Add support for command-line option -h for command help.

diff --git a/askpass b/askpass
--- a/askpass
+++ b/askpass
@@ -22,7 +22,7 @@ abort() {
 }
 
 assert() {
-    "$@" || abort "%s: Assertion failed: %s\n" "$0" "$*"
+    "$@" || abort "%s: Assertion failed: %s\n" "$script" "$*"
 }
 
 parse_arguments() {
@@ -50,7 +50,7 @@ parse_arguments() {
     shift $(($OPTIND - 1))
 
     if [ $is_query = true -a $# -gt 0 ]; then
-	usage_error "%s: Too many arguments\n" "$0"
+	usage_error "%s: Too many arguments\n" "$script"
     elif [ $# -gt 0 ]; then
 	commands="$*"
     else
@@ -60,9 +60,9 @@ parse_arguments() {
 
 usage() {
     cat <<EOF >&2
-Usage: $0 [-s SHELL] [COMMAND [COMMAND] ...]
-       $0 -q
-       $0 -h
+Usage: $script [-s SHELL] [COMMAND [COMMAND] ...]
+       $script -q
+       $script -h
 EOF
 }
 
@@ -75,6 +75,8 @@ usage_error() {
     usage
     exit 2
 }
+
+script=$(basename "$0")
 
 case "$0" in
     (*/*)
diff --git a/get-askpass-helper b/get-askpass-helper
--- a/get-askpass-helper
+++ b/get-askpass-helper
@@ -24,15 +24,15 @@ abort() {
 }
 
 abort_desktop_not_supported() {
-    abort "%s: %s: Desktop not supported\n" "$0" "$desktop_name"
+    abort "%s: %s: Desktop not supported\n" "$script" "$desktop_name"
 }
 
 abort_not_supported() {
-    abort "%s: %s: %s not supported\n" "$0" "$PRETTY_NAME" "$*"
+    abort "%s: %s: %s not supported\n" "$script" "$PRETTY_NAME" "$*"
 }
 
 assert() {
-    "$@" || abort "%s: Assertion failed: %s\n" "$0" "$*"
+    "$@" || abort "%s: Assertion failed: %s\n" "$script" "$*"
 }
 
 configure_platform() {
@@ -104,12 +104,35 @@ get_helper() {
 }
 
 parse_arguments() {
+    while getopts h opt; do
+	case $opt in
+	    (h)
+		usage
+		exit 0
+		;;
+	    (\?)
+		exit 2
+		;;
+	esac
+    done
+
+    shift $(($OPTIND - 1))
+
     if [ $# -eq 1 ]; then
 	desktop_name="$1"
     else
 	desktop_name=$("${script_prefix}get-desktop-name")
     fi
 }
+
+usage() {
+    cat <<EOF >&2
+Usage: $script [DESKTOP-ENVIRONMENT]
+       $script -h
+EOF
+}
+
+script=$(basename "$0")
 
 case "$0" in
     (*/*)
diff --git a/get-askpass-package b/get-askpass-package
--- a/get-askpass-package
+++ b/get-askpass-package
@@ -22,7 +22,7 @@ abort() {
 }
 
 assert() {
-    "$@" || abort "%s: Assertion failed: %s\n" "$0" "$*"
+    "$@" || abort "%s: Assertion failed: %s\n" "$script" "$*"
 }
 
 get_askpass_package() {
@@ -105,12 +105,35 @@ get_askpass_package() {
 }
 
 parse_arguments() {
+    while getopts h opt; do
+	case $opt in
+	    (h)
+		usage
+		exit 0
+		;;
+	    (\?)
+		exit 2
+		;;
+	esac
+    done
+
+    shift $(($OPTIND - 1))
+
     if [ $# -eq 1 ]; then
 	desktop_name="$1"
     else
 	desktop_name=$("${script_prefix}get-desktop-name")
     fi
 }
+
+usage() {
+    cat <<EOF >&2
+Usage: $script [DESKTOP-ENVIRONMENT]
+       $script -h
+EOF
+}
+
+script=$(basename "$0")
 
 case "$0" in
     (*/*)
