Prefer single- to double-quotes to enclose printf format strings.

diff --git a/askpass b/askpass
--- a/askpass
+++ b/askpass
@@ -22,7 +22,7 @@ abort() {
 }
 
 assert() {
-    "$@" || abort "%s: Assertion failed: %s\n" "$script" "$*"
+    "$@" || abort '%s: Assertion failed: %s\n' "$script" "$*"
 }
 
 parse_arguments() {
@@ -50,7 +50,7 @@ parse_arguments() {
     shift $(($OPTIND - 1))
 
     if [ $is_query = true -a $# -gt 0 ]; then
-	usage_error "%s: Too many arguments\n" "$script"
+	usage_error '%s: Too many arguments\n' "$script"
     elif [ $# -gt 0 ]; then
 	commands="$*"
     else
@@ -71,7 +71,7 @@ usage_error() {
 	printf "$@" >&2
     fi
 
-    printf "%s\n" '' >&2
+    printf '%s\n' '' >&2
     usage
     exit 2
 }
diff --git a/build-images b/build-images
--- a/build-images
+++ b/build-images
@@ -24,7 +24,7 @@ abort() {
 }
 
 assert() {
-    "$@" || abort "%s: Assertion failed: %s\n" "$0" "$*"
+    "$@" || abort '%s: Assertion failed: %s\n' "$0" "$*"
 }
 
 build_images() {
@@ -37,7 +37,7 @@ build_image() (
     assert [ $# -eq 1 ]
     assert [ -n "$1" ]
     dir=$1
-    image=$(printf "%s\n" "$dir" | get_image_name)
+    image=$(printf '%s\n' "$dir" | get_image_name)
     image_method=$(get_image_method $image)
     method_command=$(get_command $image_method)
     remote_image=$(get_remote_image_name)
@@ -83,19 +83,19 @@ get_build_subcommand() {
 
     case "$1" in
 	(buildah)
-	    printf "%s\n" \
+	    printf '%s\n' \
 		   build-using-dockerfile \
 		   $(get_buildah_bud_options "$2") \
 		   -t "$2" .
 	    ;;
 	(buildx)
-	    printf "%s\n" \
+	    printf '%s\n' \
 		   buildx build \
 		   $(get_docker_buildx_options) \
 		   --load -t "$2" .
 	    ;;
 	(*)
-	    printf "%s\n" build -t "$2" .
+	    printf '%s\n' build -t "$2" .
 	    ;;
     esac
 }
@@ -116,13 +116,13 @@ get_command() {
 
     case "$1" in
 	(buildah)
-	    printf "%s\n" buildah
+	    printf '%s\n' buildah
 	    ;;
 	(podman)
-	    printf "%s\n" podman
+	    printf '%s\n' podman
 	    ;;
 	(*)
-	    printf "%s\n" docker
+	    printf '%s\n' docker
 	    ;;
     esac
 }
@@ -136,7 +136,7 @@ get_default_capabilities() {
 	    capabilities=$("${script_prefix}get-db2-capabilities")
 
 	    if [ -n "$capabilities" ]; then
-		printf "%s\n" $capabilities
+		printf '%s\n' $capabilities
 	    fi
 	    ;;
     esac
@@ -148,10 +148,10 @@ get_default_method() {
 
     case "$1" in
 	(*-ibm-db2-*)
-	    printf "%s\n" buildah
+	    printf '%s\n' buildah
 	    ;;
 	(*)
-	    printf "%s\n" docker
+	    printf '%s\n' docker
 	    ;;
     esac
 }
@@ -167,17 +167,17 @@ get_dockerfiles() {
 }
 
 get_image_dir_prefix() {
-    printf "%s\n" "${IMAGE_DIR_PREFIX-docker}-"
+    printf '%s\n' "${IMAGE_DIR_PREFIX-docker}-"
 }
 
 get_image_dir_root() {
-    printf "%s\n" "$(cd "${IMAGE_DIR_ROOT-$HOME}" && pwd)"
+    printf '%s\n' "$(cd "${IMAGE_DIR_ROOT-$HOME}" && pwd)"
 }
 
 get_image_method() {
     assert [ $# -eq 1 ]
     assert [ -n "$1" ]
-    printf "%s\n" "${method:-$(get_default_method "$1")}"
+    printf '%s\n' "${method:-$(get_default_method "$1")}"
 }
 
 get_image_name() {
@@ -188,7 +188,7 @@ get_image_name() {
 }
 
 get_remote_image_name() {
-    printf "%s%s%s:%s\n" \
+    printf '%s%s%s:%s\n' \
 	   "${IMAGE_REMOTE_BASE_URL:+${IMAGE_REMOTE_BASE_URL#*//}/}" \
 	   "${IMAGE_REMOTE_DIR:+$IMAGE_REMOTE_DIR/}" \
 	   "${image#*/}" \
@@ -225,7 +225,7 @@ parse_arguments() {
 			method="$OPTARG"
 			;;
 		    (*)
-			usage_error "%s: %s: Invalid method\n" "$0" "$OPTARG"
+			usage_error '%s: %s: Invalid method\n' "$0" "$OPTARG"
 			;;
 		esac
 		;;
@@ -268,13 +268,13 @@ parse_arguments() {
 		    dockerfiles="${dockerfiles+$dockerfiles }$file"
 		    ;;
 		(*)
-		    abort "%s: %s: Not a Dockerfile\n" "$0" "$file"
+		    abort '%s: %s: Not a Dockerfile\n' "$0" "$file"
 		    ;;
 	    esac
 	elif [ -e "$file" ]; then
-	    abort "%s: %s: Not a Dockerfile\n" "$0" "$file"
+	    abort '%s: %s: Not a Dockerfile\n' "$0" "$file"
 	else
-	    abort "%s: %s: No such file\n" "$0" "$file"
+	    abort '%s: %s: No such file\n' "$0" "$file"
 	fi
     done
 }
@@ -291,7 +291,7 @@ usage_error() {
 	printf "$@" >&2
     fi
 
-    printf "%s\n" '' >&2
+    printf '%s\n' '' >&2
     usage
     exit 2
 }
diff --git a/build-uwsgi b/build-uwsgi
--- a/build-uwsgi
+++ b/build-uwsgi
@@ -22,7 +22,7 @@ abort() {
 }
 
 assert() {
-    "$@" || abort "%s: Assertion failed: %s\n" "$0" "$*"
+    "$@" || abort '%s: Assertion failed: %s\n' "$0" "$*"
 }
 
 build_binary() (
@@ -83,7 +83,7 @@ get_options() {
 	    ;;
     esac
 
-    printf "%s\n" "$options"
+    printf '%s\n' "$options"
 }
 
 usage_error() {
@@ -92,13 +92,13 @@ usage_error() {
 }
 
 if [ $# -lt 2 ]; then
-    usage_error "%s: Not enough arguments\n" "$0"
+    usage_error '%s: Not enough arguments\n' "$0"
 elif [ $# -gt 2 ]; then
-    usage_error "%s: Too many arguments\n" "$0"
+    usage_error '%s: Too many arguments\n' "$0"
 fi
 
 if [ "$(id -u)" -eq 0 ]; then
-    abort "%s: Must be run as a non-privileged user\n" "$0"
+    abort '%s: Must be run as a non-privileged user\n' "$0"
 fi
 
 case "$0" in
diff --git a/check-python b/check-python
--- a/check-python
+++ b/check-python
@@ -19,7 +19,7 @@ abort() {
 }
 
 assert() {
-    "$@" || abort "%s: Assertion failed: %s\n" "$0" "$*"
+    "$@" || abort '%s: Assertion failed: %s\n' "$0" "$*"
 }
 
 usage_error() {
@@ -28,9 +28,9 @@ usage_error() {
 }
 
 if [ $# -lt 1 ]; then
-    usage_error "%s: Not enough arguments\n" "$0"
+    usage_error '%s: Not enough arguments\n' "$0"
 elif [ $# -gt 1 ]; then
-    usage_error "%s: Too many arguments\n" "$0"
+    usage_error '%s: Too many arguments\n' "$0"
 fi
 
 . common-functions.sh
diff --git a/clean-up-kernel-packages b/clean-up-kernel-packages
--- a/clean-up-kernel-packages
+++ b/clean-up-kernel-packages
@@ -24,11 +24,11 @@ abort() {
 }
 
 abort_not_supported() {
-    abort "%s: %s: %s not supported\n" "$0" "$PRETTY_NAME" "$*"
+    abort '%s: %s: %s not supported\n' "$0" "$PRETTY_NAME" "$*"
 }
 
 assert() {
-    "$@" || abort "%s: Assertion failed: %s\n" "$0" "$*"
+    "$@" || abort '%s: Assertion failed: %s\n' "$0" "$*"
 }
 
 clean_up_kernel_dumps() {
@@ -120,7 +120,7 @@ validate_platform() {
 }
 
 if [ $# -gt 0 ]; then
-    usage_error "%s: Too many arguments\n" "$0"
+    usage_error '%s: Too many arguments\n' "$0"
 fi
 
 case "$0" in
diff --git a/configure-docker-proxy b/configure-docker-proxy
--- a/configure-docker-proxy
+++ b/configure-docker-proxy
@@ -26,7 +26,7 @@ abort() {
 }
 
 assert() {
-    "$@" || abort "%s: Assertion failed: %s\n" "$script" "$*"
+    "$@" || abort '%s: Assertion failed: %s\n' "$script" "$*"
 }
 
 clean_up() {
@@ -137,7 +137,7 @@ parse_arguments() {
     fi
 
     if [ $# -gt 0 ]; then
-	usage_error "%s: Too many arguments\n" "$script"
+	usage_error '%s: Too many arguments\n' "$script"
     fi
 }
 
@@ -145,7 +145,7 @@ parse_input_file() {
     if is_valid_input_file "$1"; then
 	input="$1"
     else
-	usage_error "%s: %s: No such file or no permissions\n" "$script" "$1"
+	usage_error '%s: %s: No such file or no permissions\n' "$script" "$1"
     fi
 }
 
diff --git a/configure-emacs b/configure-emacs
--- a/configure-emacs
+++ b/configure-emacs
@@ -29,23 +29,23 @@ abort() {
 }
 
 abort_invalid_prefix() {
-    usage_error "%s: invalid prefix -- %s\n" "$0" "$*"
+    usage_error '%s: invalid prefix -- %s\n' "$0" "$*"
 }
 
 abort_invalid_toolkit() {
-    usage_error "%s: invalid toolkit -- %s\n" "$0" "$*"
+    usage_error '%s: invalid toolkit -- %s\n' "$0" "$*"
 }
 
 abort_invalid_version() {
-    usage_error "%s: invalid version -- %s\n" "$0" "$*"
+    usage_error '%s: invalid version -- %s\n' "$0" "$*"
 }
 
 abort_not_supported() {
-    abort "%s: %s: %s not supported\n" "$0" "$PRETTY_NAME" "$*"
+    abort '%s: %s: %s not supported\n' "$0" "$PRETTY_NAME" "$*"
 }
 
 assert() {
-    "$@" || abort "%s: Assertion failed: %s\n" "$0" "$*"
+    "$@" || abort '%s: Assertion failed: %s\n' "$0" "$*"
 }
 
 clean_build() {
@@ -96,7 +96,7 @@ configure_emacs() {
 	exit 0
     fi
 
-    printf "%s\n" "$command"
+    printf '%s\n' "$command"
     eval $command
 }
 
@@ -137,7 +137,7 @@ configure_platform() {
     done
 
     if [ -n "${cc-}" ] && [ ! -x $cc ]; then
-	abort "%s: %s: No such compiler\n" "$0" "$cc"
+	abort '%s: %s: No such compiler\n' "$0" "$cc"
     fi
 }
 
@@ -193,12 +193,12 @@ extract_files() {
 }
 
 get_compiler() {
-    printf "%s\n" "$1"
+    printf '%s\n' "$1"
 }
 
 get_compiler_flags() {
     shift
-    printf "%s\n" "$*"
+    printf '%s\n' "$*"
 }
 
 get_configure_command() {
@@ -264,7 +264,7 @@ get_configure_options() {
     fi
 
     if [ -n "${options:-}" ]; then
-	printf "%s\n" "$options"
+	printf '%s\n' "$options"
     fi
 }
 
@@ -294,7 +294,7 @@ get_linker_flags() {
     done
 
     if [ "${ldflags-}" ]; then
-	printf "%s\n" "$ldflags"
+	printf '%s\n' "$ldflags"
     fi
 }
 
@@ -304,7 +304,7 @@ get_pkg_config_path() {
     done
 
     if [ "${pkg_config_path-}" ]; then
-	printf "%s\n" "$pkg_config_path"
+	printf '%s\n' "$pkg_config_path"
     fi
 }
 
@@ -400,11 +400,11 @@ parse_arguments() {
     shift $(($OPTIND - 1))
 
     if [ $# -gt 0 ]; then
-	usage_error "%s: Too many arguments\n" "$0"
+	usage_error '%s: Too many arguments\n' "$0"
     fi
 
     if [ "$with_gif" = true -a -n "${libgif-}" ] && [ ! -x $libgif ]; then
-	abort "%s: %s: No such shared object\n" "$0" "$libgif"
+	abort '%s: %s: No such shared object\n' "$0" "$libgif"
     fi
 }
 
@@ -420,7 +420,7 @@ usage_error() {
 	printf "$@" >&2
     fi
 
-    printf "%s\n" '' >&2
+    printf '%s\n' '' >&2
     usage
     exit 2
 }
diff --git a/configure-giflib b/configure-giflib
--- a/configure-giflib
+++ b/configure-giflib
@@ -30,19 +30,19 @@ abort() {
 }
 
 abort_invalid_prefix() {
-    usage_error "%s: invalid prefix -- %s\n" "$0" "$*"
+    usage_error '%s: invalid prefix -- %s\n' "$0" "$*"
 }
 
 abort_invalid_version() {
-    usage_error "%s: invalid version -- %s\n" "$0" "$*"
+    usage_error '%s: invalid version -- %s\n' "$0" "$*"
 }
 
 abort_not_supported() {
-    abort "%s: %s: %s not supported\n" "$0" "$PRETTY_NAME" "$*"
+    abort '%s: %s: %s not supported\n' "$0" "$PRETTY_NAME" "$*"
 }
 
 assert() {
-    "$@" || abort "%s: Assertion failed: %s\n" "$0" "$*"
+    "$@" || abort '%s: Assertion failed: %s\n' "$0" "$*"
 }
 
 configure_giflib() {
@@ -54,7 +54,7 @@ configure_giflib() {
     pathname=$archive_dir/$filename
 
     if [ ! -f $pathname ]; then
-	abort "%s: %s: No such archive file\n" "$0" "$pathname"
+	abort '%s: %s: No such archive file\n' "$0" "$pathname"
     fi
 
     src_dir="$HOME/Documents/src/GIFLIB/$basename"
@@ -110,7 +110,7 @@ usage_error() {
 	printf "$@" >&2
     fi
 
-    printf "%s\n" '' >&2
+    printf '%s\n' '' >&2
     usage
     exit 2
 }
diff --git a/configure-git b/configure-git
--- a/configure-git
+++ b/configure-git
@@ -28,19 +28,19 @@ abort() {
 }
 
 abort_invalid_prefix() {
-    usage_error "%s: invalid prefix -- %s\n" "$0" "$*"
+    usage_error '%s: invalid prefix -- %s\n' "$script" "$*"
 }
 
 abort_invalid_toolkit() {
-    usage_error "%s: invalid toolkit -- %s\n" "$0" "$*"
+    usage_error '%s: invalid toolkit -- %s\n' "$script" "$*"
 }
 
 abort_not_supported() {
-    abort "%s: %s: %s not supported\n" "$0" "$PRETTY_NAME" "$*"
+    abort '%s: %s: %s not supported\n' "$script" "$PRETTY_NAME" "$*"
 }
 
 assert() {
-    "$@" || abort "%s: Assertion failed: %s\n" "$0" "$*"
+    "$@" || abort '%s: Assertion failed: %s\n' "$script" "$*"
 }
 
 chown_real_user() {
@@ -95,7 +95,7 @@ configure_git() {
     fi
 
     $make configure
-    printf "%s\n" "$command"
+    printf '%s\n' "$command"
     eval $command
 
     if [ "$build" = true ]; then
@@ -136,11 +136,11 @@ configure_platform() {
     done
 
     if [ -n "${cc-}" ] && [ ! -x $cc ]; then
-	abort "%s: %s: No such compiler\n" "$0" "$cc"
+	abort '%s: %s: No such compiler\n' "$script" "$cc"
     fi
 
     if [ -n "${libgif-}" ] && [ ! -x $libgif ]; then
-	abort "%s: %s: No such shared object\n" "$0" "$libgif"
+	abort '%s: %s: No such shared object\n' "$script" "$libgif"
     fi
 }
 
@@ -192,12 +192,12 @@ extract_files() {
 }
 
 get_compiler() {
-    printf "%s\n" "$1"
+    printf '%s\n' "$1"
 }
 
 get_compiler_flags() {
     shift
-    printf "%s\n" "$*"
+    printf '%s\n' "$*"
 }
 
 get_configure_command() {
@@ -233,7 +233,7 @@ get_configure_command() {
 
 get_configure_options() {
     if [ -n "${options:-}" ]; then
-	printf "%s\n" "$options"
+	printf '%s\n' "$options"
     fi
 }
 
@@ -263,7 +263,7 @@ get_linker_flags() {
     done
 
     if [ "${ldflags-}" ]; then
-	printf "%s\n" "$ldflags"
+	printf '%s\n' "$ldflags"
     fi
 }
 
@@ -273,7 +273,7 @@ get_pkg_config_path() {
     done
 
     if [ "${pkg_config_path-}" ]; then
-	printf "%s\n" "$pkg_config_path"
+	printf '%s\n' "$pkg_config_path"
     fi
 }
 
@@ -347,14 +347,14 @@ parse_arguments() {
     shift $(($OPTIND - 1))
 
     if [ $# -gt 0 ]; then
-	usage_error "%s: Too many arguments\n" "$0"
+	usage_error '%s: Too many arguments\n' "$script"
     fi
 }
 
 usage() {
     cat <<EOF >&2
-Usage: $0 [-b] [-f] [-n] [-p PREFIX]
-       $0 -h
+Usage: $script [-b] [-f] [-n] [-p PREFIX]
+       $script -h
 EOF
 }
 
@@ -363,7 +363,7 @@ usage_error() {
 	printf "$@" >&2
     fi
 
-    printf "%s\n" '' >&2
+    printf '%s\n' '' >&2
     usage
     exit 2
 }
@@ -425,6 +425,8 @@ validate_platform() {
 	    ;;
     esac
 }
+
+script=$(basename "$0")
 
 case "$0" in
     (*/*)
diff --git a/configure-hyper-v-guest b/configure-hyper-v-guest
--- a/configure-hyper-v-guest
+++ b/configure-hyper-v-guest
@@ -30,7 +30,7 @@ abort() {
 }
 
 assert() {
-    "$@" || abort "%s: Assertion failed: %s\n" "$0" "$*"
+    "$@" || abort '%s: Assertion failed: %s\n' "$0" "$*"
 }
 
 configure_hyper_v_guest() {
@@ -38,7 +38,7 @@ configure_hyper_v_guest() {
     update=$(get_grub_update_command)
 
     if [ -z "$update" ]; then
-	abort "%s: No grub update command detected\n" "$0"
+	abort '%s: No grub update command detected\n' "$0"
     fi
 
     if edit_grub_defaults "$GRUB_DEFAULTS_FILE"; then
@@ -54,10 +54,10 @@ configure_platform() {
 	    true
 	    ;;
 	('')
-	    abort "%s: No hypervisor detected\n" "$0"
+	    abort '%s: No hypervisor detected\n' "$0"
 	    ;;
 	(*)
-	    abort "%s: %s hypervisor not supported\n" "$0" "$vendor"
+	    abort '%s: %s hypervisor not supported\n' "$0" "$vendor"
 	    ;;
     esac
 }
@@ -78,10 +78,10 @@ edit_grub_defaults() {
 get_awk_command() {
     case "${kernel_name=$(uname -s)}" in
 	(SunOS)
-	    printf "%s\n" /usr/gnu/bin/awk
+	    printf '%s\n' /usr/gnu/bin/awk
 	    ;;
 	(*)
-	    printf "%s\n" /usr/bin/awk
+	    printf '%s\n' /usr/bin/awk
 	    ;;
     esac
 }
@@ -89,7 +89,7 @@ get_awk_command() {
 get_grub_update_command() {
     for command in $GRUB_COMMANDS; do
 	if which $command >/dev/null 2>&1; then
-	    printf "%s\n" "$command"
+	    printf '%s\n' "$command"
 	    break
 	fi
     done
@@ -101,13 +101,13 @@ get_grub_update_options() {
 
     case "$1" in
 	(grub-mkconfig)
-	    printf "%s\n" -o /boot/grub/grub.cfg
+	    printf '%s\n' -o /boot/grub/grub.cfg
 	    ;;
 	(grub2-mkconfig)
-	    printf "%s\n" -o /boot/grub2/grub.cfg
+	    printf '%s\n' -o /boot/grub2/grub.cfg
 	    ;;
 	(grubby)
-	    printf "%s\n" --update-kernel=ALL --args="$KERNEL_ARG"
+	    printf '%s\n' --update-kernel=ALL --args="$KERNEL_ARG"
 	    ;;
     esac
 }
diff --git a/configure-python b/configure-python
--- a/configure-python
+++ b/configure-python
@@ -29,19 +29,19 @@ abort() {
 }
 
 abort_invalid_prefix() {
-    usage_error "%s: invalid prefix -- %s\n" "$0" "$*"
+    usage_error '%s: invalid prefix -- %s\n' "$0" "$*"
 }
 
 abort_invalid_version() {
-    usage_error "%s: invalid version -- %s\n" "$0" "$*"
+    usage_error '%s: invalid version -- %s\n' "$0" "$*"
 }
 
 abort_not_supported() {
-    abort "%s: %s: %s not supported\n" "$0" "$PRETTY_NAME" "$*"
+    abort '%s: %s: %s not supported\n' "$0" "$PRETTY_NAME" "$*"
 }
 
 assert() {
-    "$@" || abort "%s: Assertion failed: %s\n" "$0" "$*"
+    "$@" || abort '%s: Assertion failed: %s\n' "$0" "$*"
 }
 
 clean_build() {
@@ -95,7 +95,7 @@ configure_platform() {
     done
 
     if [ -n "${cc-}" ] && [ ! -x $cc ]; then
-	abort "%s: %s: No such compiler\n" "$0" "$cc"
+	abort '%s: %s: No such compiler\n' "$0" "$cc"
     fi
 }
 
@@ -145,7 +145,7 @@ configure_python() {
 	exit 0
     fi
 
-    printf "%s\n" "$command"
+    printf '%s\n' "$command"
     eval $command
 }
 
@@ -175,12 +175,12 @@ extract_files() {
 }
 
 get_compiler() {
-    printf "%s\n" "$1"
+    printf '%s\n' "$1"
 }
 
 get_compiler_flags() {
     shift
-    printf "%s\n" "$*"
+    printf '%s\n' "$*"
 }
 
 get_configure_command() {
@@ -218,7 +218,7 @@ get_configure_options() {
     options=
 
     if [ -n "${options:-}" ]; then
-	printf "%s\n" "$options"
+	printf '%s\n' "$options"
     fi
 }
 
@@ -252,7 +252,7 @@ get_linker_flags() {
     done
 
     if [ "${ldflags-}" ]; then
-	printf "%s\n" "$ldflags"
+	printf '%s\n' "$ldflags"
     fi
 }
 
@@ -262,7 +262,7 @@ get_pkg_config_path() {
     done
 
     if [ "${pkg_config_path-}" ]; then
-	printf "%s\n" "$pkg_config_path"
+	printf '%s\n' "$pkg_config_path"
     fi
 }
 
@@ -356,7 +356,7 @@ parse_arguments() {
     shift $(($OPTIND - 1))
 
     if [ $# -gt 0 ]; then
-	usage_error "%s: Too many arguments\n" "$0"
+	usage_error '%s: Too many arguments\n' "$0"
     fi
 }
 
@@ -372,7 +372,7 @@ usage_error() {
 	printf "$@" >&2
     fi
 
-    printf "%s\n" '' >&2
+    printf '%s\n' '' >&2
     usage
     exit 2
 }
diff --git a/create-app-database b/create-app-database
--- a/create-app-database
+++ b/create-app-database
@@ -22,7 +22,7 @@ abort() {
 }
 
 assert() {
-    "$@" || abort "%s: Assertion failed: %s\n" "$0" "$*"
+    "$@" || abort '%s: Assertion failed: %s\n' "$0" "$*"
 }
 
 usage_error() {
@@ -31,7 +31,7 @@ usage_error() {
 }
 
 if [ $# -gt 0 ]; then
-    usage_error "%s: Too many arguments\n" "$0"
+    usage_error '%s: Too many arguments\n' "$0"
 fi
 
 case "$0" in
diff --git a/docker-run-database-client b/docker-run-database-client
--- a/docker-run-database-client
+++ b/docker-run-database-client
@@ -24,7 +24,7 @@ abort() {
 }
 
 assert() {
-    "$@" || abort "%s: Assertion failed: %s\n" "$0" "$*"
+    "$@" || abort '%s: Assertion failed: %s\n' "$0" "$*"
 }
 
 docker_run_database_client() {
@@ -36,7 +36,7 @@ docker_run_database_client() {
 get_database_client_command() {
     case "$DATABASE_DIALECT" in
 	(mysql)
-	    printf "%s\n" mysql \
+	    printf '%s\n' mysql \
 		   --protocol=${DATABASE_PROTOCOL:-TCP} \
 		   --host=${DATABASE_HOST:-localhost} \
 		   --port=${DATABASE_PORT:-3306} \
@@ -44,11 +44,11 @@ get_database_client_command() {
 		   --password=${DATABASE_PASSWORD:-}
 	    ;;
 	(oracle)
-	    printf "%s\n" sqlplus \
+	    printf '%s\n' sqlplus \
 		   "system/${DATABASE_PASSWORD}@//localhost:5121/ORCLCDB"
 	    ;;
 	(postgresql)
-	    printf "%s\n" psql \
+	    printf '%s\n' psql \
 		   --host=${DATABASE_HOST:-localhost} \
 		   --port=${DATABASE_PORT:-5432} \
 		   --username=${DATABASE_USER:-$USER} \
@@ -60,13 +60,13 @@ get_database_client_command() {
 get_database_image_name() {
     case "$DATABASE_DIALECT" in
 	(mysql)
-	    printf "%s\n" mysql
+	    printf '%s\n' mysql
 	    ;;
 	(oracle)
-	    printf "%s\n" oracle/database:19.3.0-se2
+	    printf '%s\n' oracle/database:19.3.0-se2
 	    ;;
 	(postgresql)
-	    printf "%s\n" postgres
+	    printf '%s\n' postgres
 	    ;;
     esac
 }
@@ -80,7 +80,7 @@ parse_arguments() {
 }
 
 if [ ! -r $ENV_FILE ]; then
-    abort "%s: %s: No such environment file\n" "$0" $ENV_FILE
+    abort '%s: %s: No such environment file\n' "$0" $ENV_FILE
 fi
 
 if [ -r $HOME/${ENV_FILE-.env} ]; then
diff --git a/docker-run-database-server b/docker-run-database-server
--- a/docker-run-database-server
+++ b/docker-run-database-server
@@ -22,7 +22,7 @@ abort() {
 }
 
 assert() {
-    "$@" || abort "%s: Assertion failed: %s\n" "$0" "$*"
+    "$@" || abort '%s: Assertion failed: %s\n' "$0" "$*"
 }
 
 docker_run_database_server() {
@@ -33,10 +33,10 @@ docker_run_database_server() {
 get_container_port() {
     case "$DATABASE_DIALECT" in
 	(mysql)
-	    printf "%s\n" 3306
+	    printf '%s\n' 3306
 	    ;;
 	(postgresql)
-	    printf "%s\n" 5432
+	    printf '%s\n' 5432
 	    ;;
     esac
 }
@@ -44,10 +44,10 @@ get_container_port() {
 get_docker_image_name() {
     case "$DATABASE_DIALECT" in
 	(mysql)
-	    printf "%s\n" mysql
+	    printf '%s\n' mysql
 	    ;;
 	(postgresql)
-	    printf "%s\n" postgres
+	    printf '%s\n' postgres
 	    ;;
     esac
 }
@@ -56,7 +56,7 @@ get_docker_options() {
     case "$DATABASE_DIALECT" in
 	(mysql)
 	    . ./.env-mysql
-	    printf "%s\n" \
+	    printf '%s\n' \
 		   -e MYSQL_DATABASE=$MYSQL_DATABASE \
 		   -e MYSQL_USER=$MYSQL_USER \
 		   -e MYSQL_PASSWORD=$MYSQL_PASSWORD \
@@ -65,7 +65,7 @@ get_docker_options() {
 	    ;;
 	(postgresql)
 	    . ./.env-postgres
-	    printf "%s\n" \
+	    printf '%s\n' \
 		   -e POSTGRES_DB=$POSTGRES_DB \
 		   -e POSTGRES_USER=$POSTGRES_USER \
 		   -e POSTGRES_PASSWORD=$POSTGRES_PASSWORD \
diff --git a/docker-run-ibm-db2-server b/docker-run-ibm-db2-server
--- a/docker-run-ibm-db2-server
+++ b/docker-run-ibm-db2-server
@@ -26,7 +26,7 @@ abort() {
 }
 
 assert() {
-    "$@" || abort "%s: Assertion failed: %s\n" "$0" "$*"
+    "$@" || abort '%s: Assertion failed: %s\n' "$0" "$*"
 }
 
 docker_run_sap_hana() {
@@ -37,10 +37,10 @@ docker_run_sap_hana() {
 get_env_vars() {
     case ${image%:*} in
 	(*/tableau-ibm-db2-*|tableau-ibm-db2-*)
-	    printf "%s\n" $ENV_VARS_TABLEAU
+	    printf '%s\n' $ENV_VARS_TABLEAU
 	    ;;
 	(*)
-	    printf "%s\n" $ENV_VARS_VENDOR
+	    printf '%s\n' $ENV_VARS_VENDOR
 	    ;;
     esac
 }
@@ -101,7 +101,7 @@ usage_error() {
 }
 
 if [ $# -lt 1 ]; then
-    usage_error "%s: Not enough arguments\n" "$0"
+    usage_error '%s: Not enough arguments\n' "$0"
 fi
 
 case "$0" in
diff --git a/docker-run-oracle-server b/docker-run-oracle-server
--- a/docker-run-oracle-server
+++ b/docker-run-oracle-server
@@ -25,7 +25,7 @@ abort() {
 }
 
 assert() {
-    "$@" || abort "%s: Assertion failed: %s\n" "$0" "$*"
+    "$@" || abort '%s: Assertion failed: %s\n' "$0" "$*"
 }
 
 docker_run_oracle_server() {
@@ -75,7 +75,7 @@ usage_error() {
 }
 
 if [ $# -lt 1 ]; then
-    usage_error "%s: Not enough arguments\n" "$0"
+    usage_error '%s: Not enough arguments\n' "$0"
 fi
 
 case "$0" in
diff --git a/docker-run-sap-hana-server b/docker-run-sap-hana-server
--- a/docker-run-sap-hana-server
+++ b/docker-run-sap-hana-server
@@ -24,7 +24,7 @@ abort() {
 }
 
 assert() {
-    "$@" || abort "%s: Assertion failed: %s\n" "$0" "$*"
+    "$@" || abort '%s: Assertion failed: %s\n' "$0" "$*"
 }
 
 docker_run_sap_hana() {
@@ -85,7 +85,7 @@ usage_error() {
 }
 
 if [ $# -lt 1 ]; then
-    usage_error "%s: Not enough arguments\n" "$0"
+    usage_error '%s: Not enough arguments\n' "$0"
 fi
 
 case "$0" in
diff --git a/edit-software-properties b/edit-software-properties
--- a/edit-software-properties
+++ b/edit-software-properties
@@ -22,27 +22,27 @@ abort() {
 }
 
 abort_desktop_not_supported() {
-    abort "%s: %s: Desktop not supported\n" "$0" "$desktop_name"
+    abort '%s: %s: Desktop not supported\n' "$0" "$desktop_name"
 }
 
 abort_not_supported() {
-    abort "%s: %s: %s not supported\n" "$0" "$PRETTY_NAME" "$*"
+    abort '%s: %s: %s not supported\n' "$0" "$PRETTY_NAME" "$*"
 }
 
 assert() {
-    "$@" || abort "%s: Assertion failed: %s\n" "$0" "$*"
+    "$@" || abort '%s: Assertion failed: %s\n' "$0" "$*"
 }
 
 
 edit_software_properties() {
     if [ -z "${DISPLAY:-}" ]; then
-	abort "%s: No DISPLAY variable set\n" "$0"
+	abort '%s: No DISPLAY variable set\n' "$0"
     fi
 
     desktop_name=$(get-desktop-name)
 
     if [ -z "${desktop_name:-}" ]; then
-	abort "%s: Desktop not specified\n" "$0"
+	abort '%s: Desktop not specified\n' "$0"
     fi
 
     case "$ID" in
diff --git a/enable-sudo b/enable-sudo
--- a/enable-sudo
+++ b/enable-sudo
@@ -24,11 +24,11 @@ abort() {
 }
 
 abort_not_supported() {
-    abort "%s: %s: %s not supported\n" "$0" "$PRETTY_NAME" "$*"
+    abort '%s: %s: %s not supported\n' "$0" "$PRETTY_NAME" "$*"
 }
 
 assert() {
-    "$@" || abort "%s: Assertion failed: %s\n" "$0" "$*"
+    "$@" || abort '%s: Assertion failed: %s\n' "$0" "$*"
 }
 
 eval $(get-os-release -x)
@@ -43,5 +43,5 @@ case "$ID" in
 esac
 
 if su -c "usermod -a -G sudo $USER"; then
-    printf "Please restart machine before using sudo\n"
+    printf 'Please restart machine before using sudo\n'
 fi
diff --git a/export-parameters b/export-parameters
--- a/export-parameters
+++ b/export-parameters
@@ -22,7 +22,7 @@ abort() {
 }
 
 assert() {
-    "$@" || abort "%s: Assertion failed: %s\n" "$script" "$*"
+    "$@" || abort '%s: Assertion failed: %s\n' "$script" "$*"
 }
 
 export_parameters() {
@@ -62,7 +62,7 @@ parse_parameter() {
     if is_valid_parameter "$1"; then
 	parameters=${parameters:+$parameters }"$1"
     else
-	usage_error "%s: %s: Invalid parameter name\n" "$script" "$1"
+	usage_error '%s: %s: Invalid parameter name\n' "$script" "$1"
     fi
 }
 
@@ -81,7 +81,7 @@ parse_shell() {
 	    shell=${1%.exe}
 	    ;;
 	(*)
-	    usage_error "%s: %s: Unsupported shell\n" "$script" "$1"
+	    usage_error '%s: %s: Unsupported shell\n' "$script" "$1"
 	    ;;
     esac
 }
diff --git a/generate-docker-compose b/generate-docker-compose
--- a/generate-docker-compose
+++ b/generate-docker-compose
@@ -65,7 +65,7 @@ abort() {
 }
 
 assert() {
-    "$@" || abort "%s: Assertion failed: %s\n" "$script" "$*"
+    "$@" || abort '%s: Assertion failed: %s\n' "$script" "$*"
 }
 
 check_device() {
@@ -279,7 +279,7 @@ parse_arguments() {
     shift $(($OPTIND - 1))
 
     if [ $# -gt 0 ]; then
-	usage_error "%s: Too many arguments\n" "$script"
+	usage_error '%s: Too many arguments\n' "$script"
     fi
 }
 
diff --git a/generate-env b/generate-env
--- a/generate-env
+++ b/generate-env
@@ -22,7 +22,7 @@ abort() {
 }
 
 assert() {
-    "$@" || abort "%s: Assertion failed: %s\n" "$0" "$*"
+    "$@" || abort '%s: Assertion failed: %s\n' "$0" "$*"
 }
 
 format_dialect() {
@@ -95,7 +95,7 @@ generate_password() {
 }
 
 get_default_dialect() {
-    printf "%s\n" sqlite
+    printf '%s\n' sqlite
 }
 
 get_default_host() {
@@ -103,15 +103,15 @@ get_default_host() {
 	(mysql)
 	    case ${protocol:=$(get_default_protocol)} in
 		(SOCKET)
-		    printf "%s\n" localhost
+		    printf '%s\n' localhost
 		    ;;
 		(TCP)
-		    printf "%s\n" 127.0.0.1
+		    printf '%s\n' 127.0.0.1
 		    ;;
 	    esac
 	    ;;
 	(postgresql)
-	    printf "%s\n" localhost
+	    printf '%s\n' localhost
 	    ;;
     esac
 }
@@ -119,10 +119,10 @@ get_default_host() {
 get_default_port() {
     case "${dialect:=$(get_default_dialect)}" in
 	(mysql)
-	    printf "%s\n" 3306
+	    printf '%s\n' 3306
 	    ;;
 	(postgresql)
-	    printf "%s\n" 5432
+	    printf '%s\n' 5432
 	    ;;
     esac
 }
@@ -130,7 +130,7 @@ get_default_port() {
 get_default_protocol() {
     case "${dialect:=$(get_default_dialect)}" in
 	(mysql)
-	    printf "%s\n" SOCKET
+	    printf '%s\n' SOCKET
 	    ;;
     esac
 }
@@ -138,13 +138,13 @@ get_default_protocol() {
 get_default_qualifier() {
     case "${dialect:=$(get_default_dialect)}" in
 	(mysql)
-	    printf "%s\n" mysql
+	    printf '%s\n' mysql
 	    ;;
 	(postgresql)
-	    printf "%s\n" postgres
+	    printf '%s\n' postgres
 	    ;;
 	(sqlite)
-	    printf "%s\n" database
+	    printf '%s\n' database
 	    ;;
     esac
 }
@@ -152,7 +152,7 @@ get_default_qualifier() {
 get_default_user() {
     case "${dialect:=$(get_default_dialect)}" in
 	(mysql|postgresql)
-	    printf "%s\n" "${SUDO_USER-${USER-$LOGIN}}"
+	    printf '%s\n' "${SUDO_USER-${USER-$LOGIN}}"
 	    ;;
     esac
 }
@@ -184,7 +184,7 @@ parse_arguments() {
 			dialect=sqlite
 			;;
 		    (*)
-			usage_error "%s: %s: Invalid argument\n" "$0" "$OPTARG"
+			usage_error '%s: %s: Invalid argument\n' "$0" "$OPTARG"
 			;;
 		esac
 		;;
@@ -206,7 +206,7 @@ parse_arguments() {
 			qualifier=postgres
 			;;
 		    (*)
-			usage_error "%s: %s: Invalid argument\n" "$0" "$OPTARG"
+			usage_error '%s: %s: Invalid argument\n' "$0" "$OPTARG"
 			;;
 		esac
 		;;
@@ -257,7 +257,7 @@ usage_error() {
 	printf "$@" >&2
     fi
 
-    printf "%s\n" '' >&2
+    printf '%s\n' '' >&2
     usage
     exit 2
 }
diff --git a/get-askpass-helper b/get-askpass-helper
--- a/get-askpass-helper
+++ b/get-askpass-helper
@@ -24,15 +24,15 @@ abort() {
 }
 
 abort_desktop_not_supported() {
-    abort "%s: %s: Desktop not supported\n" "$script" "$desktop_name"
+    abort '%s: %s: Desktop not supported\n' "$script" "$desktop_name"
 }
 
 abort_not_supported() {
-    abort "%s: %s: %s not supported\n" "$script" "$PRETTY_NAME" "$*"
+    abort '%s: %s: %s not supported\n' "$script" "$PRETTY_NAME" "$*"
 }
 
 assert() {
-    "$@" || abort "%s: Assertion failed: %s\n" "$script" "$*"
+    "$@" || abort '%s: Assertion failed: %s\n' "$script" "$*"
 }
 
 configure_platform() {
@@ -88,10 +88,10 @@ get_askpass_helper() {
 
     if [ -n "${helper-}" ]; then
 	if [ -n "${package:-}" ]; then
-	    printf "# %s package %s:\n" "$PRETTY_NAME" $package
+	    printf '# %s package %s:\n' "$PRETTY_NAME" $package
 	fi
 
-	printf "%s\n" "${helper%.exe}"
+	printf '%s\n' "${helper%.exe}"
     fi
 }
 
diff --git a/get-askpass-package b/get-askpass-package
--- a/get-askpass-package
+++ b/get-askpass-package
@@ -22,7 +22,7 @@ abort() {
 }
 
 assert() {
-    "$@" || abort "%s: Assertion failed: %s\n" "$script" "$*"
+    "$@" || abort '%s: Assertion failed: %s\n' "$script" "$*"
 }
 
 get_askpass_package() {
@@ -100,7 +100,7 @@ get_askpass_package() {
     done
 
     if [ -n "${package-}" ]; then
-	printf "%s\n" $package
+	printf '%s\n' $package
     fi
 }
 
diff --git a/get-crystal-runtime-packages b/get-crystal-runtime-packages
--- a/get-crystal-runtime-packages
+++ b/get-crystal-runtime-packages
@@ -33,7 +33,7 @@ abort() {
 }
 
 assert() {
-    "$@" || abort "%s: Assertion failed: %s\n" "$0" "$*"
+    "$@" || abort '%s: Assertion failed: %s\n' "$0" "$*"
 }
 
 get_crystal_library_packages() {
@@ -66,7 +66,7 @@ get_crystal_library_packages() {
     esac
 
     if [ -n "${packages-}" ]; then
-	printf "%s\n" $packages
+	printf '%s\n' $packages
     fi
 }
 
diff --git a/get-development-pattern b/get-development-pattern
--- a/get-development-pattern
+++ b/get-development-pattern
@@ -30,7 +30,7 @@ abort() {
 }
 
 assert() {
-    "$@" || abort "%s: Assertion failed: %s\n" "$0" "$*"
+    "$@" || abort '%s: Assertion failed: %s\n' "$0" "$*"
 }
 
 get_devel_pattern() {
@@ -56,7 +56,7 @@ get_devel_pattern() {
     done
 
     if [ -n "${pattern-}" ]; then
-	printf "%s\n" "$pattern"
+	printf '%s\n' "$pattern"
     fi
 }
 
diff --git a/get-docker-ce-packages b/get-docker-ce-packages
--- a/get-docker-ce-packages
+++ b/get-docker-ce-packages
@@ -29,7 +29,7 @@ abort() {
 }
 
 assert() {
-    "$@" || abort "%s: Assertion failed: %s\n" "$0" "$*"
+    "$@" || abort '%s: Assertion failed: %s\n' "$0" "$*"
 }
 
 get_docker_ce_packages() {
@@ -69,7 +69,7 @@ get_docker_ce_packages() {
     done
 
     if [ -n "${packages-}" ]; then
-	printf "%s\n" $packages
+	printf '%s\n' $packages
     fi
 }
 
diff --git a/get-docker-group b/get-docker-group
--- a/get-docker-group
+++ b/get-docker-group
@@ -24,7 +24,7 @@ abort() {
 }
 
 assert() {
-    "$@" || abort "%s: Assertion failed: %s\n" "$0" "$*"
+    "$@" || abort '%s: Assertion failed: %s\n' "$0" "$*"
 }
 
 get_docker_group() {
@@ -33,10 +33,10 @@ get_docker_group() {
     if [ -n "$origin" ]; then
 	case "$origin" in
 	    (docker.com)
-		printf "%s\n" "$DOCKER_GROUP"
+		printf '%s\n' "$DOCKER_GROUP"
 		;;
 	    (native)
-		printf "%s\n" "$DOCKER_GROUP"
+		printf '%s\n' "$DOCKER_GROUP"
 		;;
 	    (podman)
 		:
@@ -60,7 +60,7 @@ get_docker_origin() {
 	esac
 
 	if [ -n "${origin-}" ]; then
-	    printf "%s\n" "$origin"
+	    printf '%s\n' "$origin"
 	    return
 	fi
     done
diff --git a/get-docker-packages b/get-docker-packages
--- a/get-docker-packages
+++ b/get-docker-packages
@@ -41,7 +41,7 @@ abort() {
 }
 
 assert() {
-    "$@" || abort "%s: Assertion failed: %s\n" "$0" "$*"
+    "$@" || abort '%s: Assertion failed: %s\n' "$0" "$*"
 }
 
 get_docker_packages() {
@@ -93,7 +93,7 @@ get_docker_packages() {
     done
 
     if [ -n "${packages-}" ]; then
-	printf "%s\n" $packages
+	printf '%s\n' $packages
     fi
 }
 
diff --git a/get-gcc-build-packages b/get-gcc-build-packages
--- a/get-gcc-build-packages
+++ b/get-gcc-build-packages
@@ -29,7 +29,7 @@ abort() {
 }
 
 assert() {
-    "$@" || abort "%s: Assertion failed: %s\n" "$0" "$*"
+    "$@" || abort '%s: Assertion failed: %s\n' "$0" "$*"
 }
 
 get_gcc_build_packages() {
@@ -62,7 +62,7 @@ get_gcc_build_packages() {
     esac
 
     if [ -n "${packages-}" ]; then
-	printf "%s\n" $packages
+	printf '%s\n' $packages
     fi
 }
 
diff --git a/get-install-command b/get-install-command
--- a/get-install-command
+++ b/get-install-command
@@ -22,7 +22,7 @@ abort() {
 }
 
 assert() {
-    "$@" || abort "%s: Assertion failed: %s\n" "$0" "$*"
+    "$@" || abort '%s: Assertion failed: %s\n' "$0" "$*"
 }
 
 get_install_command() {
@@ -42,7 +42,7 @@ get_install_command() {
     esac
 
     if [ "${install-}" ]; then
-	printf "%s\n" "$install"
+	printf '%s\n' "$install"
     fi
 }
 
@@ -52,9 +52,9 @@ usage_error() {
 }
 
 if [ $# -lt 1 ]; then
-    usage_error "%s: Not enough arguments\n" "$0"
+    usage_error '%s: Not enough arguments\n' "$0"
 elif [ $# -gt 1 ]; then
-    usage_error "%s: Too many arguments\n" "$0"
+    usage_error '%s: Too many arguments\n' "$0"
 fi
 
 get_install_command "$@"
diff --git a/get-installed-mysql-package b/get-installed-mysql-package
--- a/get-installed-mysql-package
+++ b/get-installed-mysql-package
@@ -22,7 +22,7 @@ abort() {
 }
 
 assert() {
-    "$@" || abort "%s: Assertion failed: %s\n" "$0" "$*"
+    "$@" || abort '%s: Assertion failed: %s\n' "$0" "$*"
 }
 
 get_installed_mysql_package() {
@@ -45,7 +45,7 @@ parse_arguments() {
 	    true
 	    ;;
 	(*)
-	    abort "%s: Invalid argument -- %s\n" "$0" "$1"
+	    abort '%s: Invalid argument -- %s\n' "$0" "$1"
 	    ;;
     esac
 }
@@ -56,9 +56,9 @@ usage_error() {
 }
 
 if [ $# -lt 1 ]; then
-    usage_error "%s: Not enough arguments\n" "$0"
+    usage_error '%s: Not enough arguments\n' "$0"
 elif [ $# -gt 1 ]; then
-    usage_error "%s: Too many arguments\n" "$0"
+    usage_error '%s: Too many arguments\n' "$0"
 fi
 
 case "$0" in
diff --git a/get-kubernetes-dependencies b/get-kubernetes-dependencies
--- a/get-kubernetes-dependencies
+++ b/get-kubernetes-dependencies
@@ -36,7 +36,7 @@ abort() {
 }
 
 assert() {
-    "$@" || abort "%s: Assertion failed: %s\n" "$0" "$*"
+    "$@" || abort '%s: Assertion failed: %s\n' "$0" "$*"
 }
 
 get_kubernetes_dependencies() {
@@ -86,7 +86,7 @@ get_kubernetes_dependencies() {
     done
 
     if [ -n "${packages-}" ]; then
-	printf "%s\n" ${packages-}
+	printf '%s\n' ${packages-}
     fi
 }
 
diff --git a/get-kubernetes-packages b/get-kubernetes-packages
--- a/get-kubernetes-packages
+++ b/get-kubernetes-packages
@@ -26,7 +26,7 @@ abort() {
 }
 
 assert() {
-    "$@" || abort "%s: Assertion failed: %s\n" "$0" "$*"
+    "$@" || abort '%s: Assertion failed: %s\n' "$0" "$*"
 }
 
 get_docker_ce_packages() {
@@ -52,7 +52,7 @@ get_docker_ce_packages() {
     done
 
     if [ -n "${packages-}" ]; then
-	printf "%s\n" $packages
+	printf '%s\n' $packages
     fi
 }
 
diff --git a/get-lilith-os-packages b/get-lilith-os-packages
--- a/get-lilith-os-packages
+++ b/get-lilith-os-packages
@@ -28,7 +28,7 @@ abort() {
 }
 
 assert() {
-    "$@" || abort "%s: Assertion failed: %s\n" "$0" "$*"
+    "$@" || abort '%s: Assertion failed: %s\n' "$0" "$*"
 }
 
 get_lilith_os_packages() {
@@ -55,7 +55,7 @@ get_lilith_os_packages() {
     esac
 
     if [ -n "${packages-}" ]; then
-	printf "%s\n" $packages
+	printf '%s\n' $packages
     fi
 }
 
diff --git a/get-mysql-packages b/get-mysql-packages
--- a/get-mysql-packages
+++ b/get-mysql-packages
@@ -22,7 +22,7 @@ abort() {
 }
 
 assert() {
-    "$@" || abort "%s: Assertion failed: %s\n" "$0" "$*"
+    "$@" || abort '%s: Assertion failed: %s\n' "$0" "$*"
 }
 
 get_mysql_packages() {
@@ -47,7 +47,7 @@ parse_arguments() {
 		categories="${categories+$categories mysql-server}"
 		;;
 	    (*)
-		abort "%s: %s -- invalid argument\n" "$0" "$arg"
+		abort '%s: %s -- invalid argument\n' "$0" "$arg"
 	esac
     done
 
diff --git a/get-nameserver-from-resolver b/get-nameserver-from-resolver
--- a/get-nameserver-from-resolver
+++ b/get-nameserver-from-resolver
@@ -24,7 +24,7 @@ abort() {
 }
 
 assert() {
-    "$@" || abort "%s: Assertion failed: %s\n" "$0" "$*"
+    "$@" || abort '%s: Assertion failed: %s\n' "$0" "$*"
 }
 
 get_nameserver() {
@@ -57,7 +57,7 @@ parse_arguments() {
     shift $(($OPTIND - 1))
 
     if [ $# -gt 0 ]; then
-	usage_error "%s: Too many arguments\n" "$script"
+	usage_error '%s: Too many arguments\n' "$script"
     fi
 }
 
diff --git a/get-nodejs-packages b/get-nodejs-packages
--- a/get-nodejs-packages
+++ b/get-nodejs-packages
@@ -38,7 +38,7 @@ abort() {
 }
 
 assert() {
-    "$@" || abort "%s: Assertion failed: %s\n" "$0" "$*"
+    "$@" || abort '%s: Assertion failed: %s\n' "$0" "$*"
 }
 
 get_nodejs_packages() {
@@ -76,7 +76,7 @@ get_nodejs_packages() {
     done
 
     if [ -n "${packages-}" ]; then
-	printf "%s\n" $packages
+	printf '%s\n' $packages
     fi
 }
 
diff --git a/get-nushell-build-packages b/get-nushell-build-packages
--- a/get-nushell-build-packages
+++ b/get-nushell-build-packages
@@ -26,7 +26,7 @@ abort() {
 }
 
 assert() {
-    "$@" || abort "%s: Assertion failed: %s\n" "$0" "$*"
+    "$@" || abort '%s: Assertion failed: %s\n' "$0" "$*"
 }
 
 get_nushell_build_packages() {
@@ -56,7 +56,7 @@ get_nushell_build_packages() {
     done
 
     if [ -n "${packages-}" ]; then
-	printf "%s\n" $packages
+	printf '%s\n' $packages
     fi
 }
 
diff --git a/get-oracle-client-packages b/get-oracle-client-packages
--- a/get-oracle-client-packages
+++ b/get-oracle-client-packages
@@ -30,7 +30,7 @@ abort() {
 }
 
 assert() {
-    "$@" || abort "%s: Assertion failed: %s\n" "$0" "$*"
+    "$@" || abort '%s: Assertion failed: %s\n' "$0" "$*"
 }
 
 get_oracle_client_packages() {
@@ -80,7 +80,7 @@ get_oracle_client_packages() {
     esac
 
     if [ -n "${packages-}" ]; then
-	printf "%s\n" $packages
+	printf '%s\n' $packages
     fi
 }
 
diff --git a/get-os-configuration b/get-os-configuration
--- a/get-os-configuration
+++ b/get-os-configuration
@@ -22,11 +22,11 @@ abort() {
 }
 
 abort_not_supported() {
-    abort "%s: %s: %s not supported\n" "$0" "$PRETTY_NAME" "$*"
+    abort '%s: %s: %s not supported\n' "$0" "$PRETTY_NAME" "$*"
 }
 
 assert() {
-    "$@" || abort "%s: Assertion failed: %s\n" "$0" "$*"
+    "$@" || abort '%s: Assertion failed: %s\n' "$0" "$*"
 }
 
 get_configuration_basename() {
@@ -83,7 +83,7 @@ get_configuration_basename() {
     done
 
     if [ -n "${basename-}" ]; then
-	printf "%s\n" "$basename.ini"
+	printf '%s\n' "$basename.ini"
     fi
 }
 
@@ -139,7 +139,7 @@ usage_error() {
 	printf "$@" >&2
     fi
 
-    printf "%s\n" '' >&2
+    printf '%s\n' '' >&2
     usage
     exit 2
 }
diff --git a/get-os-release b/get-os-release
--- a/get-os-release
+++ b/get-os-release
@@ -32,11 +32,11 @@ abort() {
 }
 
 assert() {
-    "$@" || abort "%s: Assertion failed: %s\n" "$0" "$*"
+    "$@" || abort '%s: Assertion failed: %s\n' "$0" "$*"
 }
 
 abort_conflicting_option() {
-    usage_error "%s: conflicting option -- %s\n" "$0" "$1"
+    usage_error '%s: conflicting option -- %s\n' "$0" "$1"
 }
 
 collect_data() {
@@ -112,7 +112,7 @@ collect_data_for_sunos() {
 }
 
 collect_data_for_unix() {
-    ID=$(printf "%s\n" "$system_name" | to_lower)
+    ID=$(printf '%s\n' "$system_name" | to_lower)
     NAME=$system_name
     VERSION=$system_release
     PRETTY_NAME=$system_data
@@ -122,9 +122,9 @@ collect_data_for_unix() {
 collect_data_for_windows() {
     ID=windows
     NAME="Microsoft Windows"
-    VERSION=$(printf "%s\n" "$system_name" | cut -d- -f2)
-    kernel_name=$(printf "%s\n" "$system_name" | cut -d- -f1)
-    kernel_release=$(printf "%s\n" "$system_release" | cut -d- -f1)
+    VERSION=$(printf '%s\n' "$system_name" | cut -d- -f2)
+    kernel_name=$(printf '%s\n' "$system_name" | cut -d- -f1)
+    kernel_release=$(printf '%s\n' "$system_release" | cut -d- -f1)
     os_family=ms-windows
 }
 
@@ -166,7 +166,7 @@ get_os_version_id() {
 		    cat $FILE_DEBIAN_VERSION
 		    ;;
 		(ubuntu)
-		    printf "%s\n" "$VERSION" | awk '{print $1}'
+		    printf '%s\n' "$VERSION" | awk '{print $1}'
 		    ;;
 		(rhel|ol|centos|fedora)
 		    "${script_prefix}get-redhat-version" $FILE_REDHAT_RELEASE
@@ -184,12 +184,12 @@ output_data() {
     if [ "$is_shell_format" = true ]; then
 	for var in $vars; do
 	    eval value="\${$var-}"
-	    printf "%s=\"%s\"\n" "$var" "$value"
+	    printf '%s="%s"\n' "$var" "$value"
 	done
     else
 	for var in $vars; do
 	    eval value="\${$var-}"
-	    printf "%s\n" "$value"
+	    printf '%s\n' "$value"
 	done
     fi
 }
@@ -239,7 +239,7 @@ parse_arguments() {
     shift $(($OPTIND - 1))
 
     if [ $# -gt 0 ]; then
-	usage_error "%s: Too many arguments\n" "$0"
+	usage_error '%s: Too many arguments\n' "$0"
     fi
 }
 
@@ -278,7 +278,7 @@ usage_error() {
 	printf "$@" >&2
     fi
 
-    printf "%s\n" '' >&2
+    printf '%s\n' '' >&2
     usage
     exit 2
 }
diff --git a/get-package-filenames b/get-package-filenames
--- a/get-package-filenames
+++ b/get-package-filenames
@@ -22,11 +22,11 @@ abort() {
 }
 
 abort_not_supported() {
-    abort "%s: %s: %s not supported\n" "$0" "$PRETTY_NAME" "$*"
+    abort '%s: %s: %s not supported\n' "$0" "$PRETTY_NAME" "$*"
 }
 
 assert() {
-    "$@" || abort "%s: Assertion failed: %s\n" "$0" "$*"
+    "$@" || abort '%s: Assertion failed: %s\n' "$0" "$*"
 }
 
 get_package_filenames() {
@@ -60,9 +60,9 @@ usage_error() {
 }
 
 if [ $# -lt 1 ]; then
-    usage_error "%s: Not enough arguments\n" "$0"
+    usage_error '%s: Not enough arguments\n' "$0"
 elif [ $# -gt 1 ]; then
-    usage_error "%s: Too many arguments\n" "$0"
+    usage_error '%s: Too many arguments\n' "$0"
 fi
 
 case "$0" in
diff --git a/get-package-managers b/get-package-managers
--- a/get-package-managers
+++ b/get-package-managers
@@ -22,7 +22,7 @@ abort() {
 }
 
 assert() {
-    "$@" || abort "%s: Assertion failed: %s\n" "$0" "$*"
+    "$@" || abort '%s: Assertion failed: %s\n' "$0" "$*"
 }
 
 get_package_managers() {
@@ -103,7 +103,7 @@ get_package_managers() {
     done
 
     if [ -n "${managers-}" ]; then
-	printf "%s\n" $managers
+	printf '%s\n' $managers
     fi
 }
 
diff --git a/get-packages b/get-packages
--- a/get-packages
+++ b/get-packages
@@ -22,11 +22,11 @@ abort() {
 }
 
 abort_not_supported() {
-    abort "%s: %s: %s not supported\n" "$script" "$PRETTY_NAME" "$*"
+    abort '%s: %s: %s not supported\n' "$script" "$PRETTY_NAME" "$*"
 }
 
 assert() {
-    "$@" || abort "%s: Assertion failed: %s\n" "$script" "$*"
+    "$@" || abort '%s: Assertion failed: %s\n' "$script" "$*"
 }
 
 get_os_configuration() {
@@ -51,7 +51,7 @@ get_packages() {
 }
 
 get_parameter() {
-    printf "%s-%s\n" "$1" "$2" | tr '[:lower:]' '[:upper:]' | tr '-' '_'
+    printf '%s-%s\n' "$1" "$2" | tr '[:lower:]' '[:upper:]' | tr '-' '_'
 }
 
 is_valid_category() {
@@ -89,7 +89,7 @@ parse_arguments() {
     shift $(($OPTIND - 1))
 
     if [ $# -lt 1 ]; then
-	usage_error "%s: Not enough arguments\n" "$script"
+	usage_error '%s: Not enough arguments\n' "$script"
     fi
 
     for category; do
diff --git a/get-postgresql-packages b/get-postgresql-packages
--- a/get-postgresql-packages
+++ b/get-postgresql-packages
@@ -25,7 +25,7 @@ abort() {
 }
 
 assert() {
-    "$@" || abort "%s: Assertion failed: %s\n" "$0" "$*"
+    "$@" || abort '%s: Assertion failed: %s\n' "$0" "$*"
 }
 
 get_postgresql_packages() {
@@ -59,7 +59,7 @@ parse_arguments() {
 		categories="${categories+$categories postgresql-server}"
 		;;
 	    (*)
-		abort "%s: %s -- invalid argument\n" "$0" "$arg"
+		abort '%s: %s -- invalid argument\n' "$0" "$arg"
 	esac
     done
 
diff --git a/get-python3-packages b/get-python3-packages
--- a/get-python3-packages
+++ b/get-python3-packages
@@ -47,7 +47,7 @@ abort() {
 }
 
 assert() {
-    "$@" || abort "%s: Assertion failed: %s\n" "$0" "$*"
+    "$@" || abort '%s: Assertion failed: %s\n' "$0" "$*"
 }
 
 get_python3_packages() {
@@ -109,7 +109,7 @@ get_python3_packages() {
     esac
 
     if [ -n "${packages-}" ]; then
-	printf "%s\n" $packages
+	printf '%s\n' $packages
     fi
 }
 
diff --git a/get-uninstall-command b/get-uninstall-command
--- a/get-uninstall-command
+++ b/get-uninstall-command
@@ -22,7 +22,7 @@ abort() {
 }
 
 assert() {
-    "$@" || abort "%s: Assertion failed: %s\n" "$0" "$*"
+    "$@" || abort '%s: Assertion failed: %s\n' "$0" "$*"
 }
 
 get_uninstall_command() {
@@ -45,7 +45,7 @@ get_uninstall_command() {
     esac
 
     if [ "${uninstall-}" ]; then
-	printf "%s\n" "$uninstall"
+	printf '%s\n' "$uninstall"
     fi
 }
 
@@ -55,9 +55,9 @@ usage_error() {
 }
 
 if [ $# -lt 1 ]; then
-    usage_error "%s: Not enough arguments\n" "$0"
+    usage_error '%s: Not enough arguments\n' "$0"
 elif [ $# -gt 1 ]; then
-    usage_error "%s: Too many arguments\n" "$0"
+    usage_error '%s: Too many arguments\n' "$0"
 fi
 
 get_uninstall_command "$@"
diff --git a/get-uninstalled-packages b/get-uninstalled-packages
--- a/get-uninstalled-packages
+++ b/get-uninstalled-packages
@@ -22,7 +22,7 @@ abort() {
 }
 
 assert() {
-    "$@" || abort "%s: Assertion failed: %s\n" "$0" "$*"
+    "$@" || abort '%s: Assertion failed: %s\n' "$0" "$*"
 }
 
 get_uninstalled_packages() {
@@ -32,7 +32,7 @@ get_uninstalled_packages() {
 
     for package; do
 	if ! grep_package $gnu_grep $package $tmpfile; then
-	   printf "%s\n" "$package"
+	   printf '%s\n' "$package"
 	fi
     done
 }
@@ -42,7 +42,7 @@ grep_package() {
     assert [ -n "$1" ]
     assert [ -n "$2" ]
     assert [ -n "$3" ]
-    quoted_package=$(printf "%s\n" "$2" | sed -e 's/\+/\\\+/g')
+    quoted_package=$(printf '%s\n' "$2" | sed -e 's/\+/\\\+/g')
     "$1" -Eq '^'"$quoted_package"'([0-9]*|-[0-9\.]+)?(nb[0-9]+)?$' "$3"
 }
 
diff --git a/git-credential-helper b/git-credential-helper
--- a/git-credential-helper
+++ b/git-credential-helper
@@ -29,11 +29,11 @@ abort() {
 }
 
 abort_not_supported() {
-    abort "%s: %s: %s not supported\n" "$0" "$PRETTY_NAME" "$*"
+    abort '%s: %s: %s not supported\n' "$0" "$PRETTY_NAME" "$*"
 }
 
 assert() {
-    "$@" || abort "%s: Assertion failed: %s\n" "$0" "$*"
+    "$@" || abort '%s: Assertion failed: %s\n' "$0" "$*"
 }
 
 get_helper_binary() {
@@ -137,10 +137,10 @@ set_helper() {
 	if [ "$1" = cache -o -x "$1" ]; then
 	    run_unpriv /bin/sh -c "git config --global credential.helper $1"
 	else
-	    abort "%s: No such executable file\n" "$1"
+	    abort '%s: No such executable file\n' "$1"
 	fi
     else
-	abort "No executable file\n"
+	abort 'No executable file\n'
     fi
 }
 
@@ -165,21 +165,21 @@ parse_arguments() {
     shift $(($OPTIND - 1))
 
     if [ $# -gt 1 ]; then
-	usage_error "%s: Too many arguments\n" "$0"
+	usage_error '%s: Too many arguments\n' "$0"
     elif [ $# -gt 0 ]; then
 	credential_helper=$1
     fi
 }
 
 query_available_helpers() {
-    printf "# %s package %s:\n" "$PRETTY_NAME" $package
+    printf '# %s package %s:\n' "$PRETTY_NAME" "$package"
 
     case "$kernel_name" in
 	(Linux|GNU)
 	    get-package-filenames $package | get_helper_binary
 	    ;;
 	(CYGWIN_NT-*)
-	    printf "%s\n" /usr/libexec/git-core/git-credential-manager
+	    printf '%s\n' /usr/libexec/git-core/git-credential-manager
 	    ;;
     esac
 }
@@ -202,7 +202,7 @@ usage_error() {
 	printf "$@" >&2
     fi
 
-    printf "%s\n" '' >&2
+    printf '%s\n' '' >&2
     usage
     exit 2
 }
diff --git a/install-docker b/install-docker
--- a/install-docker
+++ b/install-docker
@@ -22,11 +22,11 @@ abort() {
 }
 
 abort_not_supported() {
-    abort "%s: %s: %s not supported\n" "$script" "$PRETTY_NAME" "$*"
+    abort '%s: %s: %s not supported\n' "$script" "$PRETTY_NAME" "$*"
 }
 
 assert() {
-    "$@" || abort "%s: Assertion failed: %s\n" "$script" "$*"
+    "$@" || abort '%s: Assertion failed: %s\n' "$script" "$*"
 }
 
 configure_daemon_group() {
@@ -75,13 +75,13 @@ get_architecture() {
 
     case "$machine" in
 	(i86pc|x86_64)
-	    printf "%s\n" amd64
+	    printf '%s\n' amd64
 	    ;;
 	(armv7l)
-	    printf "%s\n" armhf
+	    printf '%s\n' armhf
 	    ;;
 	(*)
-	    printf "%s\n" $machine
+	    printf '%s\n' $machine
 	    ;;
     esac
 }
@@ -90,8 +90,8 @@ get_difference() (
     assert [ $# -eq 2 ]
 
     for item in $1; do
-	if ! printf "%s\n" $2 | grep -q '^'"$item"'$'; then
-	    printf "%s\n" "$item"
+	if ! printf '%s\n' $2 | grep -q '^'"$item"'$'; then
+	    printf '%s\n' "$item"
 	fi
     done
 )
@@ -113,7 +113,7 @@ get_docker_origin() {
 	esac
 
 	if [ -n "${origin-}" ]; then
-	    printf "%s\n" "$origin"
+	    printf '%s\n' "$origin"
 	    break
 	fi
     done
@@ -128,17 +128,17 @@ install_docker() {
     if [ -n "$origin" ]; then
 	case "$origin" in
 	    (docker.com)
-		printf "Docker Community Edition is installed.\n"
+		printf 'Docker Community Edition is installed.\n'
 		;;
 	    (native)
-		printf "Native Docker is installed.\n"
+		printf 'Native Docker is installed.\n'
 		;;
 	    (podman)
-		printf "Podman is installed.\n"
+		printf 'Podman is installed.\n'
 		;;
 	esac
     else
-	printf "Docker is not installed.\n"
+	printf 'Docker is not installed.\n'
     fi
 
     selected_packages=$(get-packages docker)
@@ -176,7 +176,7 @@ modify_user() (
 
     members="$(getent group $1 | awk -F: '{print $4}')"
 
-    if ! printf "%s\n" "$members" | grep -q "\<$SUDO_USER\>"; then
+    if ! printf '%s\n' "$members" | grep -q "\<$SUDO_USER\>"; then
 	usermod -a -G $1 $SUDO_USER
     fi
 )
@@ -194,7 +194,7 @@ validate_platform() {
 	    true
 	    ;;
 	(*)
-	    abort "%s: %s: Architecture not supported\n" "$script" "$arch"
+	    abort '%s: %s: Architecture not supported\n' "$script" "$arch"
 	    ;;
     esac
 
@@ -319,7 +319,7 @@ validate_platform() {
 }
 
 if [ $# -gt 0 ]; then
-    usage_error "%s: Too many arguments\n" "$script"
+    usage_error '%s: Too many arguments\n' "$script"
 fi
 
 script=$(basename "$0")
diff --git a/install-docker-ce b/install-docker-ce
--- a/install-docker-ce
+++ b/install-docker-ce
@@ -25,7 +25,7 @@ abort() {
 }
 
 abort_not_supported() {
-    abort "%s: %s: %s not supported\n" "$script" "$PRETTY_NAME" "$*"
+    abort '%s: %s: %s not supported\n' "$script" "$PRETTY_NAME" "$*"
 }
 
 add_gpg_key() {
@@ -68,7 +68,7 @@ add_repositories() {
 }
 
 assert() {
-    "$@" || abort "%s: Assertion failed: %s\n" "$script" "$*"
+    "$@" || abort '%s: Assertion failed: %s\n' "$script" "$*"
 }
 
 configure_daemon_group() {
@@ -109,13 +109,13 @@ get_architecture() {
 
     case "$machine" in
 	(i86pc|x86_64)
-	    printf "%s\n" amd64
+	    printf '%s\n' amd64
 	    ;;
 	(armv7l)
-	    printf "%s\n" armhf
+	    printf '%s\n' armhf
 	    ;;
 	(*)
-	    printf "%s\n" $machine
+	    printf '%s\n' $machine
 	    ;;
     esac
 }
@@ -128,8 +128,8 @@ get_difference() (
     assert [ $# -eq 2 ]
 
     for item in $1; do
-	if ! printf "%s\n" $2 | grep -q '^'"$item"'$'; then
-	    printf "%s\n" "$item"
+	if ! printf '%s\n' $2 | grep -q '^'"$item"'$'; then
+	    printf '%s\n' "$item"
 	fi
     done
 )
@@ -151,7 +151,7 @@ get_docker_origin() {
 	esac
 
 	if [ -n "${origin-}" ]; then
-	    printf "%s\n" "$origin"
+	    printf '%s\n' "$origin"
 	    break
 	fi
     done
@@ -177,20 +177,20 @@ get_docker_repo() {
 	esac
 
 	if [ -n "${repo-}" ]; then
-	    printf "%s\n" "$repo"
+	    printf '%s\n' "$repo"
 	    break
 	fi
     done
 }
 
 get_docker_url() {
-    printf "%s\n" "$DOCKER_BASE_URL/linux/$1"
+    printf '%s\n' "$DOCKER_BASE_URL/linux/$1"
 }
 
 get_package_manager_basename() {
     manager_pathname=$(get-package-managers | awk 'NR == 1 {print $0}')
     manager_basename=$(basename $manager_pathname)
-    printf "%s\n" $manager_basename
+    printf '%s\n' $manager_basename
 }
 
 get_repository_data() {
@@ -217,17 +217,17 @@ install_docker_ce() {
     if [ -n "$origin" ]; then
 	case "$origin" in
 	    (docker.com)
-		printf "Docker Community Edition is installed.\n"
+		printf 'Docker Community Edition is installed.\n'
 		;;
 	    (native)
-		printf "Native Docker is installed.\n"
+		printf 'Native Docker is installed.\n'
 		;;
 	    (podman)
-		printf "Podman is installed.\n"
+		printf 'Podman is installed.\n'
 		;;
 	esac
     else
-	printf "Docker is not installed.\n"
+	printf 'Docker is not installed.\n'
     fi
 
     selected_packages=$(get-packages docker-ce)
@@ -268,7 +268,7 @@ modify_user() (
 
     members="$(getent group $1 | awk -F: '{print $4}')"
 
-    if ! printf "%s\n" "$members" | grep -q "\<$SUDO_USER\>"; then
+    if ! printf '%s\n' "$members" | grep -q "\<$SUDO_USER\>"; then
 	usermod -aG $1 $SUDO_USER
     fi
 )
@@ -338,7 +338,7 @@ validate_platform() {
 	    true
 	    ;;
 	(*)
-	    abort "%s: %s: Architecture not supported" "$script" "$arch"
+	    abort '%s: %s: Architecture not supported' "$script" "$arch"
 	    ;;
     esac
 
@@ -389,7 +389,7 @@ validate_platform() {
 }
 
 if [ $# -gt 0 ]; then
-    usage_error "%s: Too many arguments\n" "$script"
+    usage_error '%s: Too many arguments\n' "$script"
 fi
 
 script=$(basename "$0")
diff --git a/install-docker-compose b/install-docker-compose
--- a/install-docker-compose
+++ b/install-docker-compose
@@ -27,7 +27,7 @@ abort() {
 }
 
 assert() {
-    "$@" || abort "%s: Assertion failed: %s\n" "$script" "$*"
+    "$@" || abort '%s: Assertion failed: %s\n' "$script" "$*"
 }
 
 clean_up() {
@@ -221,9 +221,9 @@ get_prefix() {
 get_realpath() (
     for file; do
 	if expr "$file" : '/.*' >/dev/null; then
-	    printf "%s\n" "$file"
+	    printf '%s\n' "$file"
 	else
-	    printf "%s\n" "$PWD/${file#./}"
+	    printf '%s\n' "$PWD/${file#./}"
 	fi
     done
 )
@@ -376,7 +376,7 @@ parse_arguments() {
     shift $(($OPTIND - 1))
 
     if [ $# -gt 0 ]; then
-	usage_error "%s: Too many arguments\n" "$script"
+	usage_error '%s: Too many arguments\n' "$script"
     fi
 }
 
@@ -389,14 +389,14 @@ parse_prefix() {
 	    prefix=$1
 	    ;;
 	(*)
-	    usage_error "%s: %s: Invalid prefix\n" "$script" "$1"
+	    usage_error '%s: %s: Invalid prefix\n' "$script" "$1"
 	    ;;
     esac
 
     if [ ! -d "$prefix/bin" ]; then
-	usage_error "%s: %s: Invalid prefix\n" "$script" "$1"
+	usage_error '%s: %s: Invalid prefix\n' "$script" "$1"
     elif [ ! -w "$prefix/bin" ]; then
-	usage_error "%s: %s: Invalid prefix\n" "$script" "$1"
+	usage_error '%s: %s: Invalid prefix\n' "$script" "$1"
     fi
 }
 
@@ -407,7 +407,7 @@ parse_version() {
     if is_valid_version "$1"; then
 	version=$1
     else
-	usage_error "%s: %s: Invalid version\n" "$script" "$1"
+	usage_error '%s: %s: Invalid version\n' "$script" "$1"
     fi
 }
 
diff --git a/install-docker-compose-command-completion b/install-docker-compose-command-completion
--- a/install-docker-compose-command-completion
+++ b/install-docker-compose-command-completion
@@ -27,7 +27,7 @@ abort() {
 }
 
 assert() {
-    "$@" || abort "%s: Assertion failed: %s\n" "$script" "$*"
+    "$@" || abort '%s: Assertion failed: %s\n' "$script" "$*"
 }
 
 clean_up() {
@@ -164,7 +164,7 @@ install_command_completion() {
     target_dir="${output_dir:-$(dirname "$target_file")}"
 
     if [ ! -d "$target_dir" ]; then
-	abort "%s: %s: No such directory\n" "$script" "$target_dir"
+	abort '%s: %s: No such directory\n' "$script" "$target_dir"
     fi
 
     target_status=unchanged
@@ -260,7 +260,7 @@ parse_arguments() {
     shift $(($OPTIND - 1))
 
     if [ $# -gt 0 ]; then
-	usage_error "%s: Too many arguments\n" "$script"
+	usage_error '%s: Too many arguments\n' "$script"
     fi
 }
 
@@ -272,7 +272,7 @@ parse_output() {
     if [ -d "$output_dir" -a -x "$output_dir" ]; then
 	output="$1"
     else
-	usage_error "%s: %s: Invalid output\n" "$script" "$1"
+	usage_error '%s: %s: Invalid output\n' "$script" "$1"
     fi
 }
 
@@ -283,7 +283,7 @@ parse_prefix() {
     if [ -x "$prefix/bin/$FILENAME" ]; then
 	prefix="$1"
     else
-	usage_error "%s: %s: Invalid prefix\n" "$script" "$1"
+	usage_error '%s: %s: Invalid prefix\n' "$script" "$1"
     fi
 }
 
diff --git a/install-epel b/install-epel
--- a/install-epel
+++ b/install-epel
@@ -24,11 +24,11 @@ abort() {
 }
 
 abort_not_supported() {
-    abort "%s: %s: %s not supported\n" "$0" "$PRETTY_NAME" "$*"
+    abort '%s: %s: %s not supported\n' "$0" "$PRETTY_NAME" "$*"
 }
 
 assert() {
-    "$@" || abort "%s: Assertion failed: %s\n" "$0" "$*"
+    "$@" || abort '%s: Assertion failed: %s\n' "$0" "$*"
 }
 
 configure_platform() {
@@ -47,7 +47,7 @@ configure_platform() {
 }
 
 get_url() {
-    printf "%s\n" "$EPEL_BASE_URL/epel-release-latest-$version.noarch.rpm"
+    printf '%s\n' "$EPEL_BASE_URL/epel-release-latest-$version.noarch.rpm"
 }
 
 install_epel() {
@@ -109,7 +109,7 @@ validate_platform() {
 }
 
 if [ $# -gt 0 ]; then
-    usage_error "%s: Too many arguments\n" "$0"
+    usage_error '%s: Too many arguments\n' "$0"
 fi
 
 case "$0" in
diff --git a/install-files b/install-files
--- a/install-files
+++ b/install-files
@@ -22,7 +22,7 @@ abort() {
 }
 
 assert() {
-    "$@" || abort "%s: Assertion failed: %s\n" "$0" "$*"
+    "$@" || abort '%s: Assertion failed: %s\n' "$0" "$*"
 }
 
 get_install_command() {
@@ -71,24 +71,24 @@ install_files() {
     shift $(($OPTIND - 1))
 
     if [ $# -lt 1 ]; then
-	usage_error "%s: Not enough arguments\n" "$0"
+	usage_error '%s: Not enough arguments\n' "$0"
     elif [ -n "$mode" -a "$method" != install ]; then
-	usage_error "%s: %s: Invalid option for method %s\n" "$0" "$mode" "$method"
+	usage_error '%s: %s: Invalid option for method %s\n' "$0" "$mode" "$method"
     fi
 
     target_dir="$1"
     shift
 
     if [ $# -lt 1 ]; then
-	usage_error "%s: Not enough arguments\n" "$0"
+	usage_error '%s: Not enough arguments\n' "$0"
     fi
 
     if [ -d "$target_dir" ]; then
 	true
     elif [ -e "$target_dir" ]; then
-	abort "%s: %s: Not a directory\n" "$0" "$target_dir"
+	abort '%s: %s: Not a directory\n' "$0" "$target_dir"
     elif ! mkdir -p "$target_dir"; then
-	abort "%s: %s: Cannot create directory\n" "$0" "$target_dir"
+	abort '%s: %s: Cannot create directory\n' "$0" "$target_dir"
     fi
 
     case "$method" in
@@ -134,7 +134,7 @@ usage_error() {
 	printf "$@" >&2
     fi
 
-    printf "%s\n" '' >&2
+    printf '%s\n' '' >&2
     usage
     exit 2
 }
diff --git a/install-google-chrome b/install-google-chrome
--- a/install-google-chrome
+++ b/install-google-chrome
@@ -6,7 +6,7 @@ abort() {
 }
 
 assert() {
-    "$@" || abort "%s: Assertion failed: %s\n" "$0" "$*"
+    "$@" || abort '%s: Assertion failed: %s\n' "$0" "$*"
 }
 
 install_google_chrome() {
@@ -62,7 +62,7 @@ set_user_profile "$script_dir"
 eval $(get-os-release -x)
 
 if [ $# -gt 1 ]; then
-    usage_error "%s: Too many arguments\n" "$0"
+    usage_error '%s: Too many arguments\n' "$0"
 fi
 
 install_google_chrome "$@"
diff --git a/install-homebrew b/install-homebrew
--- a/install-homebrew
+++ b/install-homebrew
@@ -26,11 +26,11 @@ abort() {
 }
 
 abort_not_supported() {
-    abort "%s: %s: %s not supported\n" "$script" "$PRETTY_NAME" "$*"
+    abort '%s: %s: %s not supported\n' "$script" "$PRETTY_NAME" "$*"
 }
 
 assert() {
-    "$@" || abort "%s: Assertion failed: %s\n" "$script" "$*"
+    "$@" || abort '%s: Assertion failed: %s\n' "$script" "$*"
 }
 
 configure_platform() {
@@ -236,7 +236,7 @@ validate_platform() {
 script=$(basename "$0")
 
 if [ $# -gt 0 ]; then
-    usage_error "%s: Too many arguments\n" "$script"
+    usage_error '%s: Too many arguments\n' "$script"
 fi
 
 case "$0" in
diff --git a/install-kubernetes b/install-kubernetes
--- a/install-kubernetes
+++ b/install-kubernetes
@@ -26,7 +26,7 @@ abort() {
 }
 
 abort_not_supported() {
-    abort "%s: %s: %s not supported\n" "$0" "$PRETTY_NAME" "$*"
+    abort '%s: %s: %s not supported\n' "$0" "$PRETTY_NAME" "$*"
 }
 
 add_debian_apt_key() {
@@ -70,12 +70,12 @@ add_repositories() {
 }
 
 assert() {
-    "$@" || abort "%s: Assertion failed: %s\n" "$0" "$*"
+    "$@" || abort '%s: Assertion failed: %s\n' "$0" "$*"
 }
 
 configure_network() {
     lsmod | if ! grep -q $MODULE; then
-	abort "%s: %s module not present\n" "$0" "$MODULE"
+	abort '%s: %s module not present\n' "$0" "$MODULE"
     fi
 
     if [ ! -d /etc/sysctl.d/k8s.conf ]; then
@@ -120,11 +120,11 @@ disable_selinux() {
 }
 
 get_google_apt_key_url() {
-    printf "%s\n" "$GOOGLE_BASE_URL/apt/doc/apt-key.gpg"
+    printf '%s\n' "$GOOGLE_BASE_URL/apt/doc/apt-key.gpg"
 }
 
 get_google_yum_url() {
-    printf "%s\n" "$GOOGLE_BASE_URL/yum"
+    printf '%s\n' "$GOOGLE_BASE_URL/yum"
 }
 
 get_kubernetes_debian_repo() {
@@ -134,13 +134,13 @@ get_kubernetes_debian_repo() {
 }
 
 get_kubernetes_url() {
-    printf "%s\n" "$KUBERNETES_BASE_URL/"
+    printf '%s\n' "$KUBERNETES_BASE_URL/"
 }
 
 get_package_manager_basename() {
     manager_pathname=$(get-package-managers | awk 'NR == 1 {print $0}')
     manager_basename=$(basename $manager_pathname)
-    printf "%s\n" $manager_basename
+    printf '%s\n' $manager_basename
 }
 
 install_dependencies() {
@@ -189,7 +189,7 @@ parse_arguments() {
 		role=$arg
 		;;
 	    (*)
-		abort "%s: %s -- invalid argument\n" "$0" "$arg"
+		abort '%s: %s -- invalid argument\n' "$0" "$arg"
 	esac
     done
 
@@ -284,7 +284,7 @@ validate_platform() {
     esac
 
     if ! docker info >/dev/null 2>&1; then
-	abort "%s: Docker not installed\n" "$0"
+	abort '%s: Docker not installed\n' "$0"
     fi
 }
 
diff --git a/install-macos-sdk-headers b/install-macos-sdk-headers
--- a/install-macos-sdk-headers
+++ b/install-macos-sdk-headers
@@ -25,15 +25,15 @@ abort() {
 }
 
 abort_not_supported() {
-    abort "%s: %s: %s not supported\n" "$0" "$PRETTY_NAME" "$*"
+    abort '%s: %s: %s not supported\n' "$0" "$PRETTY_NAME" "$*"
 }
 
 assert() {
-    "$@" || abort "%s: Assertion failed: %s\n" "$0" "$*"
+    "$@" || abort '%s: Assertion failed: %s\n' "$0" "$*"
 }
 
 get_darwin_pkg_pathname() {
-    printf "%s/$DARWIN_PKG_BASENAME\n" $DARWIN_PKG_DIRNAME $VERSION_ID
+    printf '%s/$DARWIN_PKG_BASENAME\n' $DARWIN_PKG_DIRNAME $VERSION_ID
 }
 
 install_macos_sdk_headers() {
@@ -64,7 +64,7 @@ usage_error() {
 }
 
 if [ $# -gt 0 ]; then
-    usage_error "%s: Too many arguments\n" "$0"
+    usage_error '%s: Too many arguments\n' "$0"
 fi
 
 case "$0" in
diff --git a/install-metapackages b/install-metapackages
--- a/install-metapackages
+++ b/install-metapackages
@@ -22,11 +22,11 @@ abort() {
 }
 
 abort_not_supported() {
-    abort "%s: %s: %s not supported\n" "$script" "$PRETTY_NAME" "$*"
+    abort '%s: %s: %s not supported\n' "$script" "$PRETTY_NAME" "$*"
 }
 
 assert() {
-    "$@" || abort "%s: Assertion failed: %s\n" "$script" "$*"
+    "$@" || abort '%s: Assertion failed: %s\n' "$script" "$*"
 }
 
 get_packages() {
@@ -60,7 +60,7 @@ parse_arguments() {
     shift $(($OPTIND - 1))
 
     if [ $# -lt 1 ]; then
-	usage_error "%s: Not enough arguments\n" "$script"
+	usage_error '%s: Not enough arguments\n' "$script"
     fi
 
     for category; do
diff --git a/install-mssql-odbc b/install-mssql-odbc
--- a/install-mssql-odbc
+++ b/install-mssql-odbc
@@ -25,15 +25,15 @@ abort() {
 }
 
 abort_not_supported() {
-    abort "%s: %s: %s not supported\n" "$0" "$PRETTY_NAME" "$*"
+    abort '%s: %s: %s not supported\n' "$0" "$PRETTY_NAME" "$*"
 }
 
 assert() {
-    "$@" || abort "%s: Assertion failed: %s\n" "$0" "$*"
+    "$@" || abort '%s: Assertion failed: %s\n' "$0" "$*"
 }
 
 get_packages() {
-    printf "%s\n" msodbcsql17 mssql-tools
+    printf '%s\n' msodbcsql17 mssql-tools
     get-odbc-development-packages
 }
 
@@ -94,7 +94,7 @@ validate_platform() {
 }
 
 if [ $# -gt 0 ]; then
-    usage_error "%s: Too many arguments\n" "$0"
+    usage_error '%s: Too many arguments\n' "$0"
 fi
 
 export ACCEPT_EULA=Y
diff --git a/install-mysql-odbc b/install-mysql-odbc
--- a/install-mysql-odbc
+++ b/install-mysql-odbc
@@ -30,11 +30,11 @@ abort() {
 }
 
 abort_not_supported() {
-    abort "%s: %s: %s not supported\n" "$0" "$PRETTY_NAME" "$*"
+    abort '%s: %s: %s not supported\n' "$0" "$PRETTY_NAME" "$*"
 }
 
 assert() {
-    "$@" || abort "%s: Assertion failed: %s\n" "$0" "$*"
+    "$@" || abort '%s: Assertion failed: %s\n' "$0" "$*"
 }
 
 install_mysql_odbc() {
@@ -104,7 +104,7 @@ parse_arguments() {
 		    prefix=/opt/$package
 		    ;;
 		(*)
-		    abort "%s: invalid argument" "$1"
+		    abort '%s: invalid argument' "$1"
 	    esac
 	    ;;
 	(rhel|ol|centos)
@@ -116,7 +116,7 @@ parse_arguments() {
 		    package=${basename%-linux-*-x86_64}
 		    ;;
 		(*)
-		    abort "%s: invalid argument" "$1"
+		    abort '%s: invalid argument' "$1"
 	    esac
 	    ;;
     esac
@@ -190,9 +190,9 @@ validate_platform() {
 }
 
 if [ $# -lt 1 ]; then
-    usage_error "%s: Not enough arguments\n" "$0"
+    usage_error '%s: Not enough arguments\n' "$0"
 elif [ $# -gt 1 ]; then
-    usage_error "%s: Too many arguments\n" "$0"
+    usage_error '%s: Too many arguments\n' "$0"
 fi
 
 case "$0" in
diff --git a/install-oracle-client b/install-oracle-client
--- a/install-oracle-client
+++ b/install-oracle-client
@@ -33,11 +33,11 @@ abort() {
 }
 
 abort_not_supported() {
-    abort "%s: %s: %s not supported\n" "$0" "$PRETTY_NAME" "$*"
+    abort '%s: %s: %s not supported\n' "$0" "$PRETTY_NAME" "$*"
 }
 
 assert() {
-    "$@" || abort "%s: Assertion failed: %s\n" "$0" "$*"
+    "$@" || abort '%s: Assertion failed: %s\n' "$0" "$*"
 }
 
 get_package_pathname() {
@@ -47,10 +47,10 @@ get_package_pathname() {
     assert [ -n "$3" ]
     case "$ID" in
 	(debian|ubuntu)
-	    printf "%s/$PREFIX_ZIP-$SUFFIX_ZIP\n" "$3" "$1" "$2"
+	    printf '%s/$PREFIX_ZIP-$SUFFIX_ZIP\n' "$3" "$1" "$2"
 	    ;;
 	(rhel|ol|centos)
-	    printf "%s/$PREFIX_RPM-$SUFFIX_RPM\n" "$3" "$2" "$1" "$2"
+	    printf '%s/$PREFIX_RPM-$SUFFIX_RPM\n' "$3" "$2" "$1" "$2"
 	    ;;
     esac
 }
@@ -201,7 +201,7 @@ validate_platform() {
 }
 
 if [ $# -gt 0 ]; then
-    usage_error "%s: Too many arguments\n" "$0"
+    usage_error '%s: Too many arguments\n' "$0"
 fi
 
 script_basename=$(basename "$0")
diff --git a/install-package-managers b/install-package-managers
--- a/install-package-managers
+++ b/install-package-managers
@@ -26,7 +26,7 @@ abort() {
 }
 
 assert() {
-    "$@" || abort "%s: Assertion failed: %s\n" "$0" "$*"
+    "$@" || abort '%s: Assertion failed: %s\n' "$0" "$*"
 }
 
 get_package_manager() {
@@ -45,7 +45,7 @@ get_package_manager() {
 	    ;;
     esac
 
-    printf "%s\n" "$manager"
+    printf '%s\n' "$manager"
 }
 
 install_package_manager() {
@@ -56,7 +56,7 @@ install_package_manager() {
     if [ -n "$package_manager" ]; then
 	"${script_prefix}$package_manager"
     else
-	abort "Unable to find installer for %s\n" "$1"
+	abort 'Unable to find installer for %s\n' "$1"
     fi
 }
 
diff --git a/install-packages b/install-packages
--- a/install-packages
+++ b/install-packages
@@ -22,11 +22,11 @@ abort() {
 }
 
 abort_not_supported() {
-    abort "%s: %s: %s not supported\n" "$0" "$PRETTY_NAME" "$*"
+    abort '%s: %s: %s not supported\n' "$0" "$PRETTY_NAME" "$*"
 }
 
 assert() {
-    "$@" || abort "%s: Assertion failed: %s\n" "$0" "$*"
+    "$@" || abort '%s: Assertion failed: %s\n' "$0" "$*"
 }
 
 configure_platform() {
@@ -83,7 +83,7 @@ get_package_manager() {
     assert [ $# -eq 1 ]
     assert [ -n "$1" ]
     assert [ $1 -ge 1 -a -$1 -le 2 ]
-    printf "%s\n" $package_managers | awk 'NR == '"$1"' {print $0}'
+    printf '%s\n' $package_managers | awk 'NR == '"$1"' {print $0}'
 }
 
 get_package_managers() {
@@ -104,7 +104,7 @@ get_packages() {
 	    ;;
     esac
 
-    printf "%s\n" $packages | awk -F: "$awk_expr"
+    printf '%s\n' $packages | awk -F: "$awk_expr"
 }
 
 install_packages() {
@@ -296,7 +296,7 @@ usage_error() {
 	printf "$@" >&2
     fi
 
-    printf "%s\n" '' >&2
+    printf '%s\n' '' >&2
     usage
     exit 2
 }
diff --git a/install-pgadmin4 b/install-pgadmin4
--- a/install-pgadmin4
+++ b/install-pgadmin4
@@ -22,11 +22,11 @@ abort() {
 }
 
 abort_not_supported() {
-    abort "%s: %s: %s not supported\n" "$0" "$PRETTY_NAME" "$*"
+    abort '%s: %s: %s not supported\n' "$0" "$PRETTY_NAME" "$*"
 }
 
 assert() {
-    "$@" || abort "%s: Assertion failed: %s\n" "$0" "$*"
+    "$@" || abort '%s: Assertion failed: %s\n' "$0" "$*"
 }
 
 install_pgadmin4() {
@@ -95,7 +95,7 @@ validate_platform() {
 }
 
 if [ $# -gt 0 ]; then
-    usage_error "%s: Too many arguments\n" "$0"
+    usage_error '%s: Too many arguments\n' "$0"
 fi
 
 case "$0" in
diff --git a/install-pgdg b/install-pgdg
--- a/install-pgdg
+++ b/install-pgdg
@@ -26,11 +26,11 @@ abort() {
 }
 
 abort_not_supported() {
-    abort "%s: %s: %s not supported\n" "$0" "$PRETTY_NAME" "$*"
+    abort '%s: %s: %s not supported\n' "$0" "$PRETTY_NAME" "$*"
 }
 
 assert() {
-    "$@" || abort "%s: Assertion failed: %s\n" "$0" "$*"
+    "$@" || abort '%s: Assertion failed: %s\n' "$0" "$*"
 }
 
 install_pgdg() {
@@ -48,7 +48,7 @@ install_platform() {
 	    ;;
 	(rhel|ol|centos)
 	    if ! rpm -q $PGDG_PACKAGE >/dev/null 2>&1; then
-		abort "%s: %s: No such package installed\n" "$0" $PGDG_PACKAGE
+		abort '%s: %s: No such package installed\n' "$0" $PGDG_PACKAGE
 	    fi
 	    ;;
     esac
@@ -116,7 +116,7 @@ validate_platform() {
 }
 
 if [ $# -gt 0 ]; then
-    usage_error "%s: Too many arguments\n" "$0"
+    usage_error '%s: Too many arguments\n' "$0"
 fi
 
 case "$0" in
diff --git a/install-pkgsrc b/install-pkgsrc
--- a/install-pkgsrc
+++ b/install-pkgsrc
@@ -39,11 +39,11 @@ abort() {
 }
 
 abort_not_supported() {
-    abort "%s: %s: %s not supported\n" "$0" "$PRETTY_NAME" "$*"
+    abort '%s: %s: %s not supported\n' "$0" "$PRETTY_NAME" "$*"
 }
 
 assert() {
-    "$@" || abort "%s: Assertion failed: %s\n" "$0" "$*"
+    "$@" || abort '%s: Assertion failed: %s\n' "$0" "$*"
 }
 
 install_pkgsrc() {
@@ -137,7 +137,7 @@ usage_error() {
 
 verify_checksum() {
     if which shasum >/dev/null 2>&1; then
-	eval printf "%s\n" "$boot_sha $boot_tar" | shasum || true
+	eval printf '%s\n' "$boot_sha $boot_tar" | shasum || true
     fi
 }
 
@@ -151,7 +151,7 @@ verify_signature() {
 }
 
 if [ $# -gt 1 ]; then
-    usage_error "%s: Too many arguments\n" "$0"
+    usage_error '%s: Too many arguments\n' "$0"
 fi
 
 case "$0" in
diff --git a/install-pyenv-on-macos b/install-pyenv-on-macos
--- a/install-pyenv-on-macos
+++ b/install-pyenv-on-macos
@@ -25,15 +25,15 @@ abort() {
 }
 
 abort_not_supported() {
-    abort "%s: %s: %s not supported\n" "$0" "$PRETTY_NAME" "$*"
+    abort '%s: %s: %s not supported\n' "$0" "$PRETTY_NAME" "$*"
 }
 
 assert() {
-    "$@" || abort "%s: Assertion failed: %s\n" "$0" "$*"
+    "$@" || abort '%s: Assertion failed: %s\n' "$0" "$*"
 }
 
 get_darwin_sdkroot() {
-    printf "%s/$DARWIN_SDK_BASENAME\n" $DARWIN_SDK_DIRNAME $VERSION_ID
+    printf '%s/$DARWIN_SDK_BASENAME\n' $DARWIN_SDK_DIRNAME $VERSION_ID
 }
 
 install_pyenv_on_macos() {
@@ -67,7 +67,7 @@ usage_error() {
 }
 
 if [ $# -gt 0 ]; then
-    usage_error "%s: Too many arguments\n" "$0"
+    usage_error '%s: Too many arguments\n' "$0"
 fi
 
 case "$0" in
diff --git a/install-root-scripts b/install-root-scripts
--- a/install-root-scripts
+++ b/install-root-scripts
@@ -25,7 +25,7 @@ abort() {
 }
 
 assert() {
-    "$@" || abort "%s: Assertion failed: %s\n" "$script" "$*"
+    "$@" || abort '%s: Assertion failed: %s\n' "$script" "$*"
 }
 
 get_install_command() {
@@ -55,10 +55,10 @@ get_script_files() {
 get_target_dir() {
     case "$ID" in
 	(rhel|ol|centos)
-	    printf "%s\n" /usr/sbin
+	    printf '%s\n' /usr/sbin
 	    ;;
 	(*)
-	    printf "%s\n" /usr/local/bin
+	    printf '%s\n' /usr/local/bin
 	    ;;
     esac
 }
@@ -75,7 +75,7 @@ install_root_scripts() {
     source_dir=$(pwd)
 
     if ! is_valid_script_dirname "$source_dir"; then
-	abort "%s: %s\n" \
+	abort '%s: %s\n' \
 	      "Please change to the source directory and try again" \
 	      "$script"
     fi
@@ -96,7 +96,7 @@ is_valid_script_dirname() {
 
 parse_arguments() {
     if [ $# -gt 1 ]; then
-	usage_error "%s: Too many arguments\n" "$script"
+	usage_error '%s: Too many arguments\n' "$script"
     fi
 
     if [ $# -gt 0 ]; then
diff --git a/install-scripts b/install-scripts
--- a/install-scripts
+++ b/install-scripts
@@ -26,7 +26,7 @@ abort() {
 }
 
 assert() {
-    "$@" || abort "%s: Assertion failed: %s\n" "$script" "$*"
+    "$@" || abort '%s: Assertion failed: %s\n' "$script" "$*"
 }
 
 configure_platform() {
@@ -115,7 +115,7 @@ install_scripts() {
     source_dir=$(pwd)
 
     if ! is_valid_script_dirname "$source_dir"; then
-	abort "%s: %s\n" \
+	abort '%s: %s\n' \
 	      "Please change to the source directory and try again" \
 	      "$script"
     fi
@@ -171,7 +171,7 @@ parse_arguments() {
     shift $(($OPTIND - 1))
 
     if [ $# -gt 1 ]; then
-	usage_error "%s: Too many arguments\n" "$script"
+	usage_error '%s: Too many arguments\n' "$script"
     fi
 
     if [ $# -gt 0 ]; then
@@ -184,7 +184,7 @@ remove_broken_links() {
     broken_links="$(get_broken_links .)"
 
     if [ -n "$broken_links" ]; then
-	printf "Removing broken link: %s\n" $broken_links
+	printf 'Removing broken link: %s\n' $broken_links
 	/bin/rm -f $broken_links
     fi
 }
@@ -201,7 +201,7 @@ usage_error() {
 	printf "$@" >&2
     fi
 
-    printf "%s\n" '' >&2
+    printf '%s\n' '' >&2
     usage
     exit 2
 }
diff --git a/install-startup-files b/install-startup-files
--- a/install-startup-files
+++ b/install-startup-files
@@ -30,19 +30,19 @@ abort() {
 }
 
 assert() {
-    "$@" || abort "%s: Assertion failed: %s\n" "$0" "$*"
+    "$@" || abort '%s: Assertion failed: %s\n' "$0" "$*"
 }
 
 format_git_directory() {
     assert [ $# -eq 1 ]
     assert [ -n "$1" ]
-    printf "%s/%s\n" "$1" "git"
+    printf '%s/%s\n' "$1" "git"
 }
 
 format_project_directory() {
     assert [ $# -eq 1 ]
     assert [ -n "$1" ]
-    printf "%s/%s\n" "$1" "$PROJECT_NAME"
+    printf '%s/%s\n' "$1" "$PROJECT_NAME"
 }
 
 format_project_url() {
@@ -61,7 +61,7 @@ get_project_directory() (
 	    project_dir=$(format_project_directory "$parent_dir")
 
 	    if [ -d "$project_dir" ]; then
-		printf "%s\n" "$project_dir"
+		printf '%s\n' "$project_dir"
 		return
 	    fi
 	done
@@ -90,7 +90,7 @@ install_startup_files() (
 
     for file in $STARTUP_FILES; do
 	if is_to_be_installed $file; then
-	    printf "Installing %s\n" $file
+	    printf 'Installing %s\n' $file
 
 	    if [ -r /etc/skel/$file -a "$file" = .profile ]; then
 		$gnu_install -bm 644 /etc/skel/$file $file
@@ -110,7 +110,7 @@ install_startup_files() (
 	cd .emacs.d
 
 	if [ ! -e init.el ]; then
-	    printf "Installing %s\n" .emacs.d/init.el
+	    printf 'Installing %s\n' .emacs.d/init.el
 	    $gnu_install -bm 644 $git_dir/.emacs.d/init.el init.el
 	fi
     fi
@@ -119,12 +119,12 @@ install_startup_files() (
 
     for file in $LEGACY_FILES; do
 	if [ -e $file ]; then
-	    printf "Renaming %s to %s\n" $file $file.orig
+	    printf 'Renaming %s to %s\n' $file $file.orig
 	    /bin/mv -f $file $file.orig
 	fi
     done
 
-    printf "Please log out and back in again to activate the new environment.\n"
+    printf 'Please log out and back in again to activate the new environment.\n'
     clean_up
 )
 
diff --git a/install-virtualbox-guest-additions b/install-virtualbox-guest-additions
--- a/install-virtualbox-guest-additions
+++ b/install-virtualbox-guest-additions
@@ -32,11 +32,11 @@ abort() {
 }
 
 abort_not_supported() {
-    abort "%s: %s: %s not supported\n" "$0" "$PRETTY_NAME" "$*"
+    abort '%s: %s: %s not supported\n' "$0" "$PRETTY_NAME" "$*"
 }
 
 assert() {
-    "$@" || abort "%s: Assertion failed: %s\n" "$0" "$*"
+    "$@" || abort '%s: Assertion failed: %s\n' "$0" "$*"
 }
 
 configure_platform() {
@@ -126,7 +126,7 @@ install_virtualbox_guest() {
 
     if [ "$kernel_name" != SunOS ]; then
 	until mount_package_directory; do
-	    printf "Insert VirtualBox Guest Additions CD-ROM and press Enter: "
+	    printf 'Insert VirtualBox Guest Additions CD-ROM and press Enter: '
 	    read INPUT
 	done
     else
@@ -196,7 +196,7 @@ update_redhat_kernel_packages() {
     fi
 
     trap "printf '\n'; exit 0" INT QUIT
-    printf "Please reboot the machine with the new kernel (if updated).\n"
+    printf 'Please reboot the machine with the new kernel (if updated).\n'
 }
 
 usage_error() {
@@ -273,13 +273,13 @@ validate_platform() {
 	    true
 	    ;;
 	(*)
-	    abort "%s: %s hypervisor not supported\n" "$0" "$vendor"
+	    abort '%s: %s hypervisor not supported\n' "$0" "$vendor"
 	    ;;
     esac
 }
 
 if [ $# -gt 0 ]; then
-    usage_error "%s: Too many arguments\n" "$0"
+    usage_error '%s: Too many arguments\n' "$0"
 fi
 
 case "$0" in
diff --git a/make-lilith b/make-lilith
--- a/make-lilith
+++ b/make-lilith
@@ -22,7 +22,7 @@ abort() {
 }
 
 assert() {
-    "$@" || abort "%s: Assertion failed: %s\n" "$0" "$*"
+    "$@" || abort '%s: Assertion failed: %s\n' "$0" "$*"
 }
 
 configure_platform() {
@@ -47,7 +47,7 @@ configure_platform() {
     done
 
     if [ -n "${arch-}" ]; then
-	printf "%s\n" $arch
+	printf '%s\n' $arch
     fi
 }
 
diff --git a/manage-app-database b/manage-app-database
--- a/manage-app-database
+++ b/manage-app-database
@@ -22,11 +22,11 @@ abort() {
 }
 
 assert() {
-    "$@" || abort "%s: Assertion failed: %s\n" "$0" "$*"
+    "$@" || abort '%s: Assertion failed: %s\n' "$0" "$*"
 }
 
 format_action() {
-    printf "%s\n" "$1 database" | to_upper
+    printf '%s\n' "$1 database" | to_upper
 }
 
 format_database() {
@@ -44,7 +44,7 @@ format_database() {
 	    printf '\\"%s\\"\n' "$2"
 	    ;;
 	(*)
-	    abort "%s: Invalid SQL dialect: %s\n" "$0" "$1"
+	    abort '%s: Invalid SQL dialect: %s\n' "$0" "$1"
 	    ;;
     esac
 }
@@ -80,7 +80,7 @@ parse_arguments() {
 	    true
 	    ;;
 	(*)
-	    usage_error "%s: Invalid action: %s\n" "$0" "$1"
+	    usage_error '%s: Invalid action: %s\n' "$0" "$1"
 	    ;;
     esac
 }
@@ -102,15 +102,15 @@ usage_error() {
 	printf "$@" >&2
     fi
 
-    printf "%s\n" '' >&2
+    printf '%s\n' '' >&2
     usage
     exit 2
 }
 
 if [ $# -lt 1 ]; then
-    usage_error "%s: Not enough arguments\n" "$0"
+    usage_error '%s: Not enough arguments\n' "$0"
 elif [ $# -gt 1 ]; then
-    usage_error "%s: Too many arguments\n" "$0"
+    usage_error '%s: Too many arguments\n' "$0"
 fi
 
 case "$0" in
@@ -143,7 +143,7 @@ fi
 
 if [ -n "$env_file" ]; then
     if [ "${VENV_VERBOSE-false}" = true ]; then
-	printf "%s\n" "Loading .env environment variables" >&2
+	printf '%s\n' "Loading .env environment variables" >&2
     fi
 
     . "$env_file"
diff --git a/pipenv-lock b/pipenv-lock
--- a/pipenv-lock
+++ b/pipenv-lock
@@ -26,7 +26,7 @@ abort() {
 }
 
 assert() {
-    "$@" || abort "%s: Assertion failed: %s\n" "$0" "$*"
+    "$@" || abort '%s: Assertion failed: %s\n' "$0" "$*"
 }
 
 parse_arguments() {
@@ -49,11 +49,11 @@ pipenv_lock() {
 }
 
 if [ "$(id -u)" -eq 0 ]; then
-    abort "%s: Must be run as a non-privileged user\n" "$0"
+    abort '%s: Must be run as a non-privileged user\n' "$0"
 fi
 
 if [ -n "${VIRTUAL_ENV:-}" ]; then
-    abort "%s: Must not be run within a virtual environment\n" "$0"
+    abort '%s: Must not be run within a virtual environment\n' "$0"
 fi
 
 case "$0" in
diff --git a/remove-from-path b/remove-from-path
--- a/remove-from-path
+++ b/remove-from-path
@@ -22,7 +22,7 @@ abort() {
 }
 
 assert() {
-    "$@" || abort "%s: Assertion failed: %s\n" "$script" "$*"
+    "$@" || abort '%s: Assertion failed: %s\n' "$script" "$*"
 }
 
 print_parameter() {
@@ -73,7 +73,7 @@ remove_from_path() {
 			shell=$OPTARG
 			;;
 		    (*)
-			usage_error "%s: %s: Unsupported shell\n" "$script" "$OPTARG"
+			usage_error '%s: %s: Unsupported shell\n' "$script" "$OPTARG"
 			;;
 		esac
 		;;
@@ -90,7 +90,7 @@ remove_from_path() {
     shift $(($OPTIND - 1))
 
     if [ $# -lt 2 ]; then
-	usage_error "%s: Not enough arguments\n" "$script"
+	usage_error '%s: Not enough arguments\n' "$script"
     fi
 
     var="$1"
diff --git a/run-image b/run-image
--- a/run-image
+++ b/run-image
@@ -22,7 +22,7 @@ abort() {
 }
 
 assert() {
-    "$@" || abort "%s: Assertion failed: %s\n" "$0" "$*"
+    "$@" || abort '%s: Assertion failed: %s\n' "$0" "$*"
 }
 
 get_buildah_from_options() {
@@ -34,7 +34,7 @@ get_buildah_from_options() {
 	printf -- "--cap-add=%s\n" $capabilities
     fi
 
-    printf -- "%s\n" $from_options
+    printf -- '%s\n' $from_options
 }
 
 get_default_capabilities() {
@@ -46,7 +46,7 @@ get_default_capabilities() {
 	    capabilities=$("${script_prefix}get-db2-capabilities")
 
 	    if [ -n "$capabilities" ]; then
-		printf "%s\n" $capabilities
+		printf '%s\n' $capabilities
 	    fi
 	    ;;
     esac
@@ -58,26 +58,26 @@ get_default_method() {
 
     case "$1" in
 	(*-ibm-db2-*)
-	    printf "%s\n" buildah
+	    printf '%s\n' buildah
 	    ;;
 	(*)
-	    printf "%s\n" docker
+	    printf '%s\n' docker
 	    ;;
     esac
 }
 
 get_image_dir_prefix() {
-    printf "%s\n" "${IMAGE_DIR_PREFIX-docker}-"
+    printf '%s\n' "${IMAGE_DIR_PREFIX-docker}-"
 }
 
 get_image_dir_root() {
-    printf "%s\n" "$(cd "${IMAGE_DIR_ROOT-$HOME}" && pwd)"
+    printf '%s\n' "$(cd "${IMAGE_DIR_ROOT-$HOME}" && pwd)"
 }
 
 get_image_method() {
     assert [ $# -eq 1 ]
     assert [ -n "$1" ]
-    printf "%s\n" "${method:-$(get_default_method "$1")}"
+    printf '%s\n' "${method:-$(get_default_method "$1")}"
 }
 
 get_image_name() {
@@ -102,18 +102,18 @@ get_image_run_options() {
 	    ;;
     esac
 
-    printf "%s\n" $options
+    printf '%s\n' $options
 }
 
 get_remote_image_name() {
     if [ "$is_remote" = true ]; then
-	printf "%s%s%s%s\n" \
+	printf '%s%s%s%s\n' \
 	       "${IMAGE_REMOTE_BASE_URL:+${IMAGE_REMOTE_BASE_URL#*//}/}" \
 	       "${IMAGE_REMOTE_DIR:+$IMAGE_REMOTE_DIR/}" \
 	       "${image#*/}" \
 	       "${tag:+:$tag}"
     else
-	printf "%s%s\n" \
+	printf '%s%s\n' \
 	       "${image#*/}" \
 	       "${tag:+:$tag}"
     fi
@@ -142,7 +142,7 @@ parse_arguments() {
 			method="$OPTARG"
 			;;
 		    (*)
-			usage_error "%s: %s: Invalid method\n" "$0" "$OPTARG"
+			usage_error '%s: %s: Invalid method\n' "$0" "$OPTARG"
 			;;
 		esac
 		;;
@@ -174,9 +174,9 @@ parse_arguments() {
     shift $(($OPTIND - 1))
 
     if [ $# -lt 1 ]; then
-	usage_error "%s: Not enough arguments\n" "$0"
+	usage_error '%s: Not enough arguments\n' "$0"
     elif [ $# -gt 1 ]; then
-	usage_error "%s: Too many arguments\n" "$0"
+	usage_error '%s: Too many arguments\n' "$0"
     fi
 
     file=$1
@@ -188,19 +188,19 @@ parse_arguments() {
 		dockerfile="$file"
 		;;
 	    (*)
-		abort "%s: %s: Not a Dockerfile\n" "$0" "$file"
+		abort '%s: %s: Not a Dockerfile\n' "$0" "$file"
 		;;
 	esac
     elif [ -e "$file" ]; then
-	abort "%s: %s: Not a Dockerfile\n" "$0" "$file"
+	abort '%s: %s: Not a Dockerfile\n' "$0" "$file"
     else
-	abort "%s: %s: No such file\n" "$0" "$file"
+	abort '%s: %s: No such file\n' "$0" "$file"
     fi
 }
 
 run_image() {
     dir=$(cd "$(dirname "$dockerfile")" && pwd)
-    image=$(printf "%s\n" "$dir" | get_image_name)
+    image=$(printf '%s\n' "$dir" | get_image_name)
     image_method=$(get_image_method $image)
     remote_image=$(get_remote_image_name)
 
@@ -233,7 +233,7 @@ usage_error() {
 	printf "$@" >&2
     fi
 
-    printf "%s\n" '' >&2
+    printf '%s\n' '' >&2
     usage
     exit 2
 }
diff --git a/run-sql b/run-sql
--- a/run-sql
+++ b/run-sql
@@ -25,7 +25,7 @@ abort() {
 }
 
 assert() {
-    "$@" || abort "%s: Assertion failed: %s\n" "$0" "$*"
+    "$@" || abort '%s: Assertion failed: %s\n' "$0" "$*"
 }
 
 configure_platform() {
@@ -70,12 +70,12 @@ get_cli_command() {
 	    get_cli_sqlite
 	    ;;
 	(*)
-	    abort "%s: Invalid SQL dialect '%s'\n" "$DATABASE_DIALECT"
+	    abort '%s: Invalid SQL dialect '%s'\n' "$DATABASE_DIALECT"
     esac
 }
 
 get_cli_mssql() {
-    printf "%s\n" sqlcmd \
+    printf '%s\n' sqlcmd \
 	   -H ${DATABASE_HOST:-${MSSQL_HOST:-${WSL_HOST:-localhost}}} \
 	   -U ${DATABASE_USER:-${MSSQL_USER:-$user}} \
 	   -P ${DATABASE_PASSWORD:-${MYSQL_PASSWORD-}} \
@@ -83,7 +83,7 @@ get_cli_mssql() {
 }
 
 get_cli_mysql() {
-    printf "%s\n" mysql \
+    printf '%s\n' mysql \
 	   --protocol=${DATABASE_PROTOCOL:-${MYSQL_PROTOCOL:-TCP}} \
 	   --host=${DATABASE_HOST:-${MYSQL_HOST:-${WSL_HOST:-localhost}}} \
 	   --port=${DATABASE_PORT:-${MYSQL_PORT:-3306}} \
@@ -92,7 +92,7 @@ get_cli_mysql() {
 	   --database=${DATABASE_INSTANCE:-${MYSQL_INSTANCE:-mysql}}
 
     if [ -n "${command-}" ]; then
-	printf "%s\n" --execute="\"$command\""
+	printf '%s\n' --execute="\"$command\""
     fi
 }
 
@@ -102,18 +102,18 @@ get_cli_oracle() {
     username=${DATABASE_USER:-${ORACLE_USER:-$user}}
     password=${DATABASE_PASSWORD:-${ORACLE_PASSWORD-}}
     instance=${DATABASE_INSTANCE:-${ORACLE_INSTANCE:-ORCLCDB}}
-    printf "%s\n" sqlplus "$username/$password@//$host:$port/$instance"
+    printf '%s\n' sqlplus "$username/$password@//$host:$port/$instance"
 }
 
 get_cli_postgresql() {
-    printf "%s\n" psql \
+    printf '%s\n' psql \
 	   --host=${DATABASE_HOST:-${POSTGRES_HOST:-${WSL_HOST:-localhost}}} \
 	   --port=${DATABASE_PORT:-${POSTGRES_PORT:-5432}} \
 	   --username=${DATABASE_USER:-${POSTGRES_USER:-$user}} \
 	   --password
 
     if [ -n "${command-}" ]; then
-	printf "%s\n" --command="\"$command\""
+	printf '%s\n' --command="\"$command\""
     fi
 }
 
@@ -123,7 +123,7 @@ get_cli_sap_hana() {
     username=${DATABASE_USER:-${SAP_HANA_USER:-SYSTEM}}
     password=${DATABASE_PASSWORD:-${SAP_HANA_PASSWORD-}}
     instance=${DATABASE_INSTANCE:-${SAP_HANA_INSTANCE:-SYSTEMDB}}
-    printf "%s\n" hdbsql -i 90 \
+    printf '%s\n' hdbsql -i 90 \
 	   ${host:+-n $host${port:+:$port}} \
 	   ${instance:+-d $instance} \
 	   ${username:+-u $username} \
@@ -131,7 +131,7 @@ get_cli_sap_hana() {
 }
 
 get_cli_sqlite() {
-    printf "%s\n" sqlite3 ${DATABASE_PATHNAME:-${SQLITE_PATHNAME-}}
+    printf '%s\n' sqlite3 ${DATABASE_PATHNAME:-${SQLITE_PATHNAME-}}
 }
 
 has_env_file() {
@@ -155,7 +155,7 @@ parse_argument() {
 	    if [ "$DATABASE_DIALECT" = sqlite ]; then
 		DATABASE_PATHNAME=$1
 	    else
-		abort "%s: Invalid SQL script name: %s\n" "$0" "$1"
+		abort '%s: Invalid SQL script name: %s\n' "$0" "$1"
 	    fi
 	    ;;
 	(*)
@@ -178,7 +178,7 @@ parse_argument() {
 	done
 
 	if [ -z "${script}" ]; then
-	    abort "%s: No such script file\n" "$name"
+	    abort '%s: No such script file\n' "$name"
 	fi
     fi
 
@@ -222,9 +222,9 @@ run_sql() {
 		exec <$script
 		exec_sql_command $winpty
 	    elif [ -d $script ]; then
-		abort "%s: %s: Is a directory\n" "$0" "$script"
+		abort '%s: %s: Is a directory\n' "$0" "$script"
 	    else
-		abort "%s: %s: No such script file\n" "$0" "$script"
+		abort '%s: %s: No such script file\n' "$0" "$script"
 	    fi
 	done
     else
@@ -245,7 +245,7 @@ usage_error() {
 	printf "$@" >&2
     fi
 
-    printf "%s\n" '' >&2
+    printf '%s\n' '' >&2
     usage
     exit 2
 }
@@ -281,7 +281,7 @@ fi
 
 if [ -n "$env_file" ]; then
     if [ "${VENV_VERBOSE-false}" = true ]; then
-	printf "%s\n" "Loading $ENV_FILE environment variables" >&2
+	printf '%s\n' "Loading $ENV_FILE environment variables" >&2
     fi
 
     . "$env_file"
diff --git a/set-askpass-parameters b/set-askpass-parameters
--- a/set-askpass-parameters
+++ b/set-askpass-parameters
@@ -24,7 +24,7 @@ abort() {
 }
 
 assert() {
-    "$@" || abort "%s: Assertion failed: %s\n" "$script" "$*"
+    "$@" || abort '%s: Assertion failed: %s\n' "$script" "$*"
 }
 
 configure_platform() {
@@ -82,7 +82,7 @@ parse_command() {
 	    commands=${commands:+$commands }"$1"
 	    ;;
 	(*)
-	    usage_error "%s: %s: Unsupported command\n" "$script" "$1"
+	    usage_error '%s: %s: Unsupported command\n' "$script" "$1"
     esac
 }
 
@@ -101,7 +101,7 @@ parse_shell() {
 	    shell=${1%.exe}
 	    ;;
 	(*)
-	    usage_error "%s: %s: Unsupported shell\n" "$script" "$1"
+	    usage_error '%s: %s: Unsupported shell\n' "$script" "$1"
 	    ;;
     esac
 }
diff --git a/set-display-parameters b/set-display-parameters
--- a/set-display-parameters
+++ b/set-display-parameters
@@ -24,7 +24,7 @@ abort() {
 }
 
 assert() {
-    "$@" || abort "%s: Assertion failed: %s\n" "$script" "$*"
+    "$@" || abort '%s: Assertion failed: %s\n' "$script" "$*"
 }
 
 parse_arguments() {
@@ -60,7 +60,7 @@ parse_arguments() {
     shift $(($OPTIND - 1))
 
     if [ $# -gt 0 ]; then
-	usage_error "%s: Too many arguments\n" "$script"
+	usage_error '%s: Too many arguments\n' "$script"
     fi
 }
 
@@ -79,7 +79,7 @@ parse_shell() {
 	    shell=${1%.exe}
 	    ;;
 	(*)
-	    usage_error "%s: %s: Unsupported shell\n" "$script" "$1"
+	    usage_error '%s: %s: Unsupported shell\n' "$script" "$1"
 	    ;;
     esac
 }
diff --git a/set-parameters b/set-parameters
--- a/set-parameters
+++ b/set-parameters
@@ -22,7 +22,7 @@ abort() {
 }
 
 assert() {
-    "$@" || abort "%s: Assertion failed: %s\n" "$script" "$*"
+    "$@" || abort '%s: Assertion failed: %s\n' "$script" "$*"
 }
 
 parse_arguments() {
@@ -46,7 +46,7 @@ parse_arguments() {
     shift $(($OPTIND - 1))
 
     if [ $# -gt 0 ]; then
-	usage_error "%s: Too many arguments\n" "$script"
+	usage_error '%s: Too many arguments\n' "$script"
     fi
 }
 
@@ -65,7 +65,7 @@ parse_shell() {
 	    shell=${1%.exe}
 	    ;;
 	(*)
-	    usage_error "%s: %s: Unsupported shell\n" "$script" "$1"
+	    usage_error '%s: %s: Unsupported shell\n' "$script" "$1"
 	    ;;
     esac
 }
diff --git a/set-profile-parameters b/set-profile-parameters
--- a/set-profile-parameters
+++ b/set-profile-parameters
@@ -32,7 +32,7 @@ abort() {
 }
 
 assert() {
-    "$@" || abort "%s: Assertion failed: %s\n" "$script" "$*"
+    "$@" || abort '%s: Assertion failed: %s\n' "$script" "$*"
 }
 
 configure_platform() {
@@ -282,7 +282,7 @@ parse_arguments() {
     shift $(($OPTIND - 1))
 
     if [ $# -gt 0 ]; then
-	usage_error "%s: Too many arguments\n" "$script"
+	usage_error '%s: Too many arguments\n' "$script"
     fi
 }
 
@@ -301,7 +301,7 @@ parse_shell() {
 	    shell=${1%.exe}
 	    ;;
 	(*)
-	    usage_error "%s: %s: Unsupported shell\n" "$script" "$1"
+	    usage_error '%s: %s: Unsupported shell\n' "$script" "$1"
 	    ;;
     esac
 }
diff --git a/set-proxy-parameters b/set-proxy-parameters
--- a/set-proxy-parameters
+++ b/set-proxy-parameters
@@ -25,7 +25,7 @@ abort() {
 }
 
 assert() {
-    "$@" || abort "%s: Assertion failed: %s\n" "$script" "$*"
+    "$@" || abort '%s: Assertion failed: %s\n' "$script" "$*"
 }
 
 configure_platform() {
@@ -67,7 +67,7 @@ parse_arguments() {
     shift $(($OPTIND - 1))
 
     if [ $# -gt 0 ]; then
-	usage_error "%s: Too many arguments\n" "$script"
+	usage_error '%s: Too many arguments\n' "$script"
     fi
 }
 
@@ -86,7 +86,7 @@ parse_shell() {
 	    shell=${1%.exe}
 	    ;;
 	(*)
-	    usage_error "%s: %s: Unsupported shell\n" "$script" "$1"
+	    usage_error '%s: %s: Unsupported shell\n' "$script" "$1"
 	    ;;
     esac
 }
diff --git a/uninstall-docker b/uninstall-docker
--- a/uninstall-docker
+++ b/uninstall-docker
@@ -22,11 +22,11 @@ abort() {
 }
 
 abort_not_supported() {
-    abort "%s: %s: %s not supported\n" "$0" "$PRETTY_NAME" "$*"
+    abort '%s: %s: %s not supported\n' "$0" "$PRETTY_NAME" "$*"
 }
 
 assert() {
-    "$@" || abort "%s: Assertion failed: %s\n" "$0" "$*"
+    "$@" || abort '%s: Assertion failed: %s\n' "$0" "$*"
 }
 
 get_docker_origin() {
@@ -44,7 +44,7 @@ get_docker_origin() {
 	esac
 
 	if [ -n "${origin-}" ]; then
-	    printf "%s\n" "$origin"
+	    printf '%s\n' "$origin"
 	    return
 	fi
     done
@@ -70,17 +70,17 @@ uninstall_docker() {
     if [ -n "$origin" ]; then
 	case "$origin" in
 	    (docker.com)
-		printf "Docker Community Edition is installed.\n"
+		printf 'Docker Community Edition is installed.\n'
 		;;
 	    (native)
-		printf "Native Docker is installed.\n"
+		printf 'Native Docker is installed.\n'
 		;;
 	    (podman)
-		printf "Podman is installed.\n"
+		printf 'Podman is installed.\n'
 		;;
 	esac
     else
-	printf "Docker is not installed.\n"
+	printf 'Docker is not installed.\n'
     fi
 
     if [ -n "$packages" ]; then
diff --git a/uninstall-mysql-odbc b/uninstall-mysql-odbc
--- a/uninstall-mysql-odbc
+++ b/uninstall-mysql-odbc
@@ -30,7 +30,7 @@ abort() {
 }
 
 assert() {
-    "$@" || abort "%s: Assertion failed: %s\n" "$0" "$*"
+    "$@" || abort '%s: Assertion failed: %s\n' "$0" "$*"
 }
 
 uninstall_mysql_odbc() {
@@ -61,7 +61,7 @@ parse_arguments() {
 	    package=${dirname%-linux-*-x86-64bit}
 	    ;;
 	(*)
-	    abort "%s: invalid argument" "$1"
+	    abort '%s: invalid argument' "$1"
     esac
 }
 
@@ -92,9 +92,9 @@ validate_platform() {
 }
 
 if [ $# -lt 1 ]; then
-    usage_error "%s: Not enough arguments\n" "$0"
+    usage_error '%s: Not enough arguments\n' "$0"
 elif [ $# -gt 1 ]; then
-    usage_error "%s: Too many arguments\n" "$0"
+    usage_error '%s: Too many arguments\n' "$0"
 fi
 
 case "$0" in
