Set parameter script to "$(basename "$0")" for use in diagnostics.

diff --git a/build-images b/build-images
--- a/build-images
+++ b/build-images
@@ -24,7 +24,7 @@ abort() {
 }
 
 assert() {
-    "$@" || abort '%s: Assertion failed: %s\n' "$0" "$*"
+    "$@" || abort '%s: Assertion failed: %s\n' "$script" "$*"
 }
 
 build_images() {
@@ -225,7 +225,9 @@ parse_arguments() {
 			method="$OPTARG"
 			;;
 		    (*)
-			usage_error '%s: %s: Invalid method\n' "$0" "$OPTARG"
+			usage_error '%s: %s: Invalid method\n' \
+				    "$script" \
+				    "$OPTARG"
 			;;
 		esac
 		;;
@@ -268,21 +270,21 @@ parse_arguments() {
 		    dockerfiles="${dockerfiles+$dockerfiles }$file"
 		    ;;
 		(*)
-		    abort '%s: %s: Not a Dockerfile\n' "$0" "$file"
+		    abort '%s: %s: Not a Dockerfile\n' "$script" "$file"
 		    ;;
 	    esac
 	elif [ -e "$file" ]; then
-	    abort '%s: %s: Not a Dockerfile\n' "$0" "$file"
+	    abort '%s: %s: Not a Dockerfile\n' "$script" "$file"
 	else
-	    abort '%s: %s: No such file\n' "$0" "$file"
+	    abort '%s: %s: No such file\n' "$script" "$file"
 	fi
     done
 }
 
 usage() {
     cat <<EOF >&2
-Usage: $0 [-M METHOD] [-b] [-l] [-p] [-t TAG]
-       $0 -h
+Usage: $script [-M METHOD] [-b] [-l] [-p] [-t TAG]
+       $script -h
 EOF
 }
 
@@ -295,6 +297,8 @@ usage_error() {
     usage
     exit 2
 }
+
+script=$(basename "$0")
 
 case "$0" in
     (*/*)
diff --git a/build-uwsgi b/build-uwsgi
--- a/build-uwsgi
+++ b/build-uwsgi
@@ -22,7 +22,7 @@ abort() {
 }
 
 assert() {
-    "$@" || abort '%s: Assertion failed: %s\n' "$0" "$*"
+    "$@" || abort '%s: Assertion failed: %s\n' "$script" "$*"
 }
 
 build_binary() (
@@ -91,15 +91,7 @@ usage_error() {
     exit 2
 }
 
-if [ $# -lt 2 ]; then
-    usage_error '%s: Not enough arguments\n' "$0"
-elif [ $# -gt 2 ]; then
-    usage_error '%s: Too many arguments\n' "$0"
-fi
-
-if [ "$(id -u)" -eq 0 ]; then
-    abort '%s: Must be run as a non-privileged user\n' "$0"
-fi
+script=$(basename "$0")
 
 case "$0" in
     (*/*)
@@ -116,6 +108,16 @@ script_prefix=${script_dir:+$script_dir/}
 . "${script_prefix}utility-functions.sh"
 . "${script_prefix}restapi-functions.sh"
 . "${script_prefix}restapi-parameters.sh"
+
+if [ $# -lt 2 ]; then
+    usage_error '%s: Not enough arguments\n' "$script"
+elif [ $# -gt 2 ]; then
+    usage_error '%s: Too many arguments\n' "$script"
+fi
+
+if [ "$(id -u)" -eq 0 ]; then
+    abort '%s: Must be run as a non-privileged user\n' "$script"
+fi
 
 SYSTEM_PYTHON=$1
 SYSTEM_PYTHON_VERSION=$2
diff --git a/check-python b/check-python
--- a/check-python
+++ b/check-python
@@ -19,7 +19,7 @@ abort() {
 }
 
 assert() {
-    "$@" || abort '%s: Assertion failed: %s\n' "$0" "$*"
+    "$@" || abort '%s: Assertion failed: %s\n' "$script" "$*"
 }
 
 usage_error() {
@@ -27,14 +27,27 @@ usage_error() {
     exit 2
 }
 
-if [ $# -lt 1 ]; then
-    usage_error '%s: Not enough arguments\n' "$0"
-elif [ $# -gt 1 ]; then
-    usage_error '%s: Too many arguments\n' "$0"
-fi
+script=$(basename "$0")
 
-. common-functions.sh
-. utility-functions.sh
+case "$0" in
+    (*/*)
+	script_dir=$(cd "$(dirname "$0")" && pwd)
+	;;
+    (*)
+	script_dir=
+	;;
+esac
+
+script_prefix=${script_dir:+$script_dir/}
+
+. "${script_prefix}common-functions.sh"
+. "${script_prefix}utility-functions.sh"
+
+if [ $# -lt 1 ]; then
+    usage_error '%s: Not enough arguments\n' "$script"
+elif [ $# -gt 1 ]; then
+    usage_error '%s: Too many arguments\n' "$script"
+fi
 
 version="$("$1" --version | awk '{print $2'})"
 
diff --git a/clean-up-app-caches b/clean-up-app-caches
--- a/clean-up-app-caches
+++ b/clean-up-app-caches
@@ -22,7 +22,7 @@ abort() {
 }
 
 assert() {
-    "$@" || abort '%s: Assertion failed: %s\n' "$0" "$*"
+    "$@" || abort '%s: Assertion failed: %s\n' "$script" "$*"
 }
 
 clean_up_app_caches() {
@@ -45,9 +45,7 @@ usage_error() {
     exit 2
 }
 
-if [ $# -gt 0 ]; then
-    usage_error '%s: Too many arguments\n' "$0"
-fi
+script=$(basename "$0")
 
 case "$0" in
     (*/*)
@@ -59,6 +57,10 @@ case "$0" in
 esac
 
 script_prefix=${script_dir:+$script_dir/}
+
+if [ $# -gt 0 ]; then
+    usage_error '%s: Too many arguments\n' "$script"
+fi
 
 eval $("${script_prefix}get-configuration" app.ini)
 clean_up_app_caches
diff --git a/clean-up-kernel-packages b/clean-up-kernel-packages
--- a/clean-up-kernel-packages
+++ b/clean-up-kernel-packages
@@ -24,11 +24,11 @@ abort() {
 }
 
 abort_not_supported() {
-    abort '%s: %s: %s not supported\n' "$0" "$PRETTY_NAME" "$*"
+    abort '%s: %s: %s not supported\n' "$script" "$PRETTY_NAME" "$*"
 }
 
 assert() {
-    "$@" || abort '%s: Assertion failed: %s\n' "$0" "$*"
+    "$@" || abort '%s: Assertion failed: %s\n' "$script" "$*"
 }
 
 clean_up_kernel_dumps() {
@@ -119,9 +119,7 @@ validate_platform() {
     esac
 }
 
-if [ $# -gt 0 ]; then
-    usage_error '%s: Too many arguments\n' "$0"
-fi
+script=$(basename "$0")
 
 case "$0" in
     (*/*)
@@ -133,6 +131,10 @@ case "$0" in
 esac
 
 script_prefix=${script_dir:+$script_dir/}
+
+if [ $# -gt 0 ]; then
+    usage_error '%s: Too many arguments\n' "$script"
+fi
 
 . "${script_prefix}common-functions.sh"
 
diff --git a/configure-emacs-x11 b/configure-emacs-x11
--- a/configure-emacs-x11
+++ b/configure-emacs-x11
@@ -29,23 +29,23 @@ abort() {
 }
 
 abort_invalid_prefix() {
-    usage_error '%s: invalid prefix -- %s\n' "$0" "$*"
+    usage_error '%s: invalid prefix -- %s\n' "$script" "$*"
 }
 
 abort_invalid_toolkit() {
-    usage_error '%s: invalid toolkit -- %s\n' "$0" "$*"
+    usage_error '%s: invalid toolkit -- %s\n' "$script" "$*"
 }
 
 abort_invalid_version() {
-    usage_error '%s: invalid version -- %s\n' "$0" "$*"
+    usage_error '%s: invalid version -- %s\n' "$script" "$*"
 }
 
 abort_not_supported() {
-    abort '%s: %s: %s not supported\n' "$0" "$PRETTY_NAME" "$*"
+    abort '%s: %s: %s not supported\n' "$script" "$PRETTY_NAME" "$*"
 }
 
 assert() {
-    "$@" || abort '%s: Assertion failed: %s\n' "$0" "$*"
+    "$@" || abort '%s: Assertion failed: %s\n' "$script" "$*"
 }
 
 clean_build() {
@@ -137,7 +137,7 @@ configure_platform() {
     done
 
     if [ -n "${cc-}" ] && [ ! -x $cc ]; then
-	abort '%s: %s: No such compiler\n' "$0" "$cc"
+	abort '%s: %s: No such compiler\n' "$script" "$cc"
     fi
 }
 
@@ -400,18 +400,18 @@ parse_arguments() {
     shift $(($OPTIND - 1))
 
     if [ $# -gt 0 ]; then
-	usage_error '%s: Too many arguments\n' "$0"
+	usage_error '%s: Too many arguments\n' "$script"
     fi
 
     if [ "$with_gif" = true -a -n "${libgif-}" ] && [ ! -x $libgif ]; then
-	abort '%s: %s: No such shared object\n' "$0" "$libgif"
+	abort '%s: %s: No such shared object\n' "$script" "$libgif"
     fi
 }
 
 usage() {
     cat <<EOF >&2
-Usage: $0 [-f] [-p PREFIX] [-t TOOLKIT] [-v VERSION] [-w]
-       $0 -h
+Usage: $script [-f] [-p PREFIX] [-t TOOLKIT] [-v VERSION] [-w]
+       $script -h
 EOF
 }
 
@@ -488,6 +488,8 @@ validate_platform() {
 	    ;;
     esac
 }
+
+script=$(basename "$0")
 
 case "$0" in
     (*/*)
diff --git a/configure-giflib b/configure-giflib
--- a/configure-giflib
+++ b/configure-giflib
@@ -30,19 +30,19 @@ abort() {
 }
 
 abort_invalid_prefix() {
-    usage_error '%s: invalid prefix -- %s\n' "$0" "$*"
+    usage_error '%s: invalid prefix -- %s\n' "$script" "$*"
 }
 
 abort_invalid_version() {
-    usage_error '%s: invalid version -- %s\n' "$0" "$*"
+    usage_error '%s: invalid version -- %s\n' "$script" "$*"
 }
 
 abort_not_supported() {
-    abort '%s: %s: %s not supported\n' "$0" "$PRETTY_NAME" "$*"
+    abort '%s: %s: %s not supported\n' "$script" "$PRETTY_NAME" "$*"
 }
 
 assert() {
-    "$@" || abort '%s: Assertion failed: %s\n' "$0" "$*"
+    "$@" || abort '%s: Assertion failed: %s\n' "$script" "$*"
 }
 
 configure_giflib() {
@@ -54,7 +54,7 @@ configure_giflib() {
     pathname=$archive_dir/$filename
 
     if [ ! -f $pathname ]; then
-	abort '%s: %s: No such archive file\n' "$0" "$pathname"
+	abort '%s: %s: No such archive file\n' "$script" "$pathname"
     fi
 
     src_dir="$HOME/Documents/src/GIFLIB/$basename"
@@ -100,8 +100,8 @@ parse_arguments() {
 
 usage() {
     cat <<EOF >&2
-Usage: $0 [-f]
-       $0 -h
+Usage: $script [-f]
+       $script -h
 EOF
 }
 
@@ -163,6 +163,8 @@ validate_platform() {
 	    ;;
     esac
 }
+
+script=$(basename "$0")
 
 eval $(get-os-release -x)
 
diff --git a/configure-python b/configure-python
--- a/configure-python
+++ b/configure-python
@@ -29,19 +29,19 @@ abort() {
 }
 
 abort_invalid_prefix() {
-    usage_error '%s: invalid prefix -- %s\n' "$0" "$*"
+    usage_error '%s: invalid prefix -- %s\n' "$script" "$*"
 }
 
 abort_invalid_version() {
-    usage_error '%s: invalid version -- %s\n' "$0" "$*"
+    usage_error '%s: invalid version -- %s\n' "$script" "$*"
 }
 
 abort_not_supported() {
-    abort '%s: %s: %s not supported\n' "$0" "$PRETTY_NAME" "$*"
+    abort '%s: %s: %s not supported\n' "$script" "$PRETTY_NAME" "$*"
 }
 
 assert() {
-    "$@" || abort '%s: Assertion failed: %s\n' "$0" "$*"
+    "$@" || abort '%s: Assertion failed: %s\n' "$script" "$*"
 }
 
 clean_build() {
@@ -95,7 +95,7 @@ configure_platform() {
     done
 
     if [ -n "${cc-}" ] && [ ! -x $cc ]; then
-	abort '%s: %s: No such compiler\n' "$0" "$cc"
+	abort '%s: %s: No such compiler\n' "$script" "$cc"
     fi
 }
 
@@ -356,14 +356,14 @@ parse_arguments() {
     shift $(($OPTIND - 1))
 
     if [ $# -gt 0 ]; then
-	usage_error '%s: Too many arguments\n' "$0"
+	usage_error '%s: Too many arguments\n' "$script"
     fi
 }
 
 usage() {
     cat <<EOF >&2
-Usage: $0 [-d|-e][-f] [-p PREFIX] [-v VERSION]
-       $0 -h
+Usage: $script [-d|-e][-f] [-p PREFIX] [-v VERSION]
+       $script -h
 EOF
 }
 
@@ -408,6 +408,8 @@ validate_platform() {
 	    ;;
     esac
 }
+
+script=$(basename "$0")
 
 case "$0" in
     (*/*)
diff --git a/create-app-database b/create-app-database
--- a/create-app-database
+++ b/create-app-database
@@ -22,7 +22,7 @@ abort() {
 }
 
 assert() {
-    "$@" || abort '%s: Assertion failed: %s\n' "$0" "$*"
+    "$@" || abort '%s: Assertion failed: %s\n' "$script" "$*"
 }
 
 usage_error() {
@@ -30,9 +30,7 @@ usage_error() {
     exit 2
 }
 
-if [ $# -gt 0 ]; then
-    usage_error '%s: Too many arguments\n' "$0"
-fi
+script=$(basename "$0")
 
 case "$0" in
     (*/*)
@@ -46,6 +44,10 @@ esac
 script_prefix=${script_dir:+$script_dir/}
 
 . "${script_prefix}common-functions.sh"
+
+if [ $# -gt 0 ]; then
+    usage_error '%s: Too many arguments\n' "$script"
+fi
 
 set_user_profile "$script_dir"
 manage-app-database create
diff --git a/docker-exec-oracle-client b/docker-exec-oracle-client
--- a/docker-exec-oracle-client
+++ b/docker-exec-oracle-client
@@ -22,7 +22,7 @@ abort() {
 }
 
 assert() {
-    "$@" || abort '%s: Assertion failed: %s\n' "$0" "$*"
+    "$@" || abort '%s: Assertion failed: %s\n' "$script" "$*"
 }
 
 usage_error() {
@@ -30,11 +30,7 @@ usage_error() {
     exit 2
 }
 
-if [ $# -lt 1 ]; then
-    usage_error '%s: Not enough arguments\n' "$0"
-elif [ $# -gt 1 ]; then
-    usage_error '%s: Too many arguments\n' "$0"
-fi
+script=$(basename "$0")
 
 case "$0" in
     (*/*)
@@ -48,6 +44,12 @@ esac
 script_prefix=${script_dir:+$script_dir/}
 
 . "${script_prefix}oracle-config.sh"
+
+if [ $# -lt 1 ]; then
+    usage_error '%s: Not enough arguments\n' "$script"
+elif [ $# -gt 1 ]; then
+    usage_error '%s: Too many arguments\n' "$script"
+fi
 
 if [ -r $HOME/.env-oracle ]; then
     . $HOME/.env-oracle
diff --git a/docker-run-oracle-server b/docker-run-oracle-server
--- a/docker-run-oracle-server
+++ b/docker-run-oracle-server
@@ -25,7 +25,7 @@ abort() {
 }
 
 assert() {
-    "$@" || abort '%s: Assertion failed: %s\n' "$0" "$*"
+    "$@" || abort '%s: Assertion failed: %s\n' "$script" "$*"
 }
 
 docker_run_oracle_server() {
@@ -74,9 +74,7 @@ usage_error() {
     exit 2
 }
 
-if [ $# -lt 1 ]; then
-    usage_error '%s: Not enough arguments\n' "$0"
-fi
+script=$(basename "$0")
 
 case "$0" in
     (*/*)
@@ -90,6 +88,10 @@ esac
 script_prefix=${script_dir:+$script_dir/}
 
 . "${script_prefix}oracle-config.sh"
+
+if [ $# -lt 1 ]; then
+    usage_error '%s: Not enough arguments\n' "$script"
+fi
 
 if [ -r $HOME/.env-oracle ]; then
     . $HOME/.env-oracle
diff --git a/docker-run-sap-hana-server b/docker-run-sap-hana-server
--- a/docker-run-sap-hana-server
+++ b/docker-run-sap-hana-server
@@ -24,7 +24,7 @@ abort() {
 }
 
 assert() {
-    "$@" || abort '%s: Assertion failed: %s\n' "$0" "$*"
+    "$@" || abort '%s: Assertion failed: %s\n' "$script" "$*"
 }
 
 docker_run_sap_hana() {
@@ -84,9 +84,7 @@ usage_error() {
     exit 2
 }
 
-if [ $# -lt 1 ]; then
-    usage_error '%s: Not enough arguments\n' "$0"
-fi
+script=$(basename "$0")
 
 case "$0" in
     (*/*)
@@ -100,6 +98,10 @@ esac
 script_prefix=${script_dir:+$script_dir/}
 
 . "${script_prefix}sap-hana-config.sh"
+
+if [ $# -lt 1 ]; then
+    usage_error '%s: Not enough arguments\n' "$script"
+fi
 
 if [ -r $HOME/.env-sap-hana ]; then
     . $HOME/.env-sap-hana
diff --git a/drop-app-database b/drop-app-database
--- a/drop-app-database
+++ b/drop-app-database
@@ -22,11 +22,11 @@ abort() {
 }
 
 abort_not_supported() {
-    abort '%s: %s: %s not supported\n' "$0" "$PRETTY_NAME" "$*"
+    abort '%s: %s: %s not supported\n' "$script" "$PRETTY_NAME" "$*"
 }
 
 assert() {
-    "$@" || abort '%s: Assertion failed: %s\n' "$0" "$*"
+    "$@" || abort '%s: Assertion failed: %s\n' "$script" "$*"
 }
 
 usage_error() {
@@ -34,9 +34,7 @@ usage_error() {
     exit 2
 }
 
-if [ $# -gt 0 ]; then
-    usage_error '%s: Too many arguments\n' "$0"
-fi
+script=$(basename "$0")
 
 case "$0" in
     (*/*)
@@ -50,6 +48,10 @@ esac
 script_prefix=${script_dir:+$script_dir/}
 
 . "${script_prefix}common-functions.sh"
+
+if [ $# -gt 0 ]; then
+    usage_error '%s: Too many arguments\n' "$script"
+fi
 
 set_user_profile "$script_dir"
 manage-app-database drop
diff --git a/generate-env b/generate-env
--- a/generate-env
+++ b/generate-env
@@ -22,7 +22,7 @@ abort() {
 }
 
 assert() {
-    "$@" || abort '%s: Assertion failed: %s\n' "$0" "$*"
+    "$@" || abort '%s: Assertion failed: %s\n' "$script" "$*"
 }
 
 format_dialect() {
@@ -184,7 +184,9 @@ parse_arguments() {
 			dialect=sqlite
 			;;
 		    (*)
-			usage_error '%s: %s: Invalid argument\n' "$0" "$OPTARG"
+			usage_error '%s: %s: Invalid argument\n' \
+				    "$script" \
+				    "$OPTARG"
 			;;
 		esac
 		;;
@@ -206,7 +208,9 @@ parse_arguments() {
 			qualifier=postgres
 			;;
 		    (*)
-			usage_error '%s: %s: Invalid argument\n' "$0" "$OPTARG"
+			usage_error '%s: %s: Invalid argument\n' \
+				    "$script" \
+				    "$OPTARG"
 			;;
 		esac
 		;;
@@ -245,10 +249,10 @@ to_upper() {
 
 usage() {
     cat <<EOF >&2
-Usage: $0 [-D] [-d DIALECT] [-H HOST] [-P PORT] [-p PASSWORD]
+Usage: $script [-D] [-d DIALECT] [-H HOST] [-P PORT] [-p PASSWORD]
        [-q QUALIFIER] [-r ROOT-PASSWORD] [-S SCHEMA] [-s|-t]
        [-u USER]
-       $0 -h
+       $script -h
 EOF
 }
 
@@ -261,6 +265,8 @@ usage_error() {
     usage
     exit 2
 }
+
+script=$(basename "$0")
 
 parse_arguments "$@"
 generate_env
diff --git a/get-install-command b/get-install-command
--- a/get-install-command
+++ b/get-install-command
@@ -22,7 +22,7 @@ abort() {
 }
 
 assert() {
-    "$@" || abort '%s: Assertion failed: %s\n' "$0" "$*"
+    "$@" || abort '%s: Assertion failed: %s\n' "$script" "$*"
 }
 
 get_install_command() {
@@ -51,10 +51,12 @@ usage_error() {
     exit 2
 }
 
+script=$(basename "$0")
+
 if [ $# -lt 1 ]; then
-    usage_error '%s: Not enough arguments\n' "$0"
+    usage_error '%s: Not enough arguments\n' "$script"
 elif [ $# -gt 1 ]; then
-    usage_error '%s: Too many arguments\n' "$0"
+    usage_error '%s: Too many arguments\n' "$script"
 fi
 
 get_install_command "$@"
diff --git a/get-installed-mysql-package b/get-installed-mysql-package
--- a/get-installed-mysql-package
+++ b/get-installed-mysql-package
@@ -22,7 +22,7 @@ abort() {
 }
 
 assert() {
-    "$@" || abort '%s: Assertion failed: %s\n' "$0" "$*"
+    "$@" || abort '%s: Assertion failed: %s\n' "$script" "$*"
 }
 
 get_installed_mysql_package() {
@@ -45,7 +45,7 @@ parse_arguments() {
 	    true
 	    ;;
 	(*)
-	    abort '%s: Invalid argument -- %s\n' "$0" "$1"
+	    abort '%s: Invalid argument -- %s\n' "$script" "$1"
 	    ;;
     esac
 }
@@ -55,11 +55,7 @@ usage_error() {
     exit 2
 }
 
-if [ $# -lt 1 ]; then
-    usage_error '%s: Not enough arguments\n' "$0"
-elif [ $# -gt 1 ]; then
-    usage_error '%s: Too many arguments\n' "$0"
-fi
+script=$(basename "$0")
 
 case "$0" in
     (*/*)
@@ -73,6 +69,12 @@ esac
 script_prefix=${script_dir:+$script_dir/}
 
 . "${script_prefix}common-functions.sh"
+
+if [ $# -lt 1 ]; then
+    usage_error '%s: Not enough arguments\n' "$script"
+elif [ $# -gt 1 ]; then
+    usage_error '%s: Too many arguments\n' "$script"
+fi
 
 set_user_profile "$script_dir"
 parse_arguments "$@"
diff --git a/get-os-release b/get-os-release
--- a/get-os-release
+++ b/get-os-release
@@ -32,11 +32,11 @@ abort() {
 }
 
 assert() {
-    "$@" || abort '%s: Assertion failed: %s\n' "$0" "$*"
+    "$@" || abort '%s: Assertion failed: %s\n' "$script" "$*"
 }
 
 abort_conflicting_option() {
-    usage_error '%s: conflicting option -- %s\n' "$0" "$1"
+    usage_error '%s: conflicting option -- %s\n' "$script" "$1"
 }
 
 collect_data() {
@@ -239,7 +239,7 @@ parse_arguments() {
     shift $(($OPTIND - 1))
 
     if [ $# -gt 0 ]; then
-	usage_error '%s: Too many arguments\n' "$0"
+	usage_error '%s: Too many arguments\n' "$script"
     fi
 }
 
@@ -266,10 +266,10 @@ to_lower() {
 
 usage() {
     cat <<-EOF >&2
-Usage: $0: [-i] [-k] [-n] [-p] [-r] [-v]
-       $0: -x
-       $0: -X
-       $0: -h
+Usage: $script: [-i] [-k] [-n] [-p] [-r] [-v]
+       $script: -x
+       $script: -X
+       $script: -h
 EOF
 }
 
@@ -282,6 +282,8 @@ usage_error() {
     usage
     exit 2
 }
+
+script=$(basename "$0")
 
 case "$0" in
     (*/*)
diff --git a/get-package-filenames b/get-package-filenames
--- a/get-package-filenames
+++ b/get-package-filenames
@@ -22,11 +22,11 @@ abort() {
 }
 
 abort_not_supported() {
-    abort '%s: %s: %s not supported\n' "$0" "$PRETTY_NAME" "$*"
+    abort '%s: %s: %s not supported\n' "$script" "$PRETTY_NAME" "$*"
 }
 
 assert() {
-    "$@" || abort '%s: Assertion failed: %s\n' "$0" "$*"
+    "$@" || abort '%s: Assertion failed: %s\n' "$script" "$*"
 }
 
 get_package_filenames() {
@@ -59,11 +59,7 @@ usage_error() {
     exit 2
 }
 
-if [ $# -lt 1 ]; then
-    usage_error '%s: Not enough arguments\n' "$0"
-elif [ $# -gt 1 ]; then
-    usage_error '%s: Too many arguments\n' "$0"
-fi
+script=$(basename "$0")
 
 case "$0" in
     (*/*)
@@ -75,6 +71,12 @@ case "$0" in
 esac
 
 script_prefix=${script_dir:+$script_dir/}
+
+if [ $# -lt 1 ]; then
+    usage_error '%s: Not enough arguments\n' "$script"
+elif [ $# -gt 1 ]; then
+    usage_error '%s: Too many arguments\n' "$script"
+fi
 
 eval $("${script_prefix}get-os-release" -x)
 get_package_filenames "$@"
diff --git a/git-credential-helper b/git-credential-helper
--- a/git-credential-helper
+++ b/git-credential-helper
@@ -29,11 +29,11 @@ abort() {
 }
 
 abort_not_supported() {
-    abort '%s: %s: %s not supported\n' "$0" "$PRETTY_NAME" "$*"
+    abort '%s: %s: %s not supported\n' "$script" "$PRETTY_NAME" "$*"
 }
 
 assert() {
-    "$@" || abort '%s: Assertion failed: %s\n' "$0" "$*"
+    "$@" || abort '%s: Assertion failed: %s\n' "$script" "$*"
 }
 
 get_helper_binary() {
@@ -165,7 +165,7 @@ parse_arguments() {
     shift $(($OPTIND - 1))
 
     if [ $# -gt 1 ]; then
-	usage_error '%s: Too many arguments\n' "$0"
+	usage_error '%s: Too many arguments\n' "$script"
     elif [ $# -gt 0 ]; then
 	credential_helper=$1
     fi
@@ -190,21 +190,11 @@ query_configured_helper() {
 
 usage() {
     cat <<EOF >&2
-Usage: $0
-       $0 CREDENTIAL_HELPER
-       $0 -h
-       $0 -q
+Usage: $script
+       $script CREDENTIAL_HELPER
+       $script -h
+       $script -q
 EOF
-}
-
-usage_error() {
-    if [ $# -gt 0 ]; then
-	printf "$@" >&2
-    fi
-
-    printf '%s\n' '' >&2
-    usage
-    exit 2
 }
 
 validate_platform() {
@@ -236,6 +226,8 @@ validate_platform() {
 	    ;;
     esac
 }
+
+script=$(basename "$0")
 
 case "$0" in
     (*/*)
