Refactor scripts to use and manage Python virtual environments.

diff --git a/clean-up-pipenv b/clean-up-pipenv
--- a/clean-up-pipenv
+++ b/clean-up-pipenv
@@ -16,17 +16,13 @@
 # You should have received a copy of the GNU General Public License
 # along with this program.  If not, see <https://www.gnu.org/licenses/>.
 
-: ${LANG:=en_US.UTF-8}
-: ${LC_ALL:=en_US.UTF-8}
-export LANG LC_ALL
-
 abort() {
     printf "$@" >&2
     exit 1
 }
 
 assert() {
-    "$@" || abort "%s: Assertion failed: %s\n" "$0" "$*"
+    "$@" || abort '%s: Assertion failed: %s\n' "$script" "$*"
 }
 
 clean_up_pipenv() {
@@ -44,9 +40,7 @@ usage_error() {
     exit 2
 }
 
-if [ $# -gt 0 ]; then
-    usage_error "%s: Too many arguments\n" "$0"
-fi
+script=$(basename "$0")
 
 case "$0" in
     (*/*)
@@ -61,6 +55,13 @@ script_prefix=${script_dir:+$script_dir/}
 
 . "${script_prefix}common-functions.sh"
 . "${script_prefix}utility-functions.sh"
+
+export LANG=${LANG-en_US.UTF-8}
+export LC_ALL=${LC_ALL-en_US.UTF-8}
+
+if [ $# -gt 0 ]; then
+    usage_error "%s: Too many arguments\n" "$script"
+fi
 
 set_user_profile "$script_dir"
 clean_up_pipenv
diff --git a/clean-up-virtualenv b/clean-up-virtualenv
--- a/clean-up-virtualenv
+++ b/clean-up-virtualenv
@@ -22,22 +22,40 @@ abort() {
 }
 
 assert() {
-    "$@" || abort "%s: Assertion failed: %s\n" "$0" "$*"
+    "$@" || abort '%s: Assertion failed: %s\n' "$script" "$*"
 }
 
 clean_up_virtualenv() {
-    run_unpriv "${script_prefix}clean-up-pipenv"
-    /bin/rm -rf ${VENV_DIRECTORY-venv}
+    for utility in ${pypi_utilities:-$PYPI_UTILITIES}; do
+	case "$utility" in
+	    (pipenv)
+		run_unpriv "${script_prefix}clean-up-pipenv"
+		;;
+	    (pip)
+		/bin/rm -rf ${VENV_DIRECTORY-venv}
+		;;
+	esac
+    done
+}
+
+configure_platform() {
+    case "${uname_kernel=$(uname -s)}" in
+	(CYGWIN_NT-*)
+	    pypi_utilities=pip
+	    ;;
+	(MINGW64_NT-*)
+	    pypi_utilities=pip
+	    ;;
+	(*)
+	    pypi_utilities=
+	    ;;
+    esac
 }
 
 usage_error() {
     printf "$@" >&2
     exit 2
 }
-
-if [ $# -gt 0 ]; then
-    usage_error "%s: Too many arguments\n" "$0"
-fi
 
 case "$0" in
     (*/*)
@@ -48,9 +66,16 @@ case "$0" in
 	;;
 esac
 
+script=$(basename "$0")
+
 script_prefix=${script_dir:+$script_dir/}
 
 . "${script_prefix}common-functions.sh"
 
+if [ $# -gt 0 ]; then
+    usage_error "%s: Too many arguments\n" "$script"
+fi
+
 eval $("${script_prefix}get-configuration" app.ini)
+configure_platform
 clean_up_virtualenv
