Fix issues locating scripts and such in clean-up scripts.

diff --git a/clean-app-caches b/clean-app-caches
--- a/clean-app-caches
+++ b/clean-app-caches
@@ -21,16 +21,39 @@ abort() {
     exit 1
 }
 
+assert() {
+    "$@" || abort "%s: Assertion failed: %s\n" "$0" "$*"
+}
+
 find_caches() {
     find . -type d \( -name "$VENV_DIRECTORY" -prune -o \
 	 -name .pytest_cache -print -o \
 	 -name __pycache__ -print \)
 }
 
-if [ "$(id -u)" -eq 0 ]; then
-    abort "%s: Must be run as a non-privileged user\n" "$0"
+get_realpath() (
+    assert [ $# -ge 1 ]
+    realpath=$(which realpath)
+
+    if [ -n "$realpath" ]; then
+	$realpath "$@"
+    else
+	for file; do
+	    if expr "$file" : '/.*' >/dev/null; then
+		printf "%s\n" "$file"
+	    else
+		printf "%s\n" "$PWD/${file#./}"
+	    fi
+	done
+    fi
+)
+
+if [ $# -gt 0 ]; then
+    abort "%s: Too many arguments\n" "$0"
 fi
 
-eval $(get-app-configuration --input app.ini)
+script_dir=$(get_realpath "$(dirname "$0")")
+
+eval $("$script_dir/get-app-configuration" --input app.ini)
 
 /bin/rm -rf $(find_caches)
