Refactor script docker-run-sap-hana with additional shell functions.

diff --git a/docker-run-sap-hana b/docker-run-sap-hana
--- a/docker-run-sap-hana
+++ b/docker-run-sap-hana
@@ -1,20 +1,54 @@
 #!/bin/sh -eu
 
+# docker-run-sap-hana: run SAP HANA database in container
+# Copyright (C) 2020  "Michael G. Morey" <mgmorey@gmail.com>
+
+# This program is free software: you can redistribute it and/or modify
+# it under the terms of the GNU General Public License as published by
+# the Free Software Foundation, either version 3 of the License, or
+# (at your option) any later version.
+
+# This program is distributed in the hope that it will be useful,
+# but WITHOUT ANY WARRANTY; without even the implied warranty of
+# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
+# GNU General Public License for more details.
+
+# You should have received a copy of the GNU General Public License
+# along with this program.  If not, see <https://www.gnu.org/licenses/>.
+
+abort() {
+    printf "$@" >&2
+    exit 1
+}
+
+assert() {
+    "$@" || abort "%s: Assertion failed: %s\n" "$0" "$*"
+}
+
 docker_run_sap_hana() {
-    docker run \
-	   -p 1128-1129:1128-1129 \
-	   -p 39013:39013 \
-	   -p 39017:39017 \
-	   -p 39041-39045:39041-39045 \
-	   -p 59013-59014:59013-59014 \
-	   -v /data/sap-hana:/hana/mounts \
-	   --sysctl kernel.shmall=8388608 \
-	   --sysctl kernel.shmmax=1073741824 \
-	   --sysctl kernel.shmmni=524288 \
-	   --sysctl net.ipv4.ip_local_port_range='40000 60999' \
-	   --ulimit nofile=1048576:1048576 \
-	   $IMAGE:$TAG --agree-to-sap-license \
-	   --passwords-url file:///hana/mounts/$JSONFILE
+    set_options
+    docker run $opts $IMAGE_NAME:$IMAGE_TAG --agree-to-sap-license \
+    	   --passwords-url file:///hana/mounts/$JSON_FILE
+}
+
+parse_arguments() {
+    if [ $# -gt 0 ]; then
+        user_opts="$@"
+    else
+        user_opts="-d"
+    fi
+}
+
+set_options() {
+    port_opts=
+
+    for port in $PORTS; do
+        port_opts="${port_opts:+$port_opts }-p $port:$port"
+    done
+
+    vol_opts="-v $DATADIR:/hana/mounts"
+
+    opts="${port_opts:+$port_opts }${vol_opts:+$vol_opts }$user_opts"
 }
 
 script_basename="$(basename "$0")"
@@ -22,4 +56,9 @@ script_dirname="$(realpath "$(dirname "$0")")"
 
 . "$script_dirname/sap-hana-config.sh"
 
+if [ -r $ENV_FILE ]; then
+    . $ENV_FILE
+fi
+
+parse_arguments "$@"
 docker_run_sap_hana
