Refactor scripts to install/restart/start/stop/uninstall Flask apps.

diff --git a/docker-app b/docker-app
--- a/docker-app
+++ b/docker-app
@@ -25,19 +25,19 @@ abort() {
 }
 
 assert() {
-    "$@" || abort "%s: Assertion failed: %s\n" "$0" "$*"
+    "$@" || abort '%s: Assertion failed: %s\n' "$script" "$*"
 }
 
 get_all_parameters() {
-    printf "%s\n" $UPPER_PARAMETERS $LOWER_PARAMETERS
+    printf '%s\n' $UPPER_PARAMETERS $LOWER_PARAMETERS
 }
 
 get_default_remote_image() {
-    printf "%s\n" "${DOCKER_USERNAME-$(get_real_user)}/$APP_NAME"
+    printf '%s\n' "${DOCKER_USERNAME-$(get_real_user)}/$APP_NAME"
 }
 
 get_default_run_options() {
-    printf "%s\n" -dp $APP_PORT:$APP_PORT --rm
+    printf '%s\n' -dp $APP_PORT:$APP_PORT --rm
 }
 
 get_default_tag() {
@@ -85,7 +85,7 @@ docker_app() {
 	    docker run ${run_opts+$run_opts }$image${tag:+:$tag}
 	    ;;
 	(*)
-	    usage_error "%s: invalid argument -- %s\n" "$0" "$1"
+	    usage_error "%s: invalid argument -- %s\n" "$script" "$1"
 	    ;;
     esac
 }
@@ -117,9 +117,9 @@ parse_arguments() {
     shift $(($OPTIND - 1))
 
     if [ $# -lt 1 ]; then
-	usage_error "%s: Not enough arguments\n" "$0"
+	usage_error '%s: Not enough arguments\n' "$script"
     elif [ $# -gt 1 ]; then
-	usage_error "%s: Too many arguments\n" "$0"
+	usage_error '%s: Too many arguments\n' "$script"
     fi
 
     action="$1"
@@ -127,9 +127,9 @@ parse_arguments() {
 
 usage() {
     cat <<EOF >&2
-Usage: $0 [-t TAG] pull
-       $0 [-t TAG] push
-       $0 [-t TAG] tag
+Usage: $script [-t TAG] pull
+       $script [-t TAG] push
+       $script [-t TAG] tag
 EOF
 }
 
@@ -138,10 +138,12 @@ usage_error() {
 	printf "$@" >&2
     fi
 
-    printf "%s\n" '' >&2
+    printf '%s\n' '' >&2
     usage
     exit 2
 }
+
+script=$(basename "$0")
 
 case "$0" in
     (*/*)
diff --git a/install-app b/install-app
--- a/install-app
+++ b/install-app
@@ -24,18 +24,18 @@ abort() {
 }
 
 assert() {
-    "$@" || abort "%s: Assertion failed: %s\n" "$0" "$*"
+    "$@" || abort '%s: Assertion failed: %s\n' "$script" "$*"
 }
 
 build_uwsgi_from_source() {
     if ! run_unpriv /bin/sh -c "\"build-uwsgi\" $*"; then
-	abort "%s: Unable to build uWSGI\n" "$0"
+	abort '%s: Unable to build uWSGI\n' "$script"
     fi
 }
 
 change_owner() (
     assert [ $# -ge 1 ]
-    dirs=$(printf "%s\n" "$@" | sort -u)
+    dirs=$(printf '%s\n' "$@" | sort -u)
 
     if [ "$(id -u)" -gt 0 ]; then
 	return 0
@@ -46,19 +46,19 @@ change_owner() (
     if [ $dryrun = true ]; then
 	check_permissions $dirs
     else
-	printf "Changing ownership of directory %s\n" $dirs
+	printf 'Changing ownership of directory %s\n' $dirs
 	chown -R "$APP_UID:$APP_GID" $dirs
     fi
 )
 
 create_dirs() (
     assert [ $# -ge 1 ]
-    dirs=$(printf "%s\n" "$@" | sort -u)
+    dirs=$(printf '%s\n' "$@" | sort -u)
 
     if [ $dryrun = true ]; then
 	check_permissions $dirs
     else
-	printf "Creating directory %s\n" $dirs
+	printf 'Creating directory %s\n' $dirs
 	mkdir -p $dirs
     fi
 )
@@ -176,7 +176,7 @@ install_app_files() (
 
 install_dependencies() {
     if ! install-python-build-deps; then
-	abort "%s: Unable to install dependencies\n" "$0"
+	abort '%s: Unable to install dependencies\n' "$script"
     fi
 }
 
@@ -228,7 +228,7 @@ install_virtualenv() (
     if [ $dryrun = true ]; then
 	check_permissions_single "$1"
     else
-	printf "Installing virtual environment in %s\n" "$1" >&2
+	printf 'Installing virtual environment in %s\n' "$1" >&2
 	pip_install_files=$PIP_INSTALL_MAIN
 	venv_force_sync=true
 	refresh_via_pip $1 $SYSTEM_PYTHON
@@ -270,14 +270,14 @@ print_status() {
     case "$1" in
 	(running)
 	    print_app_processes 1
-	    printf "Service %s installed and started successfully\n" "$APP_NAME"
+	    printf 'Service %s installed and started successfully\n' "$APP_NAME"
 	    print_elapsed_time started
 	    ;;
 	(stopped)
-	    printf "Service %s installed successfully\n" "$APP_NAME"
+	    printf 'Service %s installed successfully\n' "$APP_NAME"
 	    ;;
 	(*)
-	    printf "Service %s is %s\n" "$APP_NAME" "$1" >&2
+	    printf 'Service %s is %s\n' "$APP_NAME" "$1" >&2
 	    ;;
     esac
 }
@@ -291,8 +291,8 @@ run_in_virtualenv() (
 
 usage() {
     cat <<EOF >&2
-Usage: $0: [-v <VENV-UTILITIES>]
-       $0: -h
+Usage: $script: [-v <VENV-UTILITIES>]
+       $script: -h
 EOF
 }
 
@@ -301,10 +301,12 @@ usage_error() {
 	printf "$@" >&2
     fi
 
-    printf "%s\n" '' >&2
+    printf '%s\n' '' >&2
     usage
     exit 2
 }
+
+script=$(basename "$0")
 
 case "$0" in
     (*/*)
diff --git a/run-app b/run-app
--- a/run-app
+++ b/run-app
@@ -33,7 +33,7 @@ abort() {
 }
 
 assert() {
-    "$@" || abort "%s: Assertion failed: %s\n" "$0" "$*"
+    "$@" || abort '%s: Assertion failed: %s\n' "$script" "$*"
 }
 
 export_parameters() {
@@ -65,7 +65,7 @@ run_app() {
     elif [ -n "$pip" ]; then
 	run_via_pip "$@"
     else
-	abort "%s: Neither pip nor pipenv command found in PATH\n" "$0"
+	abort '%s: Neither pip nor pipenv command found in PATH\n' "$script"
     fi
 }
 
@@ -99,12 +99,14 @@ run_via_pipenv() {
 }
 
 if [ $# -lt 1 ]; then
-    abort "%s: Not enough arguments\n" "$0"
+    abort '%s: Not enough arguments\n' "$script"
 fi
 
 if [ "$(id -u)" -eq 0 ]; then
-    abort "%s: Must be run as a non-privileged user\n" "$0"
+    abort '%s: Must be run as a non-privileged user\n' "$script"
 fi
+
+script=$(basename "$0")
 
 case "$0" in
     (*/*)
diff --git a/start-app b/start-app
--- a/start-app
+++ b/start-app
@@ -19,7 +19,7 @@ abort() {
 }
 
 assert() {
-    "$@" || abort "%s: Assertion failed: %s\n" "$0" "$*"
+    "$@" || abort '%s: Assertion failed: %s\n' "$script" "$*"
 }
 
 control_app_enable() {
@@ -33,7 +33,7 @@ control_app_start() {
 	return 0
     fi
 
-    printf "Waiting for service %s to start\n" "$APP_NAME"
+    printf 'Waiting for service %s to start\n' "$APP_NAME"
     elapsed=$((elapsed + $(wait_for_service $((WAIT_RESTART - elapsed)))))
 
     if [ $elapsed -lt $WAIT_DEFAULT ]; then
@@ -52,7 +52,7 @@ create_symlink() {
 	assert [ -r $1 ]
 
 	if [ $1 != $2 -a ! -e $2 ]; then
-	    printf "Creating link %s\n" "$2"
+	    printf 'Creating link %s\n' "$2"
 	    mkdir -p $(dirname $2)
 	    /bin/ln -s $1 $2
 	fi
@@ -111,7 +111,7 @@ print_status() (
 	    ;;
     esac
 
-    printf "Service %s is %s\n" "$APP_NAME" "$status"
+    printf 'Service %s is %s\n' "$APP_NAME" "$status"
 )
 
 run_service() {
@@ -146,6 +146,8 @@ start_app() {
 	run_service
     fi
 }
+
+script=$(basename "$0")
 
 case "$0" in
     (*/*)
diff --git a/stop-app b/stop-app
--- a/stop-app
+++ b/stop-app
@@ -19,7 +19,7 @@ abort() {
 }
 
 assert() {
-    "$@" || abort "%s: Assertion failed: %s\n" "$0" "$*"
+    "$@" || abort '%s: Assertion failed: %s\n' "$script" "$*"
 }
 
 control_app_disable() {
@@ -44,7 +44,7 @@ print_status() (
 	    ;;
     esac
 
-    printf "Service %s is %s\n" "$APP_NAME" "$status"
+    printf 'Service %s is %s\n' "$APP_NAME" "$status"
 )
 
 stop_app() {
@@ -53,6 +53,8 @@ stop_app() {
 	control_app_stop
     done
 }
+
+script=$(basename "$0")
 
 case "$0" in
     (*/*)
diff --git a/uninstall-app b/uninstall-app
--- a/uninstall-app
+++ b/uninstall-app
@@ -19,7 +19,7 @@ abort() {
 }
 
 assert() {
-    "$@" || abort "%s: Assertion failed: %s\n" "$0" "$*"
+    "$@" || abort '%s: Assertion failed: %s\n' "$script" "$*"
 }
 
 parse_arguments() {
@@ -43,7 +43,7 @@ parse_arguments() {
     shift $(($OPTIND - 1))
 
     if [ $# -gt 0 ]; then
-	usage_error "%s: Too many arguments\n" "$0"
+	usage_error "%s: Too many arguments\n" "$script"
     fi
 }
 
@@ -81,12 +81,12 @@ uninstall_app() {
 	remove_service
     done
 
-    printf "Service %s uninstalled successfully\n" $APP_NAME
+    printf 'Service %s uninstalled successfully\n' $APP_NAME
 }
 
 usage() {
     cat <<EOF >&2
-Usage: $0: [-h] [-p]
+Usage: $script: [-h] [-p]
 EOF
 }
 
@@ -95,10 +95,12 @@ usage_error() {
 	printf "$@" >&2
     fi
 
-    printf "%s\n" '' >&2
+    printf '%s\n' '' >&2
     usage
     exit 2
 }
+
+script=$(basename "$0")
 
 case "$0" in
     (*/*)
