Refactor to utilize script get-os-release to get distro name, etc.

diff --git a/enable-sudo b/enable-sudo
--- a/enable-sudo
+++ b/enable-sudo
@@ -23,24 +23,40 @@ abort() {
     exit 1
 }
 
-system_name="$(uname -s)"
+assert() {
+    "$@" || abort "%s: Assertion failed: %s\n" "$0" "$*"
+}
+
+realpath() {
+    assert [ -d "$1" ]
+
+    if [ -x /usr/bin/realpath ]; then
+	/usr/bin/realpath "$1"
+    else
+	if expr "$1" : '/.*' >/dev/null; then
+	    printf "%s\n" "$1"
+	else
+	    printf "%s\n" "$PWD/${1#./}"
+	fi
+    fi
+}
+
+script_dir=$(realpath "$(dirname "$0")")
+
+distro_name=$(sh -eu $script_dir/get-os-release -i)
+kernel_name=$(sh -eu $script_dir/get-os-release -k)
 pretty_name=$(sh -eu $script_dir/get-os-release -p)
 
-case "$system_name" in
+case "$kernel_name" in
     (Linux)
-	if [ -r /etc/os-release ]; then
-	    . /etc/os-release
-	    case "$ID" in
-		(debian|ubuntu)
-		    su -c "apt-get install $DEBIAN_PKGS"
-		    ;;
-		(*)
-		    abort "%s: Distro not supported\n" "$pretty_name"
-		    ;;
-	    esac
-	else
-	    abort "Distro not supported\n"
-	fi
+	case "$distro_name" in
+	    (debian|ubuntu)
+		su -c "apt-get install $DEBIAN_PKGS"
+		;;
+	    (*)
+		abort "%s: Distro not supported\n" "$pretty_name"
+		;;
+	esac
 	;;
     (*)
 	abort "%s: Operating system not supported\n" "$pretty_name"
@@ -48,5 +64,5 @@ case "$system_name" in
 esac
 
 if su -c "usermod -a -G sudo $USER"; then
-    printf "Please restart before using sudo\n"
+    printf "Please restart machine before using sudo\n"
 fi
