Refactor scripts to use new script get-os-release-filenames.

diff --git a/get-os-release-name b/get-os-release-name
--- a/get-os-release-name
+++ b/get-os-release-name
@@ -16,39 +16,60 @@
 # You should have received a copy of the GNU General Public License
 # along with this program.  If not, see <https://www.gnu.org/licenses/>.
 
-KEYS="os centos fedora redhat system"
+abort() {
+    printf "$@" >&2
+    exit 1
+}
 
+assert() {
+    "$@" || abort "%s: Assertion failed: %s\n" "$0" "$*"
+}
+
+realpath() {
+    assert [ -d "$1" ]
+
+    if [ -x /usr/bin/realpath ]; then
+	/usr/bin/realpath "$1"
+    else
+	if expr "$1" : '/.*' >/dev/null; then
+	    printf "%s\n" "$1"
+	else
+	    printf "%s\n" "$PWD/${1#./}"
+	fi
+    fi
+}
+
+script_dir=$(realpath "$(dirname "$0")")
 system_name="$(uname -s)"
 
 case "$system_name" in
     (Linux)
-	for key in $KEYS; do
-	    file=/etc/$key-release
+	files=$(sh -eu $script_dir/get-os-release-filenames)
+	eval set -- $files
+	file=$1
 
-	    if [ -r $file ]; then
-		case ${file#/etc/} in
-		    (os-release)
-			if . $file && [ -n "${VERSION_ID:-}" ]; then
-			    printf "%s\n" "$VERSION_ID"
-			    exit 0
-			elif [ -x /usr/bin/lsb_release ]; then
-			    /usr/bin/lsb_release -rs
-			    exit 0
-			else
-			    exit 1
-			fi
-			;;
-		    (*-release)
-			awk '{print $4}' $file
+	if [ -r $file ]; then
+	    case ${file#/etc/} in
+		(lsb-release)
+		    if . $file && [ -n "${DISTRIB_RELEASE:-}" ]; then
+			printf "%s\n" "$DISTRIB_RELEASE"
 			exit 0
-			;;
-		esac
-	    fi
-	done
-
-	if [ -x /usr/bin/lsb_release ]; then
-	    /usr/bin/lsb_release -rs
+		    fi
+		    ;;
+		(os-release)
+		    if . $file && [ -n "${VERSION_ID:-}" ]; then
+			printf "%s\n" "$VERSION_ID"
+			exit 0
+		    fi
+		    ;;
+		(*-release)
+		    awk '{print $4}' $file
+		    exit 0
+		    ;;
+	    esac
 	fi
+
+	lsb_release -rs
 	;;
     (Darwin|FreeBSD|GNU|Minix)
 	uname -r
