Refactor scripts to use new script get-os-release-filenames.

diff --git a/get-os-pretty-name b/get-os-pretty-name
--- a/get-os-pretty-name
+++ b/get-os-pretty-name
@@ -16,32 +16,50 @@
 # You should have received a copy of the GNU General Public License
 # along with this program.  If not, see <https://www.gnu.org/licenses/>.
 
-KEYS="os centos fedora redhat system"
+abort() {
+    printf "$@" >&2
+    exit 1
+}
 
+assert() {
+    "$@" || abort "%s: Assertion failed: %s\n" "$0" "$*"
+}
+
+realpath() {
+    assert [ -d "$1" ]
+
+    if [ -x /usr/bin/realpath ]; then
+	/usr/bin/realpath "$1"
+    else
+	if expr "$1" : '/.*' >/dev/null; then
+	    printf "%s\n" "$1"
+	else
+	    printf "%s\n" "$PWD/${1#./}"
+	fi
+    fi
+}
+
+script_dir=$(realpath "$(dirname "$0")")
 system_name="$(uname -s)"
 
 case "$system_name" in
     (Linux)
-	for key in $KEYS; do
-	    file=/etc/$key-release
+	files=$(sh -eu $script_dir/get-os-release-filenames)
+	eval set -- $files
+	file=$1
 
-	    if [ -r $file ]; then
-		case ${file#/etc/} in
-		    (os-release)
-			 (. $file && printf "%s\n" "$PRETTY_NAME")
-			exit 0
-			;;
-		    (*-release)
-			awk '{print $1}' $file
-			exit 0
-			;;
-		esac
-	    fi
-	done
-
-	if [ -x /usr/bin/lsb_release ]; then
-	    /usr/bin/lsb_release -ds
-	fi
+	case ${file#/etc/} in
+	    (os-release)
+		if . $file && [ -n "${ID:-}" ]; then
+		    printf "%s\n" "$PRETTY_NAME"
+		    exit 0
+		fi
+		;;
+	    (*-release)
+		awk '{print $1}' $file
+		exit 0
+		;;
+	esac
 	;;
     (GNU|Darwin|FreeBSD)
 	printf "%s\n" "$(uname -sr)"
