Fix handling of source directory containing spaces.

diff --git a/get-package-filenames b/get-package-filenames
--- a/get-package-filenames
+++ b/get-package-filenames
@@ -23,6 +23,24 @@ abort() {
     exit 1
 }
 
+assert() {
+    "$@" || abort "%s: Assertion failed: %s\n" "$0" "$*"
+}
+
+realpath() {
+    assert [ -d "$1" ]
+
+    if [ -x /usr/bin/realpath ]; then
+	/usr/bin/realpath "$1"
+    else
+	if expr "$1" : '/.*' >/dev/null; then
+	    printf "%s\n" "$1"
+	else
+	    printf "%s\n" "$PWD/${1#./}"
+	fi
+    fi
+}
+
 realpath() {
     if [ -x /usr/bin/realpath ]; then
 	/usr/bin/realpath "$@"
@@ -35,9 +53,9 @@ realpath() {
     fi
 }
 
-script_dir=$(realpath $(dirname $0))
-distro_name=$(sh -eu "$script_dir/get-os-distro-name")
-kernel_name=$(sh -eu "$script_dir/get-os-kernel-name")
+script_dir=$(realpath "$(dirname "$0")")
+distro_name=$(sh -eu $script_dir/get-os-distro-name)
+kernel_name=$(sh -eu $script_dir/get-os-kernel-name)
 
 if [ $# -eq 0 ]; then
     abort "Not enough arguments\n"
diff --git a/get-package-install-options b/get-package-install-options
--- a/get-package-install-options
+++ b/get-package-install-options
@@ -16,6 +16,29 @@
 # You should have received a copy of the GNU General Public License
 # along with this program.  If not, see <https://www.gnu.org/licenses/>.
 
+abort() {
+    printf "$@" >&2
+    exit 1
+}
+
+assert() {
+    "$@" || abort "%s: Assertion failed: %s\n" "$0" "$*"
+}
+
+realpath() {
+    assert [ -d "$1" ]
+
+    if [ -x /usr/bin/realpath ]; then
+	/usr/bin/realpath "$1"
+    else
+	if expr "$1" : '/.*' >/dev/null; then
+	    printf "%s\n" "$1"
+	else
+	    printf "%s\n" "$PWD/${1#./}"
+	fi
+    fi
+}
+
 realpath() {
     if [ -x /usr/bin/realpath ]; then
 	/usr/bin/realpath "$@"
@@ -28,9 +51,9 @@ realpath() {
     fi
 }
 
-script_dir=$(realpath $(dirname $0))
-distro_name=$(sh -eu "$script_dir/get-os-distro-name")
-kernel_name=$(sh -eu "$script_dir/get-os-kernel-name")
+script_dir=$(realpath "$(dirname "$0")")
+distro_name=$(sh -eu $script_dir/get-os-distro-name)
+kernel_name=$(sh -eu $script_dir/get-os-kernel-name)
 
 case "$kernel_name" in
     (Linux)
diff --git a/get-python-package b/get-python-package
--- a/get-python-package
+++ b/get-python-package
@@ -32,6 +32,29 @@ SUNOS_INFO="python-34 34"
 
 UBUNTU_INFO="python3 python3"
 
+abort() {
+    printf "$@" >&2
+    exit 1
+}
+
+assert() {
+    "$@" || abort "%s: Assertion failed: %s\n" "$0" "$*"
+}
+
+realpath() {
+    assert [ -d "$1" ]
+
+    if [ -x /usr/bin/realpath ]; then
+	/usr/bin/realpath "$1"
+    else
+	if expr "$1" : '/.*' >/dev/null; then
+	    printf "%s\n" "$1"
+	else
+	    printf "%s\n" "$PWD/${1#./}"
+	fi
+    fi
+}
+
 realpath() {
     if [ -x /usr/bin/realpath ]; then
 	/usr/bin/realpath "$@"
@@ -44,9 +67,9 @@ realpath() {
     fi
 }
 
-script_dir=$(realpath $(dirname $0))
-distro_name=$(sh -eu "$script_dir/get-os-distro-name")
-kernel_name=$(sh -eu "$script_dir/get-os-kernel-name")
+script_dir=$(realpath "$(dirname "$0")")
+distro_name=$(sh -eu $script_dir/get-os-distro-name)
+kernel_name=$(sh -eu $script_dir/get-os-kernel-name)
 
 case "$kernel_name" in
     (Linux)
diff --git a/get-python3-build-extras b/get-python3-build-extras
--- a/get-python3-build-extras
+++ b/get-python3-build-extras
@@ -39,6 +39,29 @@ readline-devel sqlite-devel"
 
 SUNOS_PKGS="build-essential pip-%s"
 
+abort() {
+    printf "$@" >&2
+    exit 1
+}
+
+assert() {
+    "$@" || abort "%s: Assertion failed: %s\n" "$0" "$*"
+}
+
+realpath() {
+    assert [ -d "$1" ]
+
+    if [ -x /usr/bin/realpath ]; then
+	/usr/bin/realpath "$1"
+    else
+	if expr "$1" : '/.*' >/dev/null; then
+	    printf "%s\n" "$1"
+	else
+	    printf "%s\n" "$PWD/${1#./}"
+	fi
+    fi
+}
+
 realpath() {
     if [ -x /usr/bin/realpath ]; then
 	/usr/bin/realpath "$@"
@@ -51,9 +74,9 @@ realpath() {
     fi
 }
 
-script_dir=$(realpath $(dirname $0))
-distro_name=$(sh -eu "$script_dir/get-os-distro-name")
-kernel_name=$(sh -eu "$script_dir/get-os-kernel-name")
+script_dir=$(realpath "$(dirname "$0")")
+distro_name=$(sh -eu $script_dir/get-os-distro-name)
+kernel_name=$(sh -eu $script_dir/get-os-kernel-name)
 
 case "$kernel_name" in
     (Linux)
@@ -80,7 +103,7 @@ case "$kernel_name" in
 	;;
 esac
 
-data=$(sh -eu "$script_dir/get-python-package")
+data=$(sh -eu $script_dir/get-python-package)
 package_name=$(printf "%s" "$data" | awk '{print $1}')
 package_modifier=$(printf "%s" "$data" | awk '{print $2}')
 
diff --git a/git-credential-helper b/git-credential-helper
--- a/git-credential-helper
+++ b/git-credential-helper
@@ -25,6 +25,10 @@ abort() {
     exit 1
 }
 
+assert() {
+    "$@" || abort "%s: Assertion failed: %s\n" "$0" "$*"
+}
+
 get_helper() {
     $sh -c "git config --global --get credential.helper"
 }
@@ -94,6 +98,20 @@ query_helpers() {
 }
 
 realpath() {
+    assert [ -d "$1" ]
+
+    if [ -x /usr/bin/realpath ]; then
+	/usr/bin/realpath "$1"
+    else
+	if expr "$1" : '/.*' >/dev/null; then
+	    printf "%s\n" "$1"
+	else
+	    printf "%s\n" "$PWD/${1#./}"
+	fi
+    fi
+}
+
+realpath() {
     if [ -x /usr/bin/realpath ]; then
 	/usr/bin/realpath "$@"
     else
@@ -105,10 +123,10 @@ realpath() {
     fi
 }
 
-script_dir=$(realpath $(dirname $0))
-distro_name=$(sh -eu "$script_dir/get-os-distro-name")
-kernel_name=$(sh -eu "$script_dir/get-os-kernel-name")
-pretty_name=$(sh -eu "$script_dir/get-os-pretty-name")
+script_dir=$(realpath "$(dirname "$0")")
+distro_name=$(sh -eu $script_dir/get-os-distro-name)
+kernel_name=$(sh -eu $script_dir/get-os-kernel-name)
+pretty_name=$(sh -eu $script_dir/get-os-pretty-name)
 
 if [ "$(id -u)" -eq 0 ]; then
     sh="su $SUDO_USER"
diff --git a/install-pyenv b/install-pyenv
--- a/install-pyenv
+++ b/install-pyenv
@@ -18,6 +18,29 @@
 
 BASE_URL=https://github.com/pyenv
 
+abort() {
+    printf "$@" >&2
+    exit 1
+}
+
+assert() {
+    "$@" || abort "%s: Assertion failed: %s\n" "$0" "$*"
+}
+
+realpath() {
+    assert [ -d "$1" ]
+
+    if [ -x /usr/bin/realpath ]; then
+	/usr/bin/realpath "$1"
+    else
+	if expr "$1" : '/.*' >/dev/null; then
+	    printf "%s\n" "$1"
+	else
+	    printf "%s\n" "$PWD/${1#./}"
+	fi
+    fi
+}
+
 realpath() {
     if [ -x /usr/bin/realpath ]; then
 	/usr/bin/realpath "$@"
@@ -36,6 +59,6 @@ else
     sh="sh"
 fi
 
-script_dir=$(realpath $(dirname $0))
+script_dir=$(realpath "$(dirname "$0")")
 $script_dir/install-python3-build-extras || true
 $sh -c "curl -L $BASE_URL/pyenv-installer/raw/master/bin/pyenv-installer | bash"
diff --git a/install-python3-build-extras b/install-python3-build-extras
--- a/install-python3-build-extras
+++ b/install-python3-build-extras
@@ -21,6 +21,24 @@ abort() {
     exit 1
 }
 
+assert() {
+    "$@" || abort "%s: Assertion failed: %s\n" "$0" "$*"
+}
+
+realpath() {
+    assert [ -d "$1" ]
+
+    if [ -x /usr/bin/realpath ]; then
+	/usr/bin/realpath "$1"
+    else
+	if expr "$1" : '/.*' >/dev/null; then
+	    printf "%s\n" "$1"
+	else
+	    printf "%s\n" "$PWD/${1#./}"
+	fi
+    fi
+}
+
 realpath() {
     if [ -x /usr/bin/realpath ]; then
 	/usr/bin/realpath "$@"
@@ -33,12 +51,12 @@ realpath() {
     fi
 }
 
-script_dir=$(realpath $(dirname $0))
-distro_name=$(sh -eu "$script_dir/get-os-distro-name")
-kernel_name=$(sh -eu "$script_dir/get-os-kernel-name")
-package_install_options=$(sh -eu "$script_dir/get-package-install-options")
-package_manager=$(sh -eu "$script_dir/get-package-manager")
-packages=$(sh -eu "$script_dir/get-python3-build-extras")
+script_dir=$(realpath "$(dirname "$0")")
+distro_name=$(sh -eu $script_dir/get-os-distro-name)
+kernel_name=$(sh -eu $script_dir/get-os-kernel-name)
+package_install_options=$(sh -eu $script_dir/get-package-install-options)
+package_manager=$(sh -eu $script_dir/get-package-manager)
+packages=$(sh -eu $script_dir/get-python3-build-extras)
 
 case "$kernel_name" in
     (Linux)
