Refactor scripts install-root-scripts and install-scripts.

diff --git a/install-root-scripts b/install-root-scripts
--- a/install-root-scripts
+++ b/install-root-scripts
@@ -25,7 +25,7 @@ abort() {
 }
 
 assert() {
-    "$@" || abort "%s: Assertion failed: %s\n" "$0" "$*"
+    "$@" || abort "%s: Assertion failed: %s\n" "$script" "$*"
 }
 
 get_install_command() {
@@ -38,16 +38,6 @@ get_install_command() {
 	    ;;
     esac
 }
-
-get_realpath() (
-    for file; do
-	if expr "$file" : '/.*' >/dev/null; then
-	    printf "%s\n" "$file"
-	else
-	    printf "%s\n" "$PWD/${file#./}"
-	fi
-    done
-)
 
 get_script_files() {
     assert [ $# -eq 1 ]
@@ -82,23 +72,26 @@ install_script_files() {
 }
 
 install_root_scripts() {
-    source_dir=$(get_realpath "$(pwd)")
+    source_dir=$(pwd)
 
-    case "$(basename "$source_dir")" in
-	(scripts|*-scripts)
-	    true
-	    ;;
-	(*)
-	    abort "%s: Please change to the source directory and try again\n" "$0"
-	    ;;
-    esac
+    if ! is_valid_script_dirname "$source_dir"; then
+	abort "%s: %s\n" \
+	      "Please change to the source directory and try again" \
+	      "$script"
+    fi
 
+    target_dir=$(cd "$target_dir" && pwd)
+    mkdir -p "$target_dir"
     install_script_files
+}
+
+is_valid_script_dirname() {
+    expr "${1-}" : '/..*/\(scripts\|..*-scripts\)$' >/dev/null
 }
 
 parse_arguments() {
     if [ $# -gt 1 ]; then
-	usage_error "%s: Too many arguments\n" "$0"
+	usage_error "%s: Too many arguments\n" "$script"
     fi
 
     if [ $# -gt 0 ]; then
@@ -112,6 +105,8 @@ usage_error() {
     printf "$@" >&2
     exit 2
 }
+
+script=$(basename "$0")
 
 case "$0" in
     (*/*)
diff --git a/install-scripts b/install-scripts
--- a/install-scripts
+++ b/install-scripts
@@ -26,7 +26,7 @@ abort() {
 }
 
 assert() {
-    "$@" || abort "%s: Assertion failed: %s\n" "$0" "$*"
+    "$@" || abort "%s: Assertion failed: %s\n" "$script" "$*"
 }
 
 configure_platform() {
@@ -68,16 +68,6 @@ get_library_files() {
 	 -print0
 }
 
-get_realpath() (
-    for file; do
-	if expr "$file" : '/.*' >/dev/null; then
-	    printf "%s\n" "$file"
-	else
-	    printf "%s\n" "$PWD/${file#./}"
-	fi
-    done
-)
-
 get_script_files() {
     assert [ $# -eq 1 ]
     assert [ -n "$1" ]
@@ -87,7 +77,7 @@ get_script_files() {
 	 ! -name README \
 	 ! -name get-python-interpreter \
 	 ! -name run-python \
-	 ! -name "$(basename "$0")" \
+	 ! -name "$script" \
 	 ! -name '*.*' \
 	 ! -name '*~' \
 	 -type f \
@@ -95,7 +85,6 @@ get_script_files() {
 }
 
 install_files() {
-    target_dir=$(get_realpath "$target_dir")
     xargs -0 "${script_prefix}install-files" -M $method ${mode:+-m $mode }"$target_dir"
 }
 
@@ -123,21 +112,23 @@ install_scripts() {
     configure_platform
     real_user=$(get_real_user)
     validate_user_name $real_user
-    source_dir=$(get_realpath "$(pwd)")
+    source_dir=$(pwd)
 
-    case "$(basename "$source_dir")" in
-	(scripts|*-scripts)
-	    true
-	    ;;
-	(*)
-	    abort "%s: Please change to the source directory and try again\n" "$0"
-	    ;;
-    esac
+    if ! is_valid_script_dirname "$source_dir"; then
+	abort "%s: %s\n" \
+	      "Please change to the source directory and try again" \
+	      "$script"
+    fi
 
+    target_dir=$(cd "$target_dir" && pwd)
     mkdir -p "$target_dir"
     install_library_files
     install_script_files
     remove_broken_links
+}
+
+is_valid_script_dirname() {
+    expr "${1-}" : '/..*/\(scripts\|..*-scripts\)$' >/dev/null
 }
 
 parse_arguments() {
@@ -167,7 +158,7 @@ parse_arguments() {
     shift $(($OPTIND - 1))
 
     if [ $# -gt 1 ]; then
-	usage_error "%s: Too many arguments\n" "$0"
+	usage_error "%s: Too many arguments\n" "$script"
     fi
 
     if [ $# -gt 0 ]; then
@@ -189,8 +180,8 @@ remove_broken_links() {
 
 usage() {
     cat <<EOF >&2
-Usage: $0 [-c | -i | -s] [TARGET]
-       $0 -h
+Usage: $script [-c | -i | -s] [TARGET]
+       $script -h
 EOF
 }
 
@@ -203,6 +194,8 @@ usage_error() {
     usage
     exit 2
 }
+
+script=$(basename "$0")
 
 case "$0" in
     (*/*)
