Port script install-mysql-odbc to Oracle Linux 8.1.

diff --git a/install-mysql-odbc b/install-mysql-odbc
--- a/install-mysql-odbc
+++ b/install-mysql-odbc
@@ -56,39 +56,81 @@ get_realpath() (
 
 install_mysql_odbc() {
     validate_platform
-    install-packages libodbc1
-    prefix=/opt/$package
+    install-packages $(get-odbc-packages)
 
-    if [ ! -d $prefix ]; then
-	tar -C /opt -xf $tarpath
-	/bin/mv -f /opt/$dirname /opt/$package
-    fi
+    case "$ID" in
+	(debian|ubuntu)
+	    prefix=/opt/$package
 
-    chown -R root:root $prefix
+	    if [ ! -d $prefix ]; then
+		tar -C /opt -xf $tarpath
+		/bin/mv -f /opt/$dirname /opt/$package
+	    fi
 
-    for encoding in ANSI UNICODE; do
-	eval name="\$NAME_$encoding"
-	eval object="\$OBJECT_$encoding"
-	driver=$prefix/lib/$object
-	$prefix/bin/myodbc-installer -r -d -n "$name"
-	$prefix/bin/myodbc-installer -a -d -n "$name" -t Driver="$driver"
-    done
+	    chown -R root:root $prefix
 
-    for file in $prefix/bin/*; do
-	ln -sf $file /usr/local/bin
-    done
+	    for encoding in ANSI UNICODE; do
+		eval name="\$NAME_$encoding"
+		eval object="\$OBJECT_$encoding"
+		driver=$prefix/lib/$object
+		$prefix/bin/myodbc-installer -r -d -n "$name"
+		$prefix/bin/myodbc-installer -a -d -n "$name" -t Driver="$driver"
+	    done
+
+	    for file in $prefix/bin/*; do
+		ln -sf $file /usr/local/bin
+	    done
+	    ;;
+	(rhel|ol)
+	    if ! rpm -q $PKG_NAME >/dev/null 2>&1; then
+		rpm -ihv $rpmpath
+	    fi
+	    ;;
+    esac
 }
 
 parse_arguments() {
-    case "$1" in
-	(*/$PKG_NAME-8.0.*-linux-$ID$VERSION_ID-x86-64bit.tar.gz)
-	    tarpath=$1
-            tarfile=$(basename $tarpath)
-	    dirname=${tarfile%.tar.gz}
-	    package=${dirname%-linux-*-x86-64bit}
+    case "$ID" in
+	(rhel|ol)
+	    case "$VERSION_ID" in
+		(7.*)
+		    rpmfile=${PKG_NAME}-8.0.*-*.el7.x86_64.rpm
+		    ;;
+		(8.*)
+		    rpmfile=${PKG_NAME}-8.0.*-*.el8.x86_64.rpm
+		    ;;
+	    esac
 	    ;;
 	(*)
-	    abort "%s: invalid argument" "$1"
+	    tarfile=${PKG_NAME}-8.0.*-linux-$ID$VERSION_ID-x86-64bit.tar.gz
+	    ;;
+    esac
+
+    case "$ID" in
+	(debian|ubuntu)
+	    case "$(basename "$1")" in
+		($tarfile)
+		    tarpath=$1
+		    tarfile=$(basename $tarpath)
+		    basename=${tarfile%.tar.gz}
+		    package=${basename%-linux-*-x86-64bit}
+		    ;;
+		(*)
+		    abort "%s: invalid argument" "$1"
+	    esac
+	    ;;
+	(rhel|ol)
+	    case "$(basename "$1")" in
+		($rpmfile)
+		    rpmpath=$1
+		    rpmfile=$(basename $rpmpath)
+		    basename=${rpmfile%.rpm}
+		    package=${basename%-linux-*-x86_64}
+		    ;;
+		(*)
+		    abort "%s: invalid argument" "$1"
+	    esac
+	    ;;
     esac
 }
 
@@ -97,6 +139,16 @@ validate_platform() {
 	(debian)
 	    case "$VERSION_ID" in
 		(10)
+		    return
+		    ;;
+	    esac
+	    ;;
+	(rhel|ol)
+	    case "$VERSION_ID" in
+		(7.*)
+		    return
+		    ;;
+		(8.*)
 		    return
 		    ;;
 	    esac
