Set parameter script to "$(basename "$0")" for use in diagnostics.

diff --git a/install-git-build-deps b/install-git-build-deps
--- a/install-git-build-deps
+++ b/install-git-build-deps
@@ -22,11 +22,11 @@ abort() {
 }
 
 abort_not_supported() {
-    abort '%s: %s: %s not supported\n' "$0" "$PRETTY_NAME" "$*"
+    abort '%s: %s: %s not supported\n' "$script" "$PRETTY_NAME" "$*"
 }
 
 assert() {
-    "$@" || abort '%s: Assertion failed: %s\n' "$0" "$*"
+    "$@" || abort '%s: Assertion failed: %s\n' "$script" "$*"
 }
 
 install_git_build_deps() {
@@ -115,6 +115,8 @@ validate_platform() {
     abort_not_supported "Operating system"
 }
 
+script=$(basename "$0")
+
 case "$0" in
     (*/*)
 	script_dir=$(cd "$(dirname "$0")" && pwd)
@@ -129,7 +131,7 @@ script_prefix=${script_dir:+$script_dir/}
 . "${script_prefix}common-functions.sh"
 
 if [ $# -gt 0 ]; then
-    usage_error '%s: Too many arguments\n' "$0"
+    usage_error '%s: Too many arguments\n' "$script"
 fi
 
 set_user_profile "$script_dir"
diff --git a/install-google-chrome b/install-google-chrome
--- a/install-google-chrome
+++ b/install-google-chrome
@@ -6,7 +6,7 @@ abort() {
 }
 
 assert() {
-    "$@" || abort '%s: Assertion failed: %s\n' "$0" "$*"
+    "$@" || abort '%s: Assertion failed: %s\n' "$script" "$*"
 }
 
 install_google_chrome() {
@@ -45,6 +45,8 @@ usage_error() {
     exit 2
 }
 
+script=$(basename "$0")
+
 case "$0" in
     (*/*)
 	script_dir=$(cd "$(dirname "$0")" && pwd)
@@ -58,11 +60,11 @@ script_prefix=${script_dir:+$script_dir/}
 
 . "${script_prefix}common-functions.sh"
 
+if [ $# -gt 1 ]; then
+    usage_error '%s: Too many arguments\n' "$script"
+fi
+
 set_user_profile "$script_dir"
 eval $(get-os-release -x)
-
-if [ $# -gt 1 ]; then
-    usage_error '%s: Too many arguments\n' "$0"
-fi
 
 install_google_chrome "$@"
diff --git a/install-macos-sdk-headers b/install-macos-sdk-headers
--- a/install-macos-sdk-headers
+++ b/install-macos-sdk-headers
@@ -25,11 +25,11 @@ abort() {
 }
 
 abort_not_supported() {
-    abort '%s: %s: %s not supported\n' "$0" "$PRETTY_NAME" "$*"
+    abort '%s: %s: %s not supported\n' "$script" "$PRETTY_NAME" "$*"
 }
 
 assert() {
-    "$@" || abort '%s: Assertion failed: %s\n' "$0" "$*"
+    "$@" || abort '%s: Assertion failed: %s\n' "$script" "$*"
 }
 
 get_darwin_pkg_pathname() {
@@ -63,9 +63,7 @@ usage_error() {
     exit 2
 }
 
-if [ $# -gt 0 ]; then
-    usage_error '%s: Too many arguments\n' "$0"
-fi
+script=$(basename "$0")
 
 case "$0" in
     (*/*)
@@ -77,6 +75,10 @@ case "$0" in
 esac
 
 script_prefix=${script_dir:+$script_dir/}
+
+if [ $# -gt 0 ]; then
+    usage_error '%s: Too many arguments\n' "$script"
+fi
 
 eval $("${script_prefix}get-os-release" -x)
 install_macos_sdk_headers
diff --git a/manage-app-database b/manage-app-database
--- a/manage-app-database
+++ b/manage-app-database
@@ -22,7 +22,7 @@ abort() {
 }
 
 assert() {
-    "$@" || abort '%s: Assertion failed: %s\n' "$0" "$*"
+    "$@" || abort '%s: Assertion failed: %s\n' "$script" "$*"
 }
 
 format_action() {
@@ -44,7 +44,7 @@ format_database() {
 	    printf '\\"%s\\"\n' "$2"
 	    ;;
 	(*)
-	    abort '%s: Invalid SQL dialect: %s\n' "$0" "$1"
+	    abort '%s: Invalid SQL dialect: %s\n' "$script" "$1"
 	    ;;
     esac
 }
@@ -80,7 +80,7 @@ parse_arguments() {
 	    true
 	    ;;
 	(*)
-	    usage_error '%s: Invalid action: %s\n' "$0" "$1"
+	    usage_error '%s: Invalid action: %s\n' "$script" "$1"
 	    ;;
     esac
 }
@@ -91,9 +91,9 @@ to_upper() {
 
 usage() {
     cat <<EOF >&2
-Usage: $0: create
-       $0: drop
-       $0: -h
+Usage: $script: create
+       $script: drop
+       $script: -h
 EOF
 }
 
@@ -107,11 +107,7 @@ usage_error() {
     exit 2
 }
 
-if [ $# -lt 1 ]; then
-    usage_error '%s: Not enough arguments\n' "$0"
-elif [ $# -gt 1 ]; then
-    usage_error '%s: Too many arguments\n' "$0"
-fi
+script=$(basename "$0")
 
 case "$0" in
     (*/*)
@@ -125,6 +121,12 @@ esac
 script_prefix=${script_dir:+$script_dir/}
 
 . "${script_prefix}common-functions.sh"
+
+if [ $# -lt 1 ]; then
+    usage_error '%s: Not enough arguments\n' "$script"
+elif [ $# -gt 1 ]; then
+    usage_error '%s: Too many arguments\n' "$script"
+fi
 
 set_user_profile "$script_dir"
 env_dir=$(pwd)
diff --git a/run-image b/run-image
--- a/run-image
+++ b/run-image
@@ -22,7 +22,7 @@ abort() {
 }
 
 assert() {
-    "$@" || abort '%s: Assertion failed: %s\n' "$0" "$*"
+    "$@" || abort '%s: Assertion failed: %s\n' "$script" "$*"
 }
 
 get_buildah_from_options() {
@@ -142,7 +142,9 @@ parse_arguments() {
 			method="$OPTARG"
 			;;
 		    (*)
-			usage_error '%s: %s: Invalid method\n' "$0" "$OPTARG"
+			usage_error '%s: %s: Invalid method\n' \
+				    "$script" \
+				    "$OPTARG"
 			;;
 		esac
 		;;
@@ -174,9 +176,9 @@ parse_arguments() {
     shift $(($OPTIND - 1))
 
     if [ $# -lt 1 ]; then
-	usage_error '%s: Not enough arguments\n' "$0"
+	usage_error '%s: Not enough arguments\n' "$script"
     elif [ $# -gt 1 ]; then
-	usage_error '%s: Too many arguments\n' "$0"
+	usage_error '%s: Too many arguments\n' "$script"
     fi
 
     file=$1
@@ -188,13 +190,13 @@ parse_arguments() {
 		dockerfile="$file"
 		;;
 	    (*)
-		abort '%s: %s: Not a Dockerfile\n' "$0" "$file"
+		abort '%s: %s: Not a Dockerfile\n' "$script" "$file"
 		;;
 	esac
     elif [ -e "$file" ]; then
-	abort '%s: %s: Not a Dockerfile\n' "$0" "$file"
+	abort '%s: %s: Not a Dockerfile\n' "$script" "$file"
     else
-	abort '%s: %s: No such file\n' "$0" "$file"
+	abort '%s: %s: No such file\n' "$script" "$file"
     fi
 }
 
@@ -222,9 +224,9 @@ run_image() {
 
 usage() {
     cat <<EOF >&2
-Usage: $0 [-M METHOD] [-c COMMAND] [-f FROM-OPTIONS] [-o OPTIONS] [-r] \
+Usage: $script [-M METHOD] [-c COMMAND] [-f FROM-OPTIONS] [-o OPTIONS] [-r] \
 [-t TAG] DOCKERFILE
-       $0 -h
+       $script -h
 EOF
 }
 
@@ -237,6 +239,8 @@ usage_error() {
     usage
     exit 2
 }
+
+script=$(basename "$0")
 
 case "$0" in
     (*/*)
