Fix various issues in configurations and scripts to install Docker.

diff --git a/install-docker b/install-docker
--- a/install-docker
+++ b/install-docker
@@ -22,11 +22,11 @@ abort() {
 }
 
 abort_not_supported() {
-    abort "%s: %s: %s not supported\n" "$0" "$PRETTY_NAME" "$*"
+    abort "%s: %s: %s not supported\n" "$script" "$PRETTY_NAME" "$*"
 }
 
 assert() {
-    "$@" || abort "%s: Assertion failed: %s\n" "$0" "$*"
+    "$@" || abort "%s: Assertion failed: %s\n" "$script" "$*"
 }
 
 configure_daemon_group() {
@@ -208,10 +208,10 @@ validate_platform() {
 
     case "$arch" in
 	(amd64)
-	    :
+	    true
 	    ;;
 	(*)
-	    abort "%s: %s: Architecture not supported\n" "$0" "$arch"
+	    abort "%s: %s: Architecture not supported\n" "$script" "$arch"
 	    ;;
     esac
 
@@ -330,8 +330,10 @@ validate_platform() {
 }
 
 if [ $# -gt 0 ]; then
-    usage_error "%s: Too many arguments\n" "$0"
+    usage_error "%s: Too many arguments\n" "$script"
 fi
+
+script=$(basename "$0")
 
 case "$0" in
     (*/*)
