Install nodejs prior to installing the CLI in install-angular-cli.

diff --git a/install-angular-cli b/install-angular-cli
--- a/install-angular-cli
+++ b/install-angular-cli
@@ -16,4 +16,41 @@
 # You should have received a copy of the GNU General Public License
 # along with this program.  If not, see <https://www.gnu.org/licenses/>.
 
-npm install -g @angular/cli
+abort() {
+    printf "$@" >&2
+    exit 1
+}
+
+assert() {
+    "$@" || abort "%s: Assertion failed: %s\n" "$0" "$*"
+}
+
+get_realpath() (
+    assert [ $# -ge 1 ]
+    realpath=$(which realpath)
+
+    if [ -n "$realpath" ]; then
+	$realpath "$@"
+    else
+	for file; do
+	    if expr "$file" : '/.*' >/dev/null; then
+		printf "%s\n" "$file"
+	    else
+		printf "%s\n" "$PWD/${file#./}"
+	    fi
+	done
+    fi
+)
+
+install_angular_cli() {
+    install-packages nodejs
+    npm install -g @angular/cli
+}
+
+script_dir=$(get_realpath "$(dirname "$0")")
+
+. "$script_dir/common-functions.sh"
+. "$script_dir/utility-functions.sh"
+
+set_user_profile "$script_dir"
+install_angular_cli
