Add check for operating system to script install-opencsw.

diff --git a/install-opencsw b/install-opencsw
--- a/install-opencsw
+++ b/install-opencsw
@@ -16,4 +16,60 @@
 # You should have received a copy of the GNU General Public License
 # along with this program.  If not, see <https://www.gnu.org/licenses/>.
 
-pkgadd -d http://get.opencsw.org/now
+URL=http://get.opencsw.org/now
+
+abort() {
+    printf "$@" >&2
+    exit 1
+}
+
+abort_not_supported() {
+    abort "%s: %s: %s not supported\n" "$0" "$PRETTY_NAME" "$*"
+}
+
+assert() {
+    "$@" || abort "%s: Assertion failed: %s\n" "$0" "$*"
+}
+
+get_realpath() (
+    assert [ $# -ge 1 ]
+    realpath=$(which realpath)
+
+    if [ -n "$realpath" ]; then
+    	$realpath "$@"
+    else
+	for file; do
+	    if expr "$file" : '/.*' >/dev/null; then
+		printf "%s\n" "$file"
+	    else
+		printf "%s\n" "$PWD/${file#./}"
+	    fi
+	done
+    fi
+)
+
+install_opencsw() {
+    validate_platform
+    pkgadd -d $URL
+}
+
+validate_platform() {
+    for id in $ID $ID_LIKE; do
+	case "$id" in
+	    (illumos)
+		abort_not_supported "Operating system"
+    		;;
+	    (solaris)
+		return
+    		;;
+	esac
+    done
+
+    abort_not_supported "Operating system"
+}
+
+script_dir=$(get_realpath "$(dirname "$0")")
+
+eval $("$script_dir/get-os-release" -x)
+
+install_opencsw
