Refactor scripts to use and manage Python virtual environments.

diff --git a/refresh-virtualenv b/refresh-virtualenv
--- a/refresh-virtualenv
+++ b/refresh-virtualenv
@@ -24,7 +24,7 @@ abort() {
 }
 
 assert() {
-    "$@" || abort "%s: Assertion failed: %s\n" "$0" "$*"
+    "$@" || abort '%s: Assertion failed: %s\n' "$script" "$*"
 }
 
 chown_real_user() {
@@ -37,13 +37,27 @@ chown_real_user() {
     fi
 }
 
+configure_platform() {
+    case "${uname_kernel=$(uname -s)}" in
+	(MINGW64_NT-*)
+	    pypi_utilities=pip
+	    ;;
+	(*)
+	    pypi_utilities=
+	    ;;
+    esac
+}
+
 get_packages() {
     "${script_prefix}get-packages" $CATEGORIES
 }
 
 install_dependencies() {
-    case "$ID" in
-	(windows)
+    case "${uname_kernel=$(uname -s)}" in
+	(CYGWIN_NT-*)
+	    return 0
+	    ;;
+	(MINGW64_NT-*)
 	    return 0
 	    ;;
     esac
@@ -58,9 +72,9 @@ install_dependencies() {
 }
 
 parse_arguments() {
-    while getopts p:v:h opt; do
+    while getopts u:v:h opt; do
 	case $opt in
-	    (p)
+	    (u)
 		pypi_utilities=$OPTARG
 		;;
 	    (v)
@@ -95,7 +109,7 @@ refresh_via_pipenv() {
 }
 
 refresh_virtualenv() (
-    for utility in ${pypi_utilities-$PYPI_UTILITIES}; do
+    for utility in ${pypi_utilities:-$PYPI_UTILITIES}; do
 	case "$utility" in
 	    (pipenv)
 		pipenv=$(get_command pipenv || true)
@@ -128,8 +142,8 @@ refresh_virtualenv() (
 
 usage() {
     cat <<EOF >&2
-Usage: $0: [-d <DIR>] [-p <PYPI>] [-v <VENV>]
-       $0: -h
+Usage: $script: [-u <PYPI-UTILITIES>] [-v <VENV-UTILITIES>]
+       $script: -h
 EOF
 }
 
@@ -138,17 +152,12 @@ usage_error() {
 	printf "$@" >&2
     fi
 
-    printf "%s\n" '' >&2
+    printf '%s\n' '' >&2
     usage
     exit 2
 }
 
-export LANG=${LANG-en_US.UTF-8}
-export LC_ALL=${LC_ALL-en_US.UTF-8}
-
-if [ -n "${VIRTUAL_ENV:-}" ]; then
-    abort "%s: Must not be run within a virtual environment\n" "$0"
-fi
+script=$(basename "$0")
 
 case "$0" in
     (*/*)
@@ -164,9 +173,17 @@ script_prefix=${script_dir:+$script_dir/}
 . "${script_prefix}common-functions.sh"
 . "${script_prefix}utility-functions.sh"
 
+export LANG=${LANG-en_US.UTF-8}
+export LC_ALL=${LC_ALL-en_US.UTF-8}
+
+if [ -n "${VIRTUAL_ENV:-}" ]; then
+    abort "%s: Must not be run within a virtual environment\n" "$0"
+fi
+
 set_user_profile "$script_dir"
-eval $(get-os-release -x)
 eval $(get-configuration app.ini)
+eval $(get-os-release -x)
+configure_platform
 parse_arguments "$@"
 
 if [ "$(id -u)" -eq 0 ]; then
