Add missing shell function to script remove-from-path and refactor.

diff --git a/remove-from-path b/remove-from-path
--- a/remove-from-path
+++ b/remove-from-path
@@ -16,22 +16,46 @@
 # You should have received a copy of the GNU General Public License
 # along with this program.  If not, see <https://www.gnu.org/licenses/>.
 
-if [ $# -gt 0 ]; then
-    value="$(printf "%s\n" "$PATH" | sed -e 's|^'"$1"':||g;s|:'"$1"':|:|g;s|:'"$1"'$||g')"
+SED_EXPR='s|^%s:||g;s|:%s:|:|g;s|:%s$||g\n'
+
+abort() {
+    printf "$@" >&2
+    exit 1
+}
+
+assert() {
+    "$@" || abort "%s: Assertion failed: %s\n" "$0" "$*"
+}
+
+filter_path() {
+    assert [ $# -eq 1 ]
+    assert [ -n "$1" ]
+    sed -e "$(printf "$SED_EXPR" "$1" "$1" "$1")"
+}
+
+remove_from_path() {
+    path=$1
+    shift
+
+    for dir; do
+	path="$(printf "%s\n" "$path" | filter_path $dir)"
+    done
 
     case $(basename $SHELL) in
 	(bash|fish|ksh|ksh93|rbash|zsh)
-	    printf "export %s=%s\n" PATH "$value"
+	    printf "export %s=%s\n" path "$path"
 	    ;;
 	(csh|tcsh)
-	    printf "setenv %s %s;\n" PATH "$value"
+	    printf "setenv %s %s;\n" path "$path"
 	    ;;
 	(sh)
-	    printf "%s=%s\n" PATH "$value"
-	    printf "export %s\n" PATH
+	    printf "%s=%s\n" path "$path"
+	    printf "export %s\n" path
 	    ;;
 	(*)
 	    abort "%s: %s: Shell not supported\n" "$0" "$SHELL"
 	    ;;
     esac
-fi
+}
+
+remove_from_path $PATH "$@"
