Abort tunnel set-up if platform is not Debian or Ubuntu.

diff --git a/set-up-tunnel b/set-up-tunnel
--- a/set-up-tunnel
+++ b/set-up-tunnel
@@ -18,6 +18,50 @@
 
 NETWORK=10.10.0.0/23
 
+abort() {
+    printf "$@" >&2
+    exit 1
+}
+
+assert() {
+    "$@" || abort "%s: Assertion failed: %s\n" "$0" "$*"
+}
+
+realpath() {
+    assert [ -d "$1" ]
+
+    if [ -x /usr/bin/realpath ]; then
+	/usr/bin/realpath "$1"
+    else
+	if expr "$1" : '/.*' >/dev/null; then
+	    printf "%s\n" "$1"
+	else
+	    printf "%s\n" "$PWD/${1#./}"
+	fi
+    fi
+}
+
+script_dir=$(realpath "$(dirname "$0")")
+
+distro_name=$(sh -eu $script_dir/get-os-release -i)
+kernel_name=$(sh -eu $script_dir/get-os-release -k)
+pretty_name=$(sh -eu $script_dir/get-os-release -p)
+
+case "$kernel_name" in
+    (Linux)
+	case "$distro_name" in
+	    (debian|ubuntu)
+	    	;;
+	    (*)
+		abort "%s: Distro not supported\n" "$pretty_name"
+		;;
+	esac
+	;;
+    (*)
+	abort "%s: Operating system not supported\n" "$kernel_name"
+	;;
+esac
+
 iptables -t nat -A POSTROUTING -s $NETWORK -j MASQUERADE  
 iptables -A FORWARD -s $NETWORK -j ACCEPT
 iptables -A FORWARD -d $NETWORK -j ACCEPT
