Refactor scripts to set additional publishers on Solaris platforms.

diff --git a/set-publisher-sfe-on-openindiana b/set-publisher-sfe-on-openindiana
--- a/set-publisher-sfe-on-openindiana
+++ b/set-publisher-sfe-on-openindiana
@@ -1,7 +1,7 @@
-#!/bin/sh
+#!/bin/sh -eu
 
-# set-publisher-sfe-on-openindiana: set publisher OpenIndiana SFE
-# Copyright (C) 2018  "Michael G. Morey" <mgmorey@gmail.com>
+# set-publisher-sfe-on-openindiana: add publisher SFE on OpenIndiana
+# Copyright (C) 2019  "Michael G. Morey" <mgmorey@gmail.com>
 
 # This program is free software: you can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
@@ -16,4 +16,29 @@
 # You should have received a copy of the GNU General Public License
 # along with this program.  If not, see <https://www.gnu.org/licenses/>.
 
-pkg set-publisher -p http://pkg.openindiana.org/sfe
+URL=http://pkg.openindiana.org/sfe
+
+abort() {
+    printf "$@" >&2
+    exit 1
+}
+
+assert() {
+    "$@" || abort "%s: Assertion failed: %s\n" "$0" "$*"
+}
+
+get_publisher_data() {
+    assert [ $# -eq 1 ]
+    assert [ -n "$1" ]
+    awk -v publisher=$1 'NR > 1 && $1 == publisher && $2 == "origin" {print $0}'
+}
+
+set_publisher_sfe() {
+    data=$(pkg publisher | get_publisher_data sfe)
+
+    if [ -z "$data" ]; then
+	pkg set-publisher -p $URL
+    fi
+}
+
+set_publisher_sfe
diff --git a/set-publisher-solarisstudio b/set-publisher-solarisstudio
--- a/set-publisher-solarisstudio
+++ b/set-publisher-solarisstudio
@@ -1,3 +1,46 @@
-#/bin/sh -eu
+#!/bin/sh -eu
 
-pkg set-publisher -k pkg.oracle.com.key.pem -c pkg.oracle.com.certificate.pem -G "*" -g https://pkg.oracle.com/solarisstudio/release solarisstudio
+# set-publisher-solarisstudio: add publisher SolarisStudio on Oracle Solaris
+# Copyright (C) 2019  "Michael G. Morey" <mgmorey@gmail.com>
+
+# This program is free software: you can redistribute it and/or modify
+# it under the terms of the GNU General Public License as published by
+# the Free Software Foundation, either version 3 of the License, or
+# (at your option) any later version.
+
+# This program is distributed in the hope that it will be useful,
+# but WITHOUT ANY WARRANTY; without even the implied warranty of
+# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
+# GNU General Public License for more details.
+
+# You should have received a copy of the GNU General Public License
+# along with this program.  If not, see <https://www.gnu.org/licenses/>.
+
+CERT=pkg.oracle.com.certificate.pem
+KEY=pkg.oracle.com.key.pem
+URL=https://pkg.oracle.com/solarisstudio/release
+
+abort() {
+    printf "$@" >&2
+    exit 1
+}
+
+assert() {
+    "$@" || abort "%s: Assertion failed: %s\n" "$0" "$*"
+}
+
+get_publisher_data() {
+    assert [ $# -eq 1 ]
+    assert [ -n "$1" ]
+    awk -v publisher=$1 'NR > 1 && $1 == publisher && $2 == "origin" {print $0}'
+}
+
+set_publisher_solarisstudio() {
+    data=$(pkg publisher | get_publisher_data solarisstudio)
+
+    if [ -z "$data" ]; then
+	pkg set-publisher -k $KEY -c $CERT -G "*" -g $URL solarisstudio
+    fi
+}
+
+set_publisher_solarisstudio
